import { describe, expect, it } from "vitest";
import { canClaim, claimJob, deduplicateAlert, deterministicJobKey, eligibleForAi, rateLimitKey, retryDecision, type AutomationJob } from "./automation";
import { createClient } from "@libsql/client";
import { applySchemaMigrations } from "./schema-migrations";
import { claimNextJob, enqueueJob } from "./automation-service";
const job: AutomationJob = { id: "j", organizationId: "org", type: "SOURCE_ACQUISITION", targetType: "operation", targetId: "op", scheduledAt: "2026-01-01T00:00:00.000Z", status: "PENDING", attempts: 1, maxAttempts: 3, idempotencyKey: "k", leaseUntil: null, startedAt: null, completedAt: null, nextAttemptAt: null, errorCode: null, errorMessage: null, createdBy: "system" };
async function preparePersistentQueue(client: ReturnType<typeof createClient>, organizationId: string, targetIds: readonly string[]) { await client.execute("CREATE TABLE operations (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL)"); for (const id of targetIds) await client.execute({ sql: "INSERT INTO operations(id,organization_id) VALUES(?,?)", args: [id, organizationId] }); await applySchemaMigrations(client); }
describe("automation safety", () => { it("claims once and recovers expired leases", () => { const running = claimJob(job, "worker", new Date("2026-01-01T00:00:00Z")); expect(running.status).toBe("RUNNING"); expect(canClaim(running, new Date("2026-01-01T00:00:01Z"))).toBe(false); expect(canClaim({ ...running, leaseUntil: "2025-12-31T00:00:00Z" }, new Date("2026-01-01T00:00:01Z"))).toBe(true); }); it("bounds retries and classifies human-required states", () => { expect(retryDecision(job, "TIMEOUT", Date.parse("2026-01-01T00:00:00Z")).retryable).toBe(true); expect(retryDecision(job, "CAPTCHA_REQUIRED").retryable).toBe(false); expect(retryDecision({ ...job, attempts: 3 }, "TIMEOUT").retryable).toBe(false); }); it("keeps deterministic keys and AI eligibility", () => { expect(deterministicJobKey("o", "ALERT", "e", "2026-01-01")).toBe(deterministicJobKey("o", "ALERT", "e", "2026-01-01")); expect(rateLimitKey("o", "p", "r")).toBe("o:p:r"); expect(deduplicateAlert("o", "e", "coverage")).toBe("o:e:coverage"); expect(eligibleForAi(null, 100)).toBe(true); }); });
describe("persistent queue", () => { it("is idempotent and tenant scoped", async () => { const client = createClient({ url: ":memory:" }); await preparePersistentQueue(client, "a", ["op"]); const a = await enqueueJob({ organizationId: "a", type: "ALERT", targetType: "operation", targetId: "op", idempotencyKey: "same", scheduledAt: "2026-01-01T00:00:00.000Z" }, client); const b = await enqueueJob({ organizationId: "a", type: "ALERT", targetType: "operation", targetId: "op", idempotencyKey: "same", scheduledAt: "2026-01-01T00:00:00.000Z" }, client); expect(a.id).toBe(b.id); await expect(enqueueJob({ organizationId: "b", type: "ALERT", targetType: "operation", targetId: "op", idempotencyKey: "cross-tenant", scheduledAt: "2026-01-01T00:00:00.000Z" }, client)).rejects.toThrow("AUTOMATION_TARGET_TENANT_MISMATCH"); expect(await claimNextJob("b", new Date("2026-01-02"), client)).toBeNull(); expect((await claimNextJob("a", new Date("2026-01-02"), client))?.status).toBe("RUNNING"); client.close(); }); });
describe("controlled intake scale", () => { it("accepts 73 logical targets without duplicate jobs on replay", async () => { const client = createClient({ url: ":memory:" }); const ids = Array.from({ length: 73 }, (_, i) => `operation-${i}`); await preparePersistentQueue(client, "scale-org", ids); for (const id of ids) await enqueueJob({ organizationId: "scale-org", type: "SOURCE_ACQUISITION", targetType: "operation", targetId: id, scheduledAt: "2026-01-01T00:00:00.000Z", idempotencyKey: `scale-org:SOURCE_ACQUISITION:${id}:2026-01-01` }, client); for (const id of ids) await enqueueJob({ organizationId: "scale-org", type: "SOURCE_ACQUISITION", targetType: "operation", targetId: id, scheduledAt: "2026-01-01T00:00:00.000Z", idempotencyKey: `scale-org:SOURCE_ACQUISITION:${id}:2026-01-01` }, client); const count = await client.execute("SELECT COUNT(*) AS count FROM automation_jobs WHERE organization_id='scale-org'"); expect(Number(count.rows[0].count)).toBe(73); client.close(); }); });
