export type AutomationJobStatus = "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "RETRY_SCHEDULED" | "CANCELLED";
export type AutomationJobType = "SOURCE_ACQUISITION" | "AI_RECONFIRMATION" | "OPPORTUNITY_REFRESH" | "CONTACT_ENRICHMENT" | "CRM_FOLLOW_UP" | "ALERT";
export type AutomationJob = { id: string; organizationId: string; type: AutomationJobType; targetType: string; targetId: string; scheduledAt: string; status: AutomationJobStatus; attempts: number; maxAttempts: number; idempotencyKey: string; leaseUntil: string | null; startedAt: string | null; completedAt: string | null; nextAttemptAt: string | null; errorCode: string | null; errorMessage: string | null; createdBy: string };
export type RetryDecision = { retryable: boolean; nextAttemptAt: string | null; reason: string };
const nonRetryable = new Set(["INVALID_CREDENTIALS", "CAPTCHA_REQUIRED", "MANUAL_REQUIRED", "AUTH_REQUIRED", "INVALID_INPUT", "AUTHORIZATION_FAILURE", "ENDPOINT_NOT_FOUND"]);
export function retryDecision(job: Pick<AutomationJob, "attempts" | "maxAttempts">, code: string, now = Date.now()): RetryDecision { if (nonRetryable.has(code) || job.attempts >= job.maxAttempts) return { retryable: false, nextAttemptAt: null, reason: "NON_RETRYABLE_OR_LIMIT" }; const delay = Math.min(24 * 60 * 60 * 1000, 1000 * 2 ** Math.max(0, job.attempts - 1)); return { retryable: true, nextAttemptAt: new Date(now + delay).toISOString(), reason: code }; }
export function deterministicJobKey(org: string, type: AutomationJobType, target: string, window: string): string { return `${org}:${type}:${target}:${window}`; }
export function canClaim(job: AutomationJob, now = new Date()): boolean { return job.status === "PENDING" || job.status === "RETRY_SCHEDULED" || (job.status === "RUNNING" && Boolean(job.leaseUntil) && new Date(job.leaseUntil as string) <= now); }
export function claimJob(job: AutomationJob, workerId: string, now = new Date(), leaseMs = 60_000): AutomationJob { if (!canClaim(job, now)) throw new Error("JOB_NOT_CLAIMABLE"); return { ...job, status: "RUNNING", leaseUntil: new Date(now.getTime() + leaseMs).toISOString(), startedAt: job.startedAt ?? now.toISOString(), errorCode: null, errorMessage: null }; }
export function eligibleForAi(lastConfirmedAt: string | null, intervalMs: number, now = Date.now()): boolean { return !lastConfirmedAt || now - new Date(lastConfirmedAt).getTime() >= intervalMs; }
export function rateLimitKey(org: string, provider: string, route: string): string { return `${org}:${provider}:${route}`; }
export function deduplicateAlert(org: string, entity: string, key: string): string { return `${org}:${entity}:${key}`; }
