import { createHash } from "node:crypto";
import { createClient, type Client } from "@libsql/client";
import { z } from "zod";
import { defaultAcquisitionProfile, evaluateAcquisitionReadiness, type AcquisitionProfile } from "./lead-qualification";
import { canonicalizeSourceResult, evaluateSourceCoverage } from "./source-coverage";
import type { SourceAcquisitionResult } from "./research-pipeline";
import { getOperation } from "./operations";
import { dataJudAdapter, djenAdapter, esajAdapter, isOfficialSourceUrl, isValidCnjProcessNumber, normalizeCnjProcessNumber, type DjenLookupResult } from "./acquisition-sources";

const evaluateAutonomousReadiness=evaluateAcquisitionReadiness;

const db = createClient({ url: process.env.DATABASE_URL || "file:central-precatorios.db", authToken: process.env.DATABASE_AUTH_TOKEN });
export const acquisitionJobStates = ["DISCOVERED","FILTERING","ELIGIBILITY_CHECK","INVESTIGATING","RESOLVING_CREDITOR","COLLECTING_EVIDENCE","COLLECTING_CONTACT","CROSS_CHECKING","QUALIFIED_WITH_PENDING","READY_FOR_ANALYST","REJECTED","SOURCE_BLOCKED","WAITING","ERROR","PAUSED"] as const;
export type AcquisitionJobState = typeof acquisitionJobStates[number];
export const officialEvidenceTypes = ["OFICIO_REQUISITORIO","OFICIO_COMPLEMENTAR","REQUISITORIO","PROCESS_DOCUMENT","OFFICIAL_RECORD","OTHER_OFFICIAL_DOCUMENT"] as const;
const jobSelect = `SELECT j.*,o.title,o.debtor,o.tribunal,o.process,o.nominal,o.workflow,o.source FROM autonomous_acquisition_jobs j JOIN operations o ON o.id=j.operation_id AND o.organization_id=j.organization_id`;

export type OfficialEvidenceDocument = { id:string;organizationId:string;operationId:string;documentType:typeof officialEvidenceTypes[number];title:string;source:string;sourceUrl:string;downloadUrl:string;documentIdentifier:string;reference:string;publishedAt:string;collectedAt:string;page:number|null;hash:string;contentFingerprint:string;status:"COLLECTED"|"VERIFIED"|"DIVERGENT"|"FAILED";evidenceStrength:"STRONG"|"MEDIUM"|"WEAK";notes:string;sourceProvenance:OfficialEvidenceSourceProvenance|null };
export type OfficialEvidenceSourceProvenance = { provider:string;sourceId:string;route:string };
export type AcquisitionContact = { id:string;organizationId:string;operationId:string;type:"PHONE"|"MOBILE"|"EMAIL"|"WEBSITE"|"OTHER";value:string;source:string;sourceUrl:string;collectedAt:string;confidence:number;notes:string };
export type AcquisitionJob = { id:string;organizationId:string;operationId:string;operationVersion:number;importBatchId:string;status:AcquisitionJobState;currentStep:string;attempts:number;maxAttempts:number;startedAt:string;finishedAt:string;nextRunAt:string;durationMs:number;lastError:string;workerId:string;priority:number;createdAt:string;updatedAt:string;reasons:string[];summary:Record<string,unknown> };

export async function initializeAutonomousAcquisition(client:Client=db){
 await client.execute(`CREATE TABLE IF NOT EXISTS autonomous_acquisition_jobs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,operation_version INTEGER NOT NULL,import_batch_id TEXT NOT NULL,status TEXT NOT NULL,current_step TEXT NOT NULL,attempts INTEGER NOT NULL,max_attempts INTEGER NOT NULL,started_at TEXT NOT NULL,finished_at TEXT NOT NULL,next_run_at TEXT NOT NULL,duration_ms INTEGER NOT NULL,last_error TEXT NOT NULL,worker_id TEXT NOT NULL,priority REAL NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,reasons_json TEXT NOT NULL,summary_json TEXT NOT NULL)`);
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS acquisition_job_version_idx ON autonomous_acquisition_jobs(organization_id,operation_id,operation_version)");
 await client.execute("CREATE INDEX IF NOT EXISTS acquisition_job_queue_idx ON autonomous_acquisition_jobs(organization_id,status,next_run_at,priority DESC,created_at)");
 await client.execute(`CREATE TABLE IF NOT EXISTS acquisition_events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,job_id TEXT NOT NULL,source_id TEXT NOT NULL,event_type TEXT NOT NULL,status TEXT NOT NULL,query_identifier TEXT NOT NULL,source_url TEXT NOT NULL,query_id TEXT NOT NULL,consulted_at TEXT NOT NULL,source_reference_date TEXT NOT NULL,http_status INTEGER,document_id TEXT NOT NULL,evidence_reference TEXT NOT NULL,access_result TEXT NOT NULL,failure_reason TEXT NOT NULL,details_json TEXT NOT NULL,idempotency_key TEXT NOT NULL)`);
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS acquisition_event_idempotency_idx ON acquisition_events(organization_id,job_id,idempotency_key)");
 await client.execute("CREATE INDEX IF NOT EXISTS acquisition_event_timeline_idx ON acquisition_events(organization_id,operation_id,consulted_at DESC)");
 await client.execute(`CREATE TABLE IF NOT EXISTS official_evidence_documents(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,document_type TEXT NOT NULL,title TEXT NOT NULL,source TEXT NOT NULL,source_url TEXT NOT NULL,download_url TEXT NOT NULL,document_identifier TEXT NOT NULL,reference TEXT NOT NULL,published_at TEXT NOT NULL,collected_at TEXT NOT NULL,page INTEGER,hash TEXT NOT NULL,content_fingerprint TEXT NOT NULL,status TEXT NOT NULL,evidence_strength TEXT NOT NULL,notes TEXT NOT NULL,idempotency_key TEXT NOT NULL,source_provenance_json TEXT NOT NULL DEFAULT '{}')`);
 const evidenceColumns=await client.execute("PRAGMA table_info(official_evidence_documents)");if(!evidenceColumns.rows.some(row=>String(row.name)==="source_provenance_json"))await client.execute("ALTER TABLE official_evidence_documents ADD COLUMN source_provenance_json TEXT NOT NULL DEFAULT '{}'");
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS official_evidence_idempotency_idx ON official_evidence_documents(organization_id,operation_id,idempotency_key)");
 await client.execute("CREATE INDEX IF NOT EXISTS official_evidence_case_idx ON official_evidence_documents(organization_id,operation_id,status,document_type)");
 await client.execute(`CREATE TABLE IF NOT EXISTS acquisition_contacts(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,type TEXT NOT NULL,value TEXT NOT NULL,source TEXT NOT NULL,source_url TEXT NOT NULL,collected_at TEXT NOT NULL,confidence REAL NOT NULL,notes TEXT NOT NULL,idempotency_key TEXT NOT NULL)`);
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS acquisition_contact_idempotency_idx ON acquisition_contacts(organization_id,operation_id,idempotency_key)");
 await client.execute(`CREATE TABLE IF NOT EXISTS acquisition_source_cache(source_id TEXT NOT NULL,query_hash TEXT NOT NULL,status TEXT NOT NULL,result_count INTEGER NOT NULL,http_status INTEGER,source_url TEXT NOT NULL,query_id TEXT NOT NULL,consulted_at TEXT NOT NULL,expires_at TEXT NOT NULL,failure_reason TEXT NOT NULL,PRIMARY KEY(source_id,query_hash))`);
 await client.execute(`CREATE TABLE IF NOT EXISTS notification_channels(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,channel TEXT NOT NULL,enabled INTEGER NOT NULL,config_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(organization_id,channel))`);
 await client.execute(`CREATE TABLE IF NOT EXISTS notification_deliveries(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,job_id TEXT NOT NULL,channel TEXT NOT NULL,qualification_key TEXT NOT NULL,status TEXT NOT NULL,scheduled_at TEXT NOT NULL,delivered_at TEXT NOT NULL,attempts INTEGER NOT NULL,last_error TEXT NOT NULL,summary_json TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(organization_id,operation_id,qualification_key,channel))`);
 await client.execute("CREATE INDEX IF NOT EXISTS notification_delivery_schedule_idx ON notification_deliveries(organization_id,status,scheduled_at)");
}

function jsonObject(value:unknown):Record<string,unknown>{try{return JSON.parse(String(value||"{}")) as Record<string,unknown>}catch{return{}}}
function rowJob(row:Record<string,unknown>):AcquisitionJob{return{id:String(row.id),organizationId:String(row.organization_id),operationId:String(row.operation_id),operationVersion:Number(row.operation_version),importBatchId:String(row.import_batch_id),status:String(row.status) as AcquisitionJobState,currentStep:String(row.current_step),attempts:Number(row.attempts),maxAttempts:Number(row.max_attempts),startedAt:String(row.started_at),finishedAt:String(row.finished_at),nextRunAt:String(row.next_run_at),durationMs:Number(row.duration_ms),lastError:String(row.last_error),workerId:String(row.worker_id),priority:Number(row.priority),createdAt:String(row.created_at),updatedAt:String(row.updated_at),reasons:JSON.parse(String(row.reasons_json||"[]")) as string[],summary:jsonObject(row.summary_json)}}
function rowOfficialEvidence(row:Record<string,unknown>):OfficialEvidenceDocument{return{id:String(row.id),organizationId:String(row.organization_id),operationId:String(row.operation_id),documentType:String(row.document_type) as OfficialEvidenceDocument["documentType"],title:String(row.title),source:String(row.source),sourceUrl:String(row.source_url),downloadUrl:String(row.download_url),documentIdentifier:String(row.document_identifier),reference:String(row.reference),publishedAt:String(row.published_at),collectedAt:String(row.collected_at),page:row.page===null?null:Number(row.page),hash:String(row.hash),contentFingerprint:String(row.content_fingerprint),status:String(row.status) as OfficialEvidenceDocument["status"],evidenceStrength:String(row.evidence_strength) as OfficialEvidenceDocument["evidenceStrength"],notes:String(row.notes),sourceProvenance:parseEvidenceProvenance(row.source_provenance_json)}}
function parseEvidenceProvenance(value:unknown):OfficialEvidenceSourceProvenance|null{const parsed=jsonObject(value);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return null;const provider=String(parsed.provider||"").trim(),sourceId=String(parsed.sourceId||"").trim(),route=String(parsed.route||"").trim();return provider&&sourceId&&route?{provider,sourceId,route}:null}
function rowContact(row:Record<string,unknown>):AcquisitionContact{return{id:String(row.id),organizationId:String(row.organization_id),operationId:String(row.operation_id),type:String(row.type) as AcquisitionContact["type"],value:String(row.value),source:String(row.source),sourceUrl:String(row.source_url),collectedAt:String(row.collected_at),confidence:Number(row.confidence),notes:String(row.notes)}}

export async function enqueueImportedBatch(batchId:string,organizationId:string,actorUserId:string,client:Client=db){
 await initializeAutonomousAcquisition(client);
 const rows=await client.execute({sql:"SELECT DISTINCT o.id,o.version,o.nominal,o.workflow FROM capture_import_rows r JOIN operations o ON o.id=r.operation_id AND o.organization_id=r.organization_id WHERE r.organization_id=? AND r.batch_id=? AND o.is_demo=0",args:[organizationId,batchId]});
 const now=new Date().toISOString();
 const statements=rows.rows.map(row=>{const workflow=jsonObject(row.workflow),credit=jsonObject(workflow.credit),priority=Math.min(1000,Number(row.nominal||0)/1000)+(credit.numeroProcessoDEPRE?100:0)+(credit.originProcessNumber?25:0);return{sql:"INSERT OR IGNORE INTO autonomous_acquisition_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[crypto.randomUUID(),organizationId,String(row.id),Number(row.version),batchId,"DISCOVERED","DISCOVERED",0,10,"","","",0,"","",priority,now,now,"[]","{}"]}});
 const inserted=statements.length?await client.batch(statements,"write"):[];
 await client.execute({sql:"INSERT OR IGNORE INTO notification_channels(id,organization_id,channel,enabled,config_json,created_at,updated_at) VALUES(?,?,?,0,?,?,?)",args:[crypto.randomUUID(),organizationId,"TELEGRAM",JSON.stringify({alertsPerBusinessDay:3,timezone:"America/Sao_Paulo",slots:["09:00","12:00","15:00"]}),now,now]});
 return{enqueued:inserted.reduce((sum,result)=>sum+result.rowsAffected,0),actorUserId};
}

export type DocumentaryQualificationInput = Pick<OfficialEvidenceDocument, "sourceUrl" | "documentType" | "status" | "evidenceStrength" | "documentIdentifier" | "reference" | "hash">;
export type DocumentaryQualificationAudit = { qualifies: boolean; reasons: string[]; identity: string | null };
export function auditDocumentaryQualification<T extends DocumentaryQualificationInput>(document: T): DocumentaryQualificationAudit {
 const reasons: string[] = [];
 const qualifyingTypes = new Set<typeof officialEvidenceTypes[number]>(["OFICIO_REQUISITORIO", "OFICIO_COMPLEMENTAR"]);
 if (!isOfficialUrl(document.sourceUrl)) reasons.push("OFFICIAL_URL_REQUIRED");
 if (!qualifyingTypes.has(document.documentType)) reasons.push("DOCUMENT_TYPE_NOT_QUALIFYING");
 if (document.status !== "VERIFIED") reasons.push("STATUS_NOT_VERIFIED");
 if (document.evidenceStrength !== "STRONG") reasons.push("STRENGTH_NOT_STRONG");
 const identifier = document.documentIdentifier.trim(), reference = document.reference.trim();
 if (!identifier && !reference) reasons.push("IDENTIFIER_OR_REFERENCE_REQUIRED");
 const identity = document.hash ? `hash:${document.hash.toLowerCase()}` : identifier ? `document:${identifier.toLowerCase()}` : reference ? `reference:${document.documentType}|${document.sourceUrl}|${reference.toLowerCase()}` : null;
 return { qualifies: reasons.length === 0, reasons, identity };
}
export function countVerifiedOfficialEvidence<T extends DocumentaryQualificationInput>(documents:readonly T[]){const identities=new Set<string>();for(const document of documents){const audit=auditDocumentaryQualification(document);if(audit.qualifies&&audit.identity)identities.add(audit.identity)}return identities.size}
function isOfficialUrl(value:string){return isOfficialSourceUrl(value)}

const evidenceSourceProvenanceSchema=z.object({provider:z.string().trim().min(1).max(120),sourceId:z.string().trim().min(1).max(160),route:z.string().trim().min(1).max(240)}).strict();
const officialEvidenceInput=z.object({operationId:z.string().uuid(),documentType:z.enum(officialEvidenceTypes),title:z.string().trim().min(1).max(240),source:z.string().trim().min(1).max(160),sourceUrl:z.string().url().max(1000),downloadUrl:z.string().url().max(1000).or(z.literal("")).default(""),documentIdentifier:z.string().trim().max(240).default(""),reference:z.string().trim().max(500).default(""),publishedAt:z.union([z.literal(""),z.iso.date()]).default(""),page:z.number().int().positive().nullable().default(null),hash:z.string().regex(/^[a-f0-9]{64}$/i).or(z.literal("")).default(""),contentFingerprint:z.string().max(160).default(""),sourceProvenance:evidenceSourceProvenanceSchema.nullable().default(null),status:z.enum(["COLLECTED","VERIFIED","DIVERGENT","FAILED"]),evidenceStrength:z.enum(["STRONG","MEDIUM","WEAK"]),notes:z.string().trim().max(3000).default(""),idempotencyKey:z.string().trim().min(8).max(200)}).strict();
export async function recordOfficialEvidence(input:z.input<typeof officialEvidenceInput>&{organizationId:string},client:Client=db){
 const data=officialEvidenceInput.parse((( { organizationId:_organizationId, ...fields } )=>fields)(input));if(!isOfficialUrl(data.sourceUrl))throw new Error("OFFICIAL_SOURCE_URL_REQUIRED");if(data.downloadUrl&&!isOfficialUrl(data.downloadUrl))throw new Error("OFFICIAL_DOWNLOAD_URL_REQUIRED");if(data.status==="VERIFIED"&&!data.documentIdentifier.trim()&&!data.reference.trim())throw new Error("INDIVIDUAL_DOCUMENT_IDENTIFIER_REQUIRED");const operation=await getOperation(data.operationId,client,input.organizationId);if(!operation)throw new Error("EVIDENCE_OPERATION_TENANT_MISMATCH");await initializeAutonomousAcquisition(client);const id=crypto.randomUUID(),collectedAt=new Date().toISOString();
 await client.execute({sql:"INSERT OR IGNORE INTO official_evidence_documents(id,organization_id,operation_id,document_type,title,source,source_url,download_url,document_identifier,reference,published_at,collected_at,page,hash,content_fingerprint,status,evidence_strength,notes,idempotency_key,source_provenance_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[id,input.organizationId,data.operationId,data.documentType,data.title,data.source,data.sourceUrl,data.downloadUrl,data.documentIdentifier,data.reference,data.publishedAt,collectedAt,data.page,data.hash,data.contentFingerprint,data.status,data.evidenceStrength,data.notes,data.idempotencyKey,JSON.stringify(data.sourceProvenance)]});
 const row=await client.execute({sql:"SELECT * FROM official_evidence_documents WHERE organization_id=? AND operation_id=? AND idempotency_key=?",args:[input.organizationId,data.operationId,data.idempotencyKey]});return rowOfficialEvidence(row.rows[0]);
}
export async function listOfficialEvidence(operationId:string,organizationId:string,client:Client=db){await initializeAutonomousAcquisition(client);const rows=await client.execute({sql:"SELECT * FROM official_evidence_documents WHERE operation_id=? AND organization_id=? ORDER BY collected_at DESC",args:[operationId,organizationId]});return rows.rows.map(rowOfficialEvidence)}
const contactInput=z.object({operationId:z.string().uuid(),type:z.enum(["PHONE","MOBILE","EMAIL","WEBSITE","OTHER"]),value:z.string().trim().min(1).max(320),source:z.string().trim().min(1).max(160),sourceUrl:z.string().url().max(1000),confidence:z.number().min(0).max(100),notes:z.string().trim().max(1000).default(""),idempotencyKey:z.string().trim().min(8).max(200)}).strict();
export async function recordAcquisitionContact(input:z.input<typeof contactInput>&{organizationId:string},client:Client=db){const data=contactInput.parse((( { organizationId:_organizationId, ...fields } )=>fields)(input));if(!isOfficialUrl(data.sourceUrl))throw new Error("CONTACT_SOURCE_URL_REQUIRED");if(!await getOperation(data.operationId,client,input.organizationId))throw new Error("CONTACT_OPERATION_TENANT_MISMATCH");await initializeAutonomousAcquisition(client);const id=crypto.randomUUID(),collectedAt=new Date().toISOString();await client.execute({sql:"INSERT OR IGNORE INTO acquisition_contacts VALUES(?,?,?,?,?,?,?,?,?,?,?)",args:[id,input.organizationId,data.operationId,data.type,data.value,data.source,data.sourceUrl,collectedAt,data.confidence,data.notes,data.idempotencyKey]});const row=await client.execute({sql:"SELECT * FROM acquisition_contacts WHERE organization_id=? AND operation_id=? AND idempotency_key=?",args:[input.organizationId,data.operationId,data.idempotencyKey]});return rowContact(row.rows[0])}
export async function listAcquisitionContacts(operationId:string,organizationId:string,client:Client=db){await initializeAutonomousAcquisition(client);const rows=await client.execute({sql:"SELECT * FROM acquisition_contacts WHERE operation_id=? AND organization_id=? ORDER BY collected_at DESC",args:[operationId,organizationId]});return rows.rows.map(rowContact)}
export async function listAcquisitionEvents(operationId:string,organizationId:string,client:Client=db){
 await initializeAutonomousAcquisition(client);
 const result=await client.execute({sql:"SELECT * FROM acquisition_events WHERE operation_id=? AND organization_id=? ORDER BY consulted_at DESC",args:[operationId,organizationId]});
 return result.rows.map(row=>({id:String(row.id),sourceId:String(row.source_id),eventType:String(row.event_type),status:String(row.status),queryIdentifier:String(row.query_identifier),sourceUrl:String(row.source_url),queryId:String(row.query_id),consultedAt:String(row.consulted_at),sourceReferenceDate:String(row.source_reference_date),httpStatus:row.http_status===null?null:Number(row.http_status),documentId:String(row.document_id),evidenceReference:String(row.evidence_reference),accessResult:String(row.access_result),failureReason:String(row.failure_reason),details:jsonObject(row.details_json)}));
}

export async function getAutonomousDashboard(organizationId:string,options:{page?:number;pageSize?:number;status?:string;debtor?:string;minValue?:number;maxValue?:number;municipality?:string;nature?:string;confidence?:string;freshness?:string;officialEvidenceCount?:number;contactAvailable?:boolean;identityState?:string}={},client:Client=db){
 await initializeAutonomousAcquisition(client);
 const page=Math.max(1,options.page||1),pageSize=Math.min(100,Math.max(1,options.pageSize||30));
 const counts=await client.execute({sql:"SELECT status,COUNT(*) AS count FROM autonomous_acquisition_jobs WHERE organization_id=? GROUP BY status",args:[organizationId]});
 const byState=Object.fromEntries(counts.rows.map(row=>[String(row.status),Number(row.count)]));
 const where=["j.organization_id=?"],args:(string|number)[]=[organizationId];
 if(options.status){where.push("j.status=?");args.push(options.status)}
 if(options.debtor){where.push("o.debtor LIKE ?");args.push(`%${options.debtor}%`)}
 if(options.minValue!==undefined&&options.minValue!==null){where.push("o.nominal>=?");args.push(options.minValue)}
 if(options.maxValue!==undefined&&options.maxValue!==null){where.push("o.nominal<=?");args.push(options.maxValue)}
 const total=await client.execute({sql:`SELECT COUNT(*) AS count FROM autonomous_acquisition_jobs j JOIN operations o ON o.id=j.operation_id AND o.organization_id=j.organization_id WHERE ${where.join(" AND ")}`,args});
 const jobs=await client.execute({sql:`${jobSelect} WHERE ${where.join(" AND ")} ORDER BY j.priority DESC,j.created_at ASC LIMIT ? OFFSET ?`,args:[...args,pageSize,(page-1)*pageSize]});
 const running=await client.execute({sql:`${jobSelect} WHERE j.organization_id=? AND j.status='INVESTIGATING' ORDER BY j.started_at LIMIT 1`,args:[organizationId]});
 const conflictRows=await client.execute({sql:"SELECT COUNT(DISTINCT operation_id) AS count FROM autonomous_acquisition_jobs WHERE organization_id=? AND reasons_json LIKE '%IDENTITY_CONFLICT%'",args:[organizationId]});
 const nextAlertAt=await nextAlertSlot(organizationId,client);
 return{metrics:{total:Number(total.rows[0]?.count||0),analyzed:Object.entries(byState).filter(([state])=>["REJECTED","QUALIFIED_WITH_PENDING","READY_FOR_ANALYST","WAITING","SOURCE_BLOCKED"].includes(state)).reduce((sum,[,value])=>sum+value,0),inAnalysis:byState.INVESTIGATING||0,qualified:byState.QUALIFIED_WITH_PENDING||0,ready:byState.READY_FOR_ANALYST||0,rejected:byState.REJECTED||0,waitingSource:(byState.WAITING||0)+(byState.SOURCE_BLOCKED||0),conflicts:Number(conflictRows.rows[0]?.count||0),errors:byState.ERROR||0,revalidation:0,byState},processingNow:running.rows[0]?rowJob(running.rows[0]):null,jobs:jobs.rows.map(rowJob),page,pageSize,total:Number(total.rows[0]?.count||0),nextAlertAt,telegramEnabled:false};
}

async function nextAlertSlot(organizationId:string,client:Client){
 const channel=await client.execute({sql:"SELECT config_json FROM notification_channels WHERE organization_id=? AND channel='TELEGRAM'",args:[organizationId]}),config=jsonObject(channel.rows[0]?.config_json),slots=Array.isArray(config.slots)?config.slots.map(String):["09:00","12:00","15:00"],timezone=String(config.timezone||"America/Sao_Paulo"),now=new Date();
 const parts=new Intl.DateTimeFormat("en-CA",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23",weekday:"short"}).formatToParts(now),part=(key:string)=>parts.find(item=>item.type===key)?.value||"",year=Number(part("year")),month=Number(part("month")),day=Number(part("day")),hour=Number(part("hour")),minute=Number(part("minute")),weekday=part("weekday"),weekdayNum=({Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6} as Record<string,number>)[weekday]??0,offsetMs=Date.UTC(year,month-1,day,hour,minute)-now.getTime(),localNow=now.getTime()+offsetMs;
  for(let dayOffset=0;dayOffset<8;dayOffset++){const date=new Date(localNow+dayOffset*86400000),dow=date.getUTCDay();if(dow===0||dow===6)continue;for(const slot of slots){const [slotHour,slotMinute]=slot.split(":").map(Number),candidateLocal=Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate(),slotHour,slotMinute);if(candidateLocal>localNow)return new Date(candidateLocal-offsetMs).toISOString()}}
 return "";
}

async function recordEvent(input:{organizationId:string;operationId:string;jobId:string;sourceId:string;eventType:string;status:string;queryIdentifier?:string;sourceUrl?:string;queryId?:string;httpStatus?:number|null;accessResult?:string;failureReason?:string;details?:Record<string,unknown>;idempotencyKey:string},client:Client){await client.execute({sql:"INSERT OR IGNORE INTO acquisition_events VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[crypto.randomUUID(),input.organizationId,input.operationId,input.jobId,input.sourceId,input.eventType,input.status,input.queryIdentifier||"",input.sourceUrl||"",input.queryId||"",new Date().toISOString(),"",input.httpStatus??null,"","",input.accessResult||"",input.failureReason||"",JSON.stringify(input.details||{}),input.idempotencyKey]})}

async function queryDataJud(processNumber:string,fetcher:typeof fetch=fetch){return dataJudAdapter.lookup({processNumber,fetcher})}

let nextDjenRequestAt = 0;
async function waitForDjenRequestSlot() {
 const now=Date.now(),delayMs=Math.max(0,nextDjenRequestAt-now);
 nextDjenRequestAt=now+delayMs+1000;
 if(delayMs)await new Promise(resolve=>setTimeout(resolve,delayMs));
}

async function investigateDjen(operation:Awaited<ReturnType<typeof getOperation>>,job:AcquisitionJob,client:Client,fetcher:typeof fetch){
 if(!operation)return[];
 const credit=operation.workflow.credit;
 const identifiers=[credit.numeroProcessoDEPRE,credit.originProcessNumber].map(value=>String(value||"").trim()).filter((value,index,all)=>value&&all.indexOf(value)===index);
 const outcomes:Array<Record<string,unknown>>=[];
 for(const identifier of identifiers){
  const queryId=normalizeCnjProcessNumber(identifier);
  const queryHash=createHash("sha256").update(queryId||identifier).digest("hex");
  const now=new Date(),nowIso=now.toISOString();
  let result:DjenLookupResult={sourceId:"djen",status:"INVALID_QUERY",sourceName:"DJEN",sourceType:"PUBLIC_API",jurisdiction:"BRAZIL",access:"PUBLIC",sourceUrl:"",originalIdentifier:identifier,queryId,queriedAt:nowIso,resultCount:0,httpStatus:null,latencyMs:0,requestAttempted:false,rateLimitLimit:null,rateLimitRemaining:null,communications:[],failureReason:""};
  let cached=false;
  let cachedDetails:Record<string,unknown>={};
  if(queryId){
   const cachedRow=await client.execute({sql:"SELECT status,result_count,http_status,source_url,query_id,consulted_at,expires_at,failure_reason FROM acquisition_source_cache WHERE source_id='djen' AND query_hash=? AND expires_at>?",args:[queryHash,nowIso]});
   if(cachedRow.rows[0]){
    const row=cachedRow.rows[0];
    const priorEvent=await client.execute({sql:"SELECT details_json FROM acquisition_events WHERE organization_id=? AND source_id='djen' AND query_id=? AND details_json LIKE '%\"requestAttempted\":true%' ORDER BY consulted_at DESC LIMIT 1",args:[job.organizationId,queryId]});
    cachedDetails=jsonObject(priorEvent.rows[0]?.details_json);
    result={sourceId:"djen",status:String(row.status) as DjenLookupResult["status"],sourceName:"DJEN",sourceType:"PUBLIC_API",jurisdiction:"BRAZIL",access:"PUBLIC",sourceUrl:String(row.source_url),originalIdentifier:identifier,queryId:String(row.query_id),queriedAt:String(row.consulted_at),resultCount:Number(row.result_count),httpStatus:row.http_status===null?null:Number(row.http_status),latencyMs:0,requestAttempted:false,rateLimitLimit:null,rateLimitRemaining:null,communications:[],failureReason:String(row.failure_reason)};
    cached=true;
   }
  }
  if(!cached&&!queryId){
   result=await djenAdapter.lookup({processNumber:identifier,fetcher});
  }else if(!cached){
   const cooldown=await client.execute({sql:"SELECT expires_at FROM acquisition_source_cache WHERE source_id='djen' AND query_hash='global-cooldown' AND expires_at>?",args:[nowIso]});
   if(cooldown.rows[0]){
    result={sourceId:"djen",status:"RATE_LIMITED",sourceName:"DJEN",sourceType:"PUBLIC_API",jurisdiction:"BRAZIL",access:"PUBLIC",sourceUrl:"",originalIdentifier:identifier,queryId,queriedAt:nowIso,resultCount:0,httpStatus:null,latencyMs:0,requestAttempted:false,rateLimitLimit:null,rateLimitRemaining:0,communications:[],failureReason:"Consulta suspensa pelo cooldown global DJEN; nenhuma nova requisição foi enviada."};
   }else{
    await waitForDjenRequestSlot();
    result=await djenAdapter.lookup({processNumber:identifier,fetcher});
   }
  }
  const retrievedAt=new Date().toISOString(),evidenceReference=`acquisition_events:${job.id}:djen:${queryHash}`,partyCandidates=result.communications.flatMap(communication=>communication.partyObservations.map(party=>({...party,source:"djen",processNumber:communication.processNumber||result.queryId,retrievedAt,evidenceReference}))),contacts=result.communications.flatMap(communication=>communication.contacts.map(contact=>({...contact,communicationHash:communication.hash})));
    const sourceResult=canonicalizeSourceResult({provider:"CP_AUTONOMOUS_WORKER",source:"CNJ/ComunicaCNJ",sourceId:"cnj-djen",route:"GET /api/v1/comunicacao",queryIdentifier:identifier,status:result.status,requestAttempted:result.requestAttempted,finishedAt:result.requestAttempted?null:result.queriedAt,durationMs:result.latencyMs,httpStatus:result.httpStatus,officialUrl:result.sourceUrl,resultCount:result.resultCount,errorMessage:result.failureReason});
    const details=cached?{...cachedDetails,cached:true,requestAttempted:false,responseClass:result.status,sourceResult}:{responseClass:result.status,requestAttempted:result.requestAttempted,cached:false,resultCount:result.resultCount,latencyMs:result.latencyMs,originalIdentifier:identifier,normalizedIdentifier:result.queryId,rateLimitLimit:result.rateLimitLimit,rateLimitRemaining:result.rateLimitRemaining,communicationCount:result.communications.length,partyCandidates,contacts,communications:result.communications,sourceResult};
  if(!cached&&result.requestAttempted){
   const ttlMs=result.status==="FOUND"||result.status==="NO_RESULT"?86400000:result.status==="RATE_LIMITED"?60000:300000,expiresAt=new Date(Date.now()+ttlMs).toISOString();
   await client.execute({sql:"INSERT OR REPLACE INTO acquisition_source_cache VALUES('djen',?,?,?,?,?,?,?,?,?)",args:[queryHash,result.status,result.resultCount,result.httpStatus,result.sourceUrl,result.queryId,result.queriedAt,expiresAt,result.failureReason]});
   if(result.status==="RATE_LIMITED"||result.rateLimitRemaining===0){
    const cooldownExpiry=new Date(Date.now()+60000).toISOString();
    await client.execute({sql:"INSERT OR REPLACE INTO acquisition_source_cache VALUES('djen','global-cooldown','RATE_LIMITED',0,?,?,?, ?,?,?)",args:[result.httpStatus,result.sourceUrl,result.queryId,result.queriedAt,cooldownExpiry,result.failureReason||"A API informou que o limite de requisições restantes chegou a zero."]});
   }
  }
  {
   await addEvent({organizationId:job.organizationId,operationId:job.operationId,jobId:job.id,sourceId:"djen",eventType:cached?"CACHE_HIT":"PUBLIC_COMMUNICATION_LOOKUP",status:result.status,queryIdentifier:identifier,sourceUrl:result.sourceUrl,queryId:result.queryId,httpStatus:result.httpStatus,accessResult:result.requestAttempted?result.status:cached?"CACHE_HIT":"NOT_ATTEMPTED",failureReason:result.failureReason,details,idempotencyKey:`djen-${cached?"cache-":""}${queryHash}-${now.toISOString().slice(0,10)}`},client);
  }
  if(result.requestAttempted&&result.communications.length){
   for(const contact of contacts){
    const contactHash=createHash("sha256").update(`${contact.type}|${contact.value.toLowerCase()}|${contact.communicationHash}`).digest("hex");
    await recordAcquisitionContact({organizationId:job.organizationId,operationId:job.operationId,type:contact.type==="EMAIL"?"EMAIL":"PHONE",value:contact.value,source:"DJEN",sourceUrl:result.sourceUrl,confidence:50,notes:"Contato localizado em comunicação pública; não verificado.",idempotencyKey:`djen-${contactHash}`},client);
   }
  }
  outcomes.push({status:result.status,requestAttempted:result.requestAttempted,cached,queryId:result.queryId,httpStatus:result.httpStatus,latencyMs:result.latencyMs,communicationCount:result.resultCount,partyCount:partyCandidates.length,partyRoles:[...new Set(partyCandidates.map(party=>party.role))],contactCount:contacts.length,rateLimitRemaining:result.rateLimitRemaining,failureReason:result.failureReason});
  if(result.status!=="NO_RESULT"&&result.status!=="INVALID_QUERY")break;
 }
 return outcomes;
}

async function getOfficialCount(operationId:string,organizationId:string,client:Client){const rows=await client.execute({sql:"SELECT * FROM official_evidence_documents WHERE operation_id=? AND organization_id=?",args:[operationId,organizationId]});return rows.rows.map(rowOfficialEvidence)}
export async function getAcquisitionProfile(organizationId:string,client:Client=db):Promise<AcquisitionProfile>{
 const row=await client.execute({sql:"SELECT profile_json FROM acquisition_profiles WHERE organization_id=?",args:[organizationId]}).catch(()=>({rows:[]} as {rows:Record<string,unknown>[]})),profile={...defaultAcquisitionProfile,...(row.rows[0]?jsonObject(row.rows[0].profile_json):{})} as AcquisitionProfile;
 const configuredMinimum=Number(profile.minimumOfficialEvidence),configuredAmount=Number(profile.minimumPrecatory);
 return{...profile,minimumOfficialEvidence:Number.isFinite(configuredMinimum)?Math.max(2,Math.trunc(configuredMinimum)):2,minimumPrecatory:Number.isFinite(configuredAmount)&&configuredAmount>=0?configuredAmount:defaultAcquisitionProfile.minimumPrecatory};
}
async function profileFor(organizationId:string,client:Client){return getAcquisitionProfile(organizationId,client)}
async function addEvent(input:Parameters<typeof recordEvent>[0],client:Client){return recordEvent(input,client)}

async function claimNext(organizationId:string,workerId:string,client:Client){const transaction=await client.transaction("write");try{const now=new Date().toISOString(),found=await transaction.execute({sql:"SELECT id FROM autonomous_acquisition_jobs WHERE organization_id=? AND status IN ('DISCOVERED','WAITING','QUALIFIED_WITH_PENDING','SOURCE_BLOCKED','ERROR') AND next_run_at<=? AND attempts<max_attempts ORDER BY priority DESC,created_at ASC LIMIT 1",args:[organizationId,now]});if(!found.rows[0]){await transaction.commit();return null}const id=String(found.rows[0].id),updated=await transaction.execute({sql:"UPDATE autonomous_acquisition_jobs SET status='INVESTIGATING',current_step='ELIGIBILITY_CHECK',started_at=?,finished_at='',worker_id=?,attempts=attempts+1,updated_at=? WHERE id=? AND organization_id=? AND status IN ('DISCOVERED','WAITING','QUALIFIED_WITH_PENDING','SOURCE_BLOCKED','ERROR')",args:[now,workerId,now,id,organizationId]});if(updated.rowsAffected!==1){await transaction.rollback();return null}const job=await transaction.execute({sql:"SELECT * FROM autonomous_acquisition_jobs WHERE id=? AND organization_id=?",args:[id,organizationId]});await transaction.commit();return job.rows[0]?rowJob(job.rows[0]):null}catch(error){await transaction.rollback();throw error}}
async function setJob(job:AcquisitionJob,patch:Partial<AcquisitionJob>,client:Client){const updated={...job,...patch,updatedAt:new Date().toISOString()};await client.execute({sql:"UPDATE autonomous_acquisition_jobs SET status=?,current_step=?,finished_at=?,next_run_at=?,duration_ms=?,last_error=?,worker_id=?,priority=?,updated_at=?,reasons_json=?,summary_json=? WHERE id=? AND organization_id=?",args:[updated.status,updated.currentStep,updated.finishedAt,updated.nextRunAt,updated.durationMs,updated.lastError,updated.workerId,updated.priority,updated.updatedAt,JSON.stringify(updated.reasons),JSON.stringify(updated.summary),updated.id,updated.organizationId]});return updated}

function nextRetry(attempts:number){const delayMinutes=Math.min(24*60,15*Math.pow(2,Math.max(0,attempts-1)));return new Date(Date.now()+delayMinutes*60000).toISOString()}
function summaryFor(operation:Awaited<ReturnType<typeof getOperation>>,readiness:ReturnType<typeof evaluateAcquisitionReadiness>,documents:OfficialEvidenceDocument[],contacts:AcquisitionContact[],requiredEvidence:number){if(!operation)return{};const w=operation.workflow;return{title:"OPPORTUNITY SUMMARY",creditor:w.client.name||"Não identificado",value:operation.nominal,depre:w.credit.numeroProcessoDEPRE||"Não identificado na fonte consultada",process:w.credit.originProcessNumber||w.credit.precatoryNumber||"",debtor:operation.debtor,nature:w.credit.nature||"",contact:contacts.map(item=>({type:item.type,value:item.value,source:item.source,sourceUrl:item.sourceUrl,collectedAt:item.collectedAt})),officialEvidence:`${countVerifiedOfficialEvidence(documents)}/${requiredEvidence}`,source:documents[0]?.source||operation.source,sourceReferenceDate:w.credit.valueDate,lastUpdated:w.credit.checkedAt,identityConfidence:w.creditorResolution.confidence,identityState:w.creditorResolution.state,conflicts:readiness.reasons.filter(reason=>reason==="IDENTITY_CONFLICT"),status:readiness.state,nextAction:readiness.nextAction,evidence:documents.filter(item=>item.status==="VERIFIED").map(item=>({sourceUrl:item.sourceUrl,downloadUrl:item.downloadUrl||undefined,reference:item.reference,documentIdentifier:item.documentIdentifier}))}}

async function writeAlertIfReady(job:AcquisitionJob,summary:Record<string,unknown>,client:Client){const org=job.organizationId,channel=await client.execute({sql:"SELECT enabled,config_json FROM notification_channels WHERE organization_id=? AND channel='TELEGRAM'",args:[org]});if(!Number(channel.rows[0]?.enabled||0))return;const key=createHash("sha256").update(JSON.stringify({jobId:job.id,status:job.status,summary})).digest("hex"),day=new Date().toISOString().slice(0,10),count=await client.execute({sql:"SELECT COUNT(*) AS count FROM notification_deliveries WHERE organization_id=? AND channel='TELEGRAM' AND scheduled_at LIKE ?",args:[org,`${day}%`]}),config=jsonObject(channel.rows[0]?.config_json),limit=Number(config.alertsPerBusinessDay||3),scheduled=Number(count.rows[0]?.count||0)>=limit?nextAlertSlot(org,client):Promise.resolve(new Date().toISOString()),scheduledAt=await scheduled;await client.execute({sql:"INSERT OR IGNORE INTO notification_deliveries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[crypto.randomUUID(),org,job.operationId,job.id,"TELEGRAM",key,"QUEUED",scheduledAt,"",0,"",JSON.stringify(summary),new Date().toISOString()]})}

async function processClaimed(job:AcquisitionJob,client:Client,fetcher:typeof fetch){const start=Date.now(),operation=await getOperation(job.operationId,client,job.organizationId);if(!operation){await setJob(job,{status:"ERROR",currentStep:"ERROR",finishedAt:new Date().toISOString(),nextRunAt:nextRetry(job.attempts),durationMs:Date.now()-start,lastError:"OPERATION_NOT_FOUND",reasons:["DATABASE_ERROR"]},client);return"ERROR"}const profile=await profileFor(job.organizationId,client),documents=await getOfficialCount(job.operationId,job.organizationId,client),contacts=await listAcquisitionContacts(job.operationId,job.organizationId,client),requiredEvidence=profile.minimumOfficialEvidence??2;let readiness=evaluateAutonomousReadiness({creditorName:operation.workflow.client.name,amount:operation.nominal,minimumAmount:profile.minimumPrecatory,numeroProcessoDEPRE:operation.workflow.credit.numeroProcessoDEPRE,debtor:operation.debtor,debtorState:operation.workflow.credit.debtorState,tribunal:operation.tribunal,targetState:profile.state,targetTribunal:profile.tribunal,officialEvidenceCount:countVerifiedOfficialEvidence(documents),requiredOfficialEvidence:requiredEvidence,identityConflict:operation.workflow.creditorResolution.state==="CONFLITO_DE_IDENTIDADE",contactAvailable:contacts.length>0||Boolean(operation.workflow.client.phone||operation.workflow.client.email)});
 const org=job.organizationId,now=new Date().toISOString(),sourceLimit=25;let step="CROSS_CHECKING",lastError="";
 if(readiness.state==="REJECTED"){await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"deterministic-filter",eventType:"ELIGIBILITY_CHECK",status:"REJECTED",accessResult:"NOT_APPLICABLE",failureReason:readiness.reasons.join(","),details:{criteria:readiness.criteria},idempotencyKey:`eligibility-${job.operationVersion}`},client);const summary=summaryFor(operation,readiness,documents,contacts,requiredEvidence);await setJob(job,{status:"REJECTED",currentStep:"FILTERING",finishedAt:now,nextRunAt:"",durationMs:Date.now()-start,lastError:"",reasons:readiness.reasons,summary},client);return"REJECTED"}
 if(readiness.ready){const summary=summaryFor(operation,readiness,documents,contacts,requiredEvidence),readyJob=await setJob(job,{status:"READY_FOR_ANALYST",currentStep:"READY_FOR_ANALYST",finishedAt:now,nextRunAt:"",durationMs:Date.now()-start,lastError:"",reasons:[],summary},client);await writeAlertIfReady(readyJob,summary,client);await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"qualification",eventType:"READY_FOR_ANALYST",status:"READY_FOR_ANALYST",accessResult:"ELIGIBLE",details:{qualificationKey:job.operationVersion,evidenceCount:countVerifiedOfficialEvidence(documents)},idempotencyKey:`ready-${job.operationVersion}`},client);return"READY_FOR_ANALYST"}
 const djenResults=await investigateDjen(operation,job,client,fetcher);
 const processNumber=operation.workflow.credit.numeroProcessoDEPRE||"",dataJudStartedAt=new Date().toISOString();let dataJud:Awaited<ReturnType<typeof dataJudAdapter.lookup>>;
 if(!isValidCnjProcessNumber(processNumber)){dataJud=await queryDataJud(processNumber,fetcher)}
 else if(process.env.DATAJUD_COMMERCIAL_USE_AUTHORIZED!=="true"||!process.env.DATAJUD_PUBLIC_API_KEY?.trim()){dataJud=await queryDataJud(processNumber,fetcher)}
 else {const sourceCount=await client.execute({sql:`SELECT COUNT(*) AS count FROM acquisition_events WHERE organization_id=? AND source_id='datajud' AND consulted_at>=? AND (http_status IS NOT NULL OR details_json LIKE '%"requestAttempted":true%')`,args:[org,new Date(Date.now()-86400000).toISOString()]});if(Number(sourceCount.rows[0]?.count||0)<sourceLimit){step="RESOLVING_CREDITOR";dataJud=await queryDataJud(processNumber,fetcher)}else{dataJud={sourceId:"datajud",status:"DAILY_BUDGET_EXHAUSTED",sourceUrl:"https://api-publica.datajud.cnj.jus.br/api_publica_tjsp/_search",originalIdentifier:processNumber,queryId:normalizeCnjProcessNumber(processNumber),resultCount:0,httpStatus:null,latencyMs:0,requestAttempted:false,parties:[],failureReason:"Limite diário conservador de consultas DataJud atingido."}}}
 const dataJudFinishedAt=new Date().toISOString(),dataJudSourceResult=canonicalizeSourceResult({provider:"CP_AUTONOMOUS_WORKER",source:"CNJ/DataJud",sourceId:"cnj-datajud",route:"POST /api_publica_tjsp/_search",queryIdentifier:dataJud.originalIdentifier,status:dataJud.status,requestAttempted:dataJud.requestAttempted,startedAt:dataJud.requestAttempted?dataJudStartedAt:null,finishedAt:dataJud.requestAttempted?dataJudFinishedAt:null,durationMs:dataJud.latencyMs,httpStatus:dataJud.httpStatus,officialUrl:dataJud.sourceUrl,resultCount:dataJud.resultCount,errorMessage:dataJud.failureReason}),canonicalAcquisitionResult:SourceAcquisitionResult={provider:"CP_AUTONOMOUS_WORKER",source:"CNJ/DataJud",sourceId:"cnj-datajud",route:"POST /api_publica_tjsp/_search",requestedIdentifier:dataJud.originalIdentifier,normalizedIdentifier:dataJud.queryId,startedAt:dataJud.requestAttempted?dataJudStartedAt:null,completedAt:dataJud.requestAttempted?dataJudFinishedAt:null,durationMs:dataJud.latencyMs,status:dataJudSourceResult.status,requestAttempted:dataJud.requestAttempted,httpStatus:dataJud.httpStatus,sourceUrl:dataJud.sourceUrl,officialSourceUrl:dataJudSourceResult.officialUrl,errorCode:dataJudSourceResult.errorCategory,errorMessage:dataJudSourceResult.errorMessage,rawPayload:dataJud,metadata:{partyCandidates:dataJud.parties},documentaryCandidates:[],canonicalResult:dataJudSourceResult},coverage=evaluateSourceCoverage([dataJudSourceResult],null),queryHash=createHash("sha256").update(dataJud.queryId).digest("hex"),retrievedAt=new Date().toISOString(),evidenceReference=`acquisition_events:${job.id}:datajud:${job.attempts}`,partyCandidates=dataJud.parties.map(party=>({...party,source:"datajud",processNumber:dataJud.queryId,retrievedAt,evidenceReference}));const sourceDetails={provider:"CP_AUTONOMOUS_WORKER",source:"CNJ/DataJud",sourceId:"cnj-datajud",route:"POST /api_publica_tjsp/_search",resultCount:dataJud.resultCount,responseClass:dataJud.status,latencyMs:dataJud.latencyMs,requestAttempted:dataJud.requestAttempted,originalIdentifier:dataJud.originalIdentifier,normalizedIdentifier:dataJud.queryId,partyCandidates,djen:djenResults,sourceResult:dataJudSourceResult,canonicalAcquisitionResult,coverage};if(dataJud.status==="SOURCE_UNAVAILABLE"||dataJud.status==="RATE_LIMITED")lastError=dataJud.failureReason;
 await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"datajud",eventType:"PUBLIC_LOOKUP",status:dataJud.status,queryIdentifier:dataJud.originalIdentifier,sourceUrl:dataJud.sourceUrl,queryId:dataJud.queryId,httpStatus:dataJud.httpStatus,accessResult:dataJud.requestAttempted?dataJud.status:"NOT_ATTEMPTED",failureReason:dataJud.failureReason,details:sourceDetails,idempotencyKey:`datajud-${queryHash}-${new Date().toISOString().slice(0,10)}-${job.attempts}`},client);
 if(dataJud.requestAttempted){const esajResult=await esajAdapter.lookup({processNumber});await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:esajResult.sourceId,eventType:"SOURCE_ADAPTER_STATUS",status:esajResult.status,sourceUrl:esajResult.sourceUrl,queryIdentifier:esajResult.originalIdentifier,queryId:esajResult.queryId,accessResult:"NO_REQUEST_MADE",failureReason:esajResult.failureReason,details:{requestAttempted:false,resultCount:esajResult.resultCount},idempotencyKey:`esaj-pending-${job.operationVersion}-${job.attempts}`},client)}
 if(dataJud.requestAttempted)await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"tjsp-cac-pending",eventType:"SOURCE_ADAPTER_STATUS",status:"ASSISTED_SOURCE_REQUIRED",sourceUrl:"https://www.tjsp.jus.br/cac/scp/webrelpubliclstpagprecatpendentes.aspx",queryIdentifier:operation.workflow.credit.numeroProcessoDEPRE,accessResult:"NO_REQUEST_MADE",failureReason:"O worker não coleta listas CAC automaticamente; relatórios precisam entrar pelo fluxo de importação assistida.",details:{requestAttempted:false},idempotencyKey:`cac-blocked-${job.operationVersion}-${job.attempts}`},client);
 const rereadDocs=await getOfficialCount(job.operationId,job.organizationId,client);readiness=evaluateAutonomousReadiness({creditorName:operation.workflow.client.name,amount:operation.nominal,minimumAmount:profile.minimumPrecatory,numeroProcessoDEPRE:operation.workflow.credit.numeroProcessoDEPRE,debtor:operation.debtor,debtorState:operation.workflow.credit.debtorState,tribunal:operation.tribunal,targetState:profile.state,targetTribunal:profile.tribunal,officialEvidenceCount:countVerifiedOfficialEvidence(rereadDocs),requiredOfficialEvidence:requiredEvidence,identityConflict:operation.workflow.creditorResolution.state==="CONFLITO_DE_IDENTIDADE",contactAvailable:contacts.length>0||Boolean(operation.workflow.client.phone||operation.workflow.client.email)});
 const resultIsSourceFailure=["DATAJUD_KEY_NOT_CONFIGURED","DATAJUD_USE_NOT_AUTHORIZED","SOURCE_BLOCKED","SOURCE_UNAVAILABLE","RATE_LIMITED","DAILY_BUDGET_EXHAUSTED","INVALID_IDENTIFIER"].includes(dataJud.status),sourceReason=dataJud.status==="PROCESS_FOUND"?"PARTY_CANDIDATES_REVIEW_REQUIRED":dataJud.status,reasons=[...readiness.reasons.filter(reason=>reason!=="CREDITOR_NOT_IDENTIFIED"),...(readiness.reasons.includes("CREDITOR_NOT_IDENTIFIED")||resultIsSourceFailure?[sourceReason]:[])],criteria=readiness.criteria.map(criterion=>criterion.key==="creditor"&&!operation.workflow.client.name.trim()?{...criterion,label:"Resultado da investigação de partes",detail:dataJud.status==="PROCESS_FOUND"?"Candidatos localizados; titularidade atual requer revisão humana":dataJud.status==="PROCESS_NOT_FOUND"?"Processo não encontrado nesta fonte; outras fontes ainda podem ser consultadas":dataJud.status==="NO_PUBLIC_PARTY_DATA"?"Processo encontrado sem dados públicos de partes":`Investigação não concluída: ${dataJud.status}`} : criterion),summary={...summaryFor(operation,readiness,rereadDocs,contacts,requiredEvidence),creditor:operation.workflow.client.name||(dataJud.parties.length?"Candidato(s) localizado(s) — revisão humana necessária":`Investigação: ${dataJud.status}`),sourceInvestigation:{status:dataJud.status,sourceUrl:dataJud.sourceUrl,originalIdentifier:dataJud.originalIdentifier,queryId:dataJud.queryId,httpStatus:dataJud.httpStatus,latencyMs:dataJud.latencyMs,requestAttempted:dataJud.requestAttempted,partyCandidateCount:dataJud.parties.length}},durationMs=Date.now()-start;
 if(readiness.ready){const readyJob=await setJob(job,{status:"READY_FOR_ANALYST",currentStep:"READY_FOR_ANALYST",finishedAt:now,nextRunAt:"",durationMs,lastError:"",reasons:[],summary},client);await writeAlertIfReady(readyJob,summary,client);await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"qualification",eventType:"READY_FOR_ANALYST",status:"READY_FOR_ANALYST",accessResult:"ELIGIBLE",details:{qualificationKey:job.operationVersion,evidenceCount:countVerifiedOfficialEvidence(rereadDocs)},idempotencyKey:`ready-${job.operationVersion}`},client);return"READY_FOR_ANALYST"}
 const terminal=readiness.state==="REJECTED",status:AcquisitionJobState=terminal?"REJECTED":resultIsSourceFailure?"SOURCE_BLOCKED":readiness.state==="QUALIFIED_WITH_PENDING"?"QUALIFIED_WITH_PENDING":"WAITING",nextRunAt=terminal?"":nextRetry(job.attempts),updated=await setJob(job,{status,currentStep:resultIsSourceFailure?"WAITING_SOURCE":step,finishedAt:now,nextRunAt,durationMs,lastError,reasons,summary},client);await addEvent({organizationId:org,operationId:job.operationId,jobId:job.id,sourceId:"qualification",eventType:"ELIGIBILITY_CHECK",status,accessResult:readiness.ready?"ELIGIBLE":"NOT_READY",failureReason:reasons.join(","),details:{criteria,officialEvidenceCount:countVerifiedOfficialEvidence(rereadDocs),requiredOfficialEvidence:requiredEvidence,contactOptional:true,attempts:updated.attempts,sourceStatus:dataJud.status},idempotencyKey:`eligibility-${job.operationVersion}-${updated.attempts}`},client);return status;
}

export async function processAcquisitionCycle(input:{organizationId:string;actorUserId:string;workerId?:string;limit?:number;client?:Client;fetcher?:typeof fetch}){const client=input.client||db,limit=Math.min(50,Math.max(1,input.limit||10)),workerId=input.workerId||`interactive-${input.actorUserId}`,counts:Record<string,number>={},errors:string[]=[];await initializeAutonomousAcquisition(client);for(let index=0;index<limit;index++){const job=await claimNext(input.organizationId,workerId,client);if(!job)break;try{const state=await processClaimed(job,client,input.fetcher||fetch);counts[state]=(counts[state]||0)+1}catch(error){const reason=error instanceof Error?error.message:"UNKNOWN_ERROR";errors.push(reason.slice(0,200));const next=nextRetry(job.attempts);await setJob(job,{status:"ERROR",currentStep:"ERROR",finishedAt:new Date().toISOString(),nextRunAt:job.attempts>=job.maxAttempts?"":next,durationMs:Date.now()-Date.parse(job.startedAt||job.updatedAt),lastError:reason.slice(0,500),reasons:["UNKNOWN_ERROR"]},client);await addEvent({organizationId:job.organizationId,operationId:job.operationId,jobId:job.id,sourceId:"worker",eventType:"CASE_ERROR",status:"ERROR",accessResult:"WORKER_ERROR",failureReason:reason.slice(0,300),details:{attempt:job.attempts,maxAttempts:job.maxAttempts},idempotencyKey:`error-${job.attempts}`},client)}}return{processed:Object.values(counts).reduce((sum,count)=>sum+count,0)+errors.length,counts,errors:errors.length,workerId}}

export async function runAcquisitionWorker(input:{organizationId:string;actorUserId:string;workerId?:string;limit?:number;idleMs?:number;client?:Client;fetcher?:typeof fetch;signal?:AbortSignal}){const results=[];while(!input.signal?.aborted){const result=await processAcquisitionCycle(input);results.push(result);if(!result.processed)await new Promise(resolve=>setTimeout(resolve,Math.max(250,input.idleMs||5000)));if(results.length>=100)results.shift()}return results}
