import { createClient, type Client } from "@libsql/client";
import { createHash } from "node:crypto";

const db=createClient({url:process.env.DATABASE_URL||"file:central-precatorios.db",authToken:process.env.DATABASE_AUTH_TOKEN});
export type ImportStatus="PROCESSING"|"COMPLETED"|"COMPLETED_WITH_WARNINGS"|"FAILED";
export type ImportSummary={read:number;created:number;updated:number;duplicates:number;conflicts:number;rpvs:number;skipped:number;belowMinimum:number;incomplete:number;errors:number};
export async function initializeCaptureImports(client:Client=db){
 await client.execute(`CREATE TABLE IF NOT EXISTS capture_import_batches(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,source_id TEXT NOT NULL,source_name TEXT NOT NULL,file_name TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT NOT NULL,status TEXT NOT NULL,summary_json TEXT NOT NULL,errors_json TEXT NOT NULL,parser_version TEXT NOT NULL,source_reference TEXT NOT NULL,content_hash TEXT NOT NULL,actor_user_id TEXT NOT NULL)`);
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS capture_import_idempotency_idx ON capture_import_batches(organization_id,source_id,content_hash)");
 await client.execute("CREATE INDEX IF NOT EXISTS capture_import_history_idx ON capture_import_batches(organization_id,started_at DESC)");
 await client.execute("CREATE TABLE IF NOT EXISTS capture_source_events(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,source_id TEXT NOT NULL,checked_at TEXT NOT NULL,success INTEGER NOT NULL,records INTEGER NOT NULL,error TEXT NOT NULL,actor_user_id TEXT NOT NULL)");
 await client.execute("CREATE INDEX IF NOT EXISTS capture_source_events_idx ON capture_source_events(organization_id,source_id,checked_at DESC)");
 await client.execute("CREATE TABLE IF NOT EXISTS capture_import_rows(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,batch_id TEXT NOT NULL,operation_id TEXT NOT NULL,row_number INTEGER NOT NULL,source_reference TEXT NOT NULL,raw_values_json TEXT NOT NULL,normalized_values_json TEXT NOT NULL,observed_at TEXT NOT NULL)");
 await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS capture_import_row_source_idx ON capture_import_rows(organization_id,batch_id,row_number)");
}
export async function beginImport(input:{organizationId:string;userId:string;sourceId:string;sourceName:string;fileName:string;sourceReference:string;bytes:Uint8Array},client:Client=db){
 await initializeCaptureImports(client);const contentHash=createHash("sha256").update(input.bytes).digest("hex");
 const found=await client.execute({sql:"SELECT * FROM capture_import_batches WHERE organization_id=? AND source_id=? AND content_hash=?",args:[input.organizationId,input.sourceId,contentHash]});
 if(found.rows[0])return{duplicate:true as const,batch:rowBatch(found.rows[0])};
 const id=crypto.randomUUID(),startedAt=new Date().toISOString(),empty:ImportSummary={read:0,created:0,updated:0,duplicates:0,conflicts:0,rpvs:0,skipped:0,belowMinimum:0,incomplete:0,errors:0};
 try{await client.execute({sql:"INSERT INTO capture_import_batches VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[id,input.organizationId,input.sourceId,input.sourceName,input.fileName,startedAt,"","PROCESSING",JSON.stringify(empty),"[]","cp-tjsp-import/2.2.1",input.sourceReference,contentHash,input.userId]})}catch(e){if(e instanceof Error&&e.message.includes("UNIQUE")){const again=await client.execute({sql:"SELECT * FROM capture_import_batches WHERE organization_id=? AND source_id=? AND content_hash=?",args:[input.organizationId,input.sourceId,contentHash]});if(again.rows[0])return{duplicate:true as const,batch:rowBatch(again.rows[0])}}throw e}
 return{duplicate:false as const,batch:{id,organizationId:input.organizationId,sourceId:input.sourceId,sourceName:input.sourceName,fileName:input.fileName,startedAt,finishedAt:"",status:"PROCESSING" as ImportStatus,summary:empty,errors:[] as unknown[],parserVersion:"cp-tjsp-import/2.2.1",sourceReference:input.sourceReference,contentHash,actorUserId:input.userId}};
}
export async function finishImport(id:string,organizationId:string,status:ImportStatus,summary:ImportSummary,errors:unknown[],client:Client=db){await initializeCaptureImports(client);const finishedAt=new Date().toISOString();await client.execute({sql:"UPDATE capture_import_batches SET finished_at=?,status=?,summary_json=?,errors_json=? WHERE id=? AND organization_id=?",args:[finishedAt,status,JSON.stringify({...summary,errors:errors.length}),JSON.stringify(errors.slice(0,300)),id,organizationId]});}
function rowBatch(r:Record<string,unknown>){return{id:String(r.id),organizationId:String(r.organization_id),sourceId:String(r.source_id),sourceName:String(r.source_name),fileName:String(r.file_name),startedAt:String(r.started_at),finishedAt:String(r.finished_at),status:String(r.status) as ImportStatus,summary:JSON.parse(String(r.summary_json)) as ImportSummary,errors:JSON.parse(String(r.errors_json)) as unknown[],parserVersion:String(r.parser_version),sourceReference:String(r.source_reference),contentHash:String(r.content_hash),actorUserId:String(r.actor_user_id)}}
export async function listImportBatches(organizationId:string,client:Client=db){await initializeCaptureImports(client);const r=await client.execute({sql:"SELECT * FROM capture_import_batches WHERE organization_id=? ORDER BY started_at DESC LIMIT 100",args:[organizationId]});return r.rows.map(rowBatch)}
export async function recordSourceEvent(input:{organizationId:string;sourceId:string;success:boolean;records:number;error?:string;userId:string},client:Client=db){await initializeCaptureImports(client);await client.execute({sql:"INSERT INTO capture_source_events VALUES(?,?,?,?,?,?,?,?)",args:[crypto.randomUUID(),input.organizationId,input.sourceId,new Date().toISOString(),input.success?1:0,input.records,input.error||"",input.userId]})}
export async function listSourceEvents(organizationId:string,client:Client=db){await initializeCaptureImports(client);const r=await client.execute({sql:"SELECT * FROM capture_source_events WHERE organization_id=? ORDER BY checked_at DESC LIMIT 500",args:[organizationId]});return r.rows.map(x=>({sourceId:String(x.source_id),checkedAt:String(x.checked_at),success:Boolean(x.success),records:Number(x.records),error:String(x.error),actorUserId:String(x.actor_user_id)}))}
export async function recordImportSourceRow(input:{organizationId:string;batchId:string;operationId:string;rowNumber:number;sourceReference:string;rawValues:unknown;normalizedValues:unknown},client:Client=db){await initializeCaptureImports(client);await client.execute({sql:"INSERT OR IGNORE INTO capture_import_rows VALUES(?,?,?,?,?,?,?,?,?)",args:[crypto.randomUUID(),input.organizationId,input.batchId,input.operationId,input.rowNumber,input.sourceReference,JSON.stringify(input.rawValues),JSON.stringify(input.normalizedValues),new Date().toISOString()]})}
