import { createClient, type Client } from "@libsql/client";
import { canTransition, type CrmActivity, type CrmRecord, type CrmStage, type CrmTask } from "./crm";
import { assertSchemaMigrations } from "./schema-migrations";
import { createDatabaseClient } from "./database-config";

const db = createDatabaseClient();
/** Runtime guard only; schema changes are applied by the explicit migration command. */
export async function initializeCrm(client: Client = db) { await assertSchemaMigrations(client); }
function record(row: Record<string, unknown>): CrmRecord { return { id: String(row.id), organizationId: String(row.organization_id), operationId: String(row.operation_id), opportunityId: row.opportunity_id ? String(row.opportunity_id) : null, contactIds: JSON.parse(String(row.contact_ids)), stage: String(row.stage) as CrmStage, createdAt: String(row.created_at), updatedAt: String(row.updated_at), nextActionAt: row.next_action_at ? String(row.next_action_at) : null }; }
function task(row: Record<string, unknown>): CrmTask { return { id: String(row.id), organizationId: String(row.organization_id), crmId: String(row.crm_id), title: String(row.title), description: String(row.description), dueAt: row.due_at ? String(row.due_at) : null, status: String(row.status) as CrmTask["status"], priority: String(row.priority) as CrmTask["priority"], assigneeId: row.assignee_id ? String(row.assignee_id) : null, completedAt: row.completed_at ? String(row.completed_at) : null, idempotencyKey: String(row.idempotency_key) }; }
function activity(row: Record<string, unknown>): CrmActivity { return { id: String(row.id), organizationId: String(row.organization_id), crmId: String(row.crm_id), actorId: String(row.actor_id), type: String(row.type) as CrmActivity["type"], notes: String(row.notes), occurredAt: String(row.occurred_at) }; }
export async function createCrmRecord(input: Omit<CrmRecord, "createdAt" | "updatedAt">, client: Client = db): Promise<CrmRecord> { await initializeCrm(client); const now = new Date().toISOString(); await client.execute({ sql: `INSERT INTO crm_records VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,operation_id) DO NOTHING`, args: [input.id, input.organizationId, input.operationId, input.opportunityId, JSON.stringify(input.contactIds), input.stage, now, now, input.nextActionAt] }); const result = await client.execute({ sql: "SELECT * FROM crm_records WHERE organization_id=? AND operation_id=?", args: [input.organizationId, input.operationId] }); if (!result.rows[0]) throw new Error("CRM_CREATE_FAILED"); return record(result.rows[0] as Record<string, unknown>); }
export async function getCrmRecord(id: string, organizationId: string, client: Client = db): Promise<CrmRecord | null> { await initializeCrm(client); const result = await client.execute({ sql: "SELECT * FROM crm_records WHERE id=? AND organization_id=?", args: [id, organizationId] }); return result.rows[0] ? record(result.rows[0] as Record<string, unknown>) : null; }
export async function listCrmRecords(organizationId: string, client: Client = db): Promise<CrmRecord[]> { await initializeCrm(client); const result = await client.execute({ sql: "SELECT * FROM crm_records WHERE organization_id=? ORDER BY updated_at DESC", args: [organizationId] }); return result.rows.map((row) => record(row as Record<string, unknown>)); }
export async function changeCrmStage(id: string, organizationId: string, to: CrmStage, actorId: string, reason = "", client: Client = db): Promise<CrmRecord> { const current = await getCrmRecord(id, organizationId, client); if (!current || !canTransition(current.stage, to)) throw new Error("CRM_INVALID_TRANSITION"); if (to === "CONTACTED" || to === "NEGOTIATION") { const contact = await client.execute({ sql: "SELECT 1 FROM crm_activities WHERE crm_id=? AND organization_id=? AND type IN ('CALL_COMPLETED','EMAIL_MANUAL','MEETING') LIMIT 1", args: [id, organizationId] }); if (!contact.rows[0]) throw new Error("CRM_CONTACT_ACTIVITY_REQUIRED"); } const now = new Date().toISOString(); await client.execute({ sql: "UPDATE crm_records SET stage=?,updated_at=? WHERE id=? AND organization_id=?", args: [to, now, id, organizationId] }); await client.execute({ sql: "INSERT INTO crm_stage_history VALUES (?,?,?,?,?,?,?,?)", args: [crypto.randomUUID(), organizationId, id, current.stage, to, actorId, reason, now] }); return { ...current, stage: to, updatedAt: now }; }
export async function createCrmTask(input: CrmTask, client: Client = db): Promise<CrmTask> { await initializeCrm(client); if (!await getCrmRecord(input.crmId, input.organizationId, client)) throw new Error("CRM_NOT_FOUND"); await client.execute({ sql: "INSERT INTO crm_tasks VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(organization_id,idempotency_key) DO NOTHING", args: [input.id, input.organizationId, input.crmId, input.title, input.description, input.dueAt, input.status, input.priority, input.assigneeId, input.completedAt, input.idempotencyKey] }); const result = await client.execute({ sql: "SELECT * FROM crm_tasks WHERE organization_id=? AND idempotency_key=?", args: [input.organizationId, input.idempotencyKey] }); if (!result.rows[0]) throw new Error("CRM_TASK_CREATE_FAILED"); return task(result.rows[0] as Record<string, unknown>); }
export async function createCrmActivity(input: CrmActivity, client: Client = db): Promise<CrmActivity> { await initializeCrm(client); if (!await getCrmRecord(input.crmId, input.organizationId, client)) throw new Error("CRM_NOT_FOUND"); const allowedTypes: CrmActivity["type"][] = ["CALL_ATTEMPTED", "CALL_COMPLETED", "EMAIL_MANUAL", "MEETING", "FOLLOW_UP", "DOCUMENT_REVIEW", "NOTE"]; if (!allowedTypes.includes(input.type)) throw new Error("CRM_INVALID_ACTIVITY_TYPE"); await client.execute({ sql: "INSERT OR IGNORE INTO crm_activities VALUES (?,?,?,?,?,?,?)", args: [input.id, input.organizationId, input.crmId, input.actorId, input.type, input.notes, input.occurredAt] }); const result = await client.execute({ sql: "SELECT * FROM crm_activities WHERE id=? AND organization_id=?", args: [input.id, input.organizationId] }); if (!result.rows[0]) throw new Error("CRM_ACTIVITY_CREATE_FAILED"); return activity(result.rows[0] as Record<string, unknown>); }
