export type CrmStage = "NEW" | "QUALIFICATION" | "CONTACT_PENDING" | "CONTACTED" | "FOLLOW_UP" | "NEGOTIATION" | "WON" | "LOST" | "ON_HOLD";
export type CrmRecord = { id: string; organizationId: string; operationId: string; opportunityId: string | null; contactIds: string[]; stage: CrmStage; createdAt: string; updatedAt: string; nextActionAt: string | null };
export type CrmTask = { id: string; organizationId: string; crmId: string; title: string; description: string; dueAt: string | null; status: "OPEN" | "DONE"; priority: "LOW" | "MEDIUM" | "HIGH"; assigneeId: string | null; completedAt: string | null; idempotencyKey: string };
export type CrmActivity = { id: string; organizationId: string; crmId: string; actorId: string; type: "CALL_ATTEMPTED" | "CALL_COMPLETED" | "EMAIL_MANUAL" | "MEETING" | "FOLLOW_UP" | "DOCUMENT_REVIEW" | "NOTE"; notes: string; occurredAt: string };
const transitions: Record<CrmStage, readonly CrmStage[]> = { NEW: ["QUALIFICATION", "ON_HOLD", "LOST"], QUALIFICATION: ["CONTACT_PENDING", "ON_HOLD", "LOST"], CONTACT_PENDING: ["CONTACTED", "ON_HOLD", "LOST"], CONTACTED: ["FOLLOW_UP", "NEGOTIATION", "ON_HOLD", "LOST"], FOLLOW_UP: ["CONTACTED", "NEGOTIATION", "ON_HOLD", "LOST"], NEGOTIATION: ["WON", "LOST", "ON_HOLD"], WON: [], LOST: ["NEW"], ON_HOLD: ["NEW", "QUALIFICATION", "CONTACT_PENDING", "CONTACTED", "LOST"] };
export function canTransition(from: CrmStage, to: CrmStage): boolean { return from === to || transitions[from].includes(to); }
export function transitionCrm(record: CrmRecord, to: CrmStage, now = new Date().toISOString()): CrmRecord { if (!canTransition(record.stage, to)) throw new Error(`CRM_INVALID_TRANSITION:${record.stage}:${to}`); return { ...record, stage: to, updatedAt: now }; }
export function isOverdue(task: CrmTask, now = new Date()): boolean { return task.status === "OPEN" && Boolean(task.dueAt) && new Date(task.dueAt as string) < now; }
export function deduplicateTasks(tasks: readonly CrmTask[]): CrmTask[] { const keys = new Set<string>(); return tasks.filter((task) => { if (keys.has(task.organizationId + ":" + task.idempotencyKey)) return false; keys.add(task.organizationId + ":" + task.idempotencyKey); return true; }); }
export function canAccessCrm(record: Pick<CrmRecord, "organizationId">, organizationId: string): boolean { return record.organizationId === organizationId; }
