import { describe, expect, it } from "vitest";
import { canAccessCrm, deduplicateTasks, isOverdue, transitionCrm, type CrmActivity, type CrmRecord, type CrmTask } from "./crm";
import { createClient } from "@libsql/client";
import { applySchemaMigrations } from "./schema-migrations";
async function prepareCrmPersistence(client: ReturnType<typeof createClient>) { await client.execute("CREATE TABLE operations (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL)"); await client.execute({ sql: "INSERT INTO operations(id,organization_id) VALUES(?,?),(?,?)", args: [record.operationId, record.organizationId, "op-b", "org-b"] }); await applySchemaMigrations(client); }
import { changeCrmStage, createCrmActivity, createCrmRecord, createCrmTask, getCrmRecord } from "./crm-service";
const record: CrmRecord = { id: "crm-1", organizationId: "org-a", operationId: "op-1", opportunityId: "opp-1", contactIds: ["c-1"], stage: "NEW", createdAt: "2026-01-01", updatedAt: "2026-01-01", nextActionAt: null };
describe("CRM domain", () => { it("validates lifecycle and preserves independent domains", () => { const next = transitionCrm(record, "QUALIFICATION", "2026-01-02"); expect(next.stage).toBe("QUALIFICATION"); expect(() => transitionCrm(next, "WON")).toThrow("CRM_INVALID_TRANSITION"); }); it("protects tenant scope and task idempotency", () => { expect(canAccessCrm(record, "org-b")).toBe(false); const task: CrmTask = { id: "t-1", organizationId: "org-a", crmId: "crm-1", title: "Follow-up", description: "", dueAt: "2020-01-01", status: "OPEN", priority: "MEDIUM", assigneeId: null, completedAt: null, idempotencyKey: "same" }; expect(deduplicateTasks([task, { ...task, id: "t-2" }])).toHaveLength(1); expect(isOverdue(task, new Date("2020-02-01"))).toBe(true); }); });
describe("CRM persistence isolation", () => { it("rejects cross-tenant task/activity attachment and operation attachment", async () => { const client = createClient({ url: ":memory:" }); await prepareCrmPersistence(client); await createCrmRecord(record, client); await expect(createCrmRecord({ ...record, id: "crm-cross", organizationId: "org-a", operationId: "op-b" }, client)).rejects.toThrow("CRM_OPERATION_TENANT_MISMATCH"); await expect(createCrmRecord({ ...record, id: "crm-cross-org", organizationId: "org-b" }, client)).rejects.toThrow("CRM_OPERATION_TENANT_MISMATCH"); await expect(createCrmTask({ id: "t", organizationId: "org-b", crmId: record.id, title: "x", description: "", dueAt: null, status: "OPEN", priority: "LOW", assigneeId: null, completedAt: null, idempotencyKey: "k" }, client)).rejects.toThrow("CRM_NOT_FOUND"); await expect(createCrmActivity({ id: "a", organizationId: "org-b", crmId: record.id, actorId: "u", type: "NOTE", notes: "x", occurredAt: new Date().toISOString() }, client)).rejects.toThrow("CRM_NOT_FOUND"); expect(await getCrmRecord(record.id, "org-b", client)).toBeNull(); client.close(); }); });
describe("CRM creation idempotency", () => { it("returns the persisted record when the same tenant operation is submitted again", async () => { const client = createClient({ url: ":memory:" }); await prepareCrmPersistence(client); const created = await createCrmRecord(record, client); const repeated = await createCrmRecord({ ...record, id: "crm-duplicate", stage: "QUALIFICATION" }, client); expect(repeated).toEqual(created); expect(await getCrmRecord("crm-duplicate", record.organizationId, client)).toBeNull(); client.close(); }); });
describe("CRM transition safeguards", () => { it("does not treat a note or attempted call as successful contact", async () => { const client = createClient({ url: ":memory:" }); await prepareCrmPersistence(client); await createCrmRecord(record, client); await changeCrmStage(record.id, record.organizationId, "QUALIFICATION", "u", "qualification", client); await changeCrmStage(record.id, record.organizationId, "CONTACT_PENDING", "u", "route", client); const addActivity = (id: string, type: CrmActivity["type"]) => createCrmActivity({ id, organizationId: record.organizationId, crmId: record.id, actorId: "u", type, notes: "test", occurredAt: new Date().toISOString() }, client); await addActivity("note", "NOTE"); await expect(changeCrmStage(record.id, record.organizationId, "CONTACTED", "u", "contact", client)).rejects.toThrow("CRM_CONTACT_ACTIVITY_REQUIRED"); await addActivity("attempt", "CALL_ATTEMPTED"); await expect(changeCrmStage(record.id, record.organizationId, "CONTACTED", "u", "contact", client)).rejects.toThrow("CRM_CONTACT_ACTIVITY_REQUIRED"); await addActivity("complete", "CALL_COMPLETED"); await expect(changeCrmStage(record.id, record.organizationId, "CONTACTED", "u", "contact", client)).resolves.toMatchObject({ stage: "CONTACTED" }); await client.close(); }); });
describe("CRM task idempotency", () => { it("returns the existing task for a repeated idempotency key", async () => { const client = createClient({ url: ":memory:" }); await prepareCrmPersistence(client); await createCrmRecord(record, client); const task: CrmTask = { id: "task-1", organizationId: record.organizationId, crmId: record.id, title: "Follow up", description: "", dueAt: null, status: "OPEN", priority: "MEDIUM", assigneeId: null, completedAt: null, idempotencyKey: "follow-up-key" }; const created = await createCrmTask(task, client); const retried = await createCrmTask({ ...task, id: "task-2", title: "Different payload" }, client); expect(retried).toEqual(created); expect((await client.execute("SELECT COUNT(*) count FROM crm_tasks")).rows[0].count).toBe(1); await client.close(); }); });
