import { createHash } from "node:crypto";
import { createClient, type Client } from "@libsql/client";
import { z } from "zod";

const db=createClient({url:process.env.DATABASE_URL||"file:central-precatorios.db",authToken:process.env.DATABASE_AUTH_TOKEN});
export const documentStatuses=["UPLOADED","QUARANTINED","SCANNING","SAFE","REJECTED","ARCHIVED"] as const;
export const scanStatuses=["NOT_SCANNED","DEMO_SCAN","CLEAN","INFECTED","ERROR"] as const;
export const documentCategories=["IDENTIDADE","CPF_CNPJ","COMPROVANTE_ENDERECO","PRECATORIO","PROCESSO","PROCURACAO","PARECER_JURIDICO","PROPOSTA","CESSAO","OUTRO"] as const;
export type DocumentStatus=(typeof documentStatuses)[number];

export const documentMetadataSchema=z.object({id:z.string().uuid(),operationId:z.string().uuid(),organizationId:z.string(),name:z.string(),hash:z.string().length(64),size:z.number().int().nonnegative(),mime:z.literal("application/pdf"),status:z.enum(documentStatuses),scanStatus:z.enum(scanStatuses),category:z.enum(documentCategories),version:z.number().int().positive(),reviewerNotes:z.string(),retentionUntil:z.string(),createdBy:z.string(),createdAt:z.string(),updatedAt:z.string()});
export type DocumentMetadata=z.infer<typeof documentMetadataSchema>;

export async function initializeDocumentStorage(client:Client=db){
  await client.execute("CREATE TABLE IF NOT EXISTS operation_documents (id TEXT PRIMARY KEY,operation_id TEXT NOT NULL,name TEXT NOT NULL,hash TEXT NOT NULL,content BLOB NOT NULL,created_at TEXT NOT NULL,organization_id TEXT NOT NULL DEFAULT 'legacy-internal')");
  const cols=await client.execute("PRAGMA table_info(operation_documents)"); const add=async(name:string,sql:string)=>{if(!cols.rows.some(r=>r.name===name))try{await client.execute(`ALTER TABLE operation_documents ADD COLUMN ${sql}`)}catch{const current=await client.execute("PRAGMA table_info(operation_documents)");if(!current.rows.some(r=>r.name===name))throw new Error(`Falha ao migrar documento: ${name}`)}};
  await add("size","size INTEGER NOT NULL DEFAULT 0");await add("mime","mime TEXT NOT NULL DEFAULT 'application/pdf'");await add("status","status TEXT NOT NULL DEFAULT 'UPLOADED'");await add("scan_status","scan_status TEXT NOT NULL DEFAULT 'NOT_SCANNED'");await add("category","category TEXT NOT NULL DEFAULT 'OUTRO'");await add("version","version INTEGER NOT NULL DEFAULT 1");await add("reviewer_notes","reviewer_notes TEXT NOT NULL DEFAULT ''");await add("retention_until","retention_until TEXT NOT NULL DEFAULT ''");await add("created_by","created_by TEXT NOT NULL DEFAULT 'legacy'");await add("updated_at","updated_at TEXT NOT NULL DEFAULT ''");
  await client.execute("CREATE INDEX IF NOT EXISTS operation_documents_organization_idx ON operation_documents(organization_id,operation_id,created_at DESC)");
  await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS operation_documents_hash_idx ON operation_documents(organization_id,operation_id,hash)");
}

function metadata(row:Record<string,unknown>):DocumentMetadata{return documentMetadataSchema.parse({id:String(row.id),operationId:String(row.operation_id),organizationId:String(row.organization_id),name:String(row.name),hash:String(row.hash),size:Number(row.size||0),mime:String(row.mime||"application/pdf"),status:String(row.status||"UPLOADED"),scanStatus:String(row.scan_status||"NOT_SCANNED"),category:String(row.category||"OUTRO"),version:Number(row.version||1),reviewerNotes:String(row.reviewer_notes||""),retentionUntil:String(row.retention_until||""),createdBy:String(row.created_by||"legacy"),createdAt:String(row.created_at),updatedAt:String(row.updated_at||row.created_at)});}

export interface StorageAdapter { upload(input:{operationId:string;organizationId:string;name:string;bytes:Uint8Array;createdBy:string}):Promise<DocumentMetadata>;getMetadata(id:string,organizationId:string):Promise<DocumentMetadata|null>;createPrivateAccess(id:string,organizationId:string):Promise<{metadata:DocumentMetadata;bytes:ArrayBuffer}|null>;delete(id:string,organizationId:string):Promise<void>;quarantine(id:string,organizationId:string):Promise<void>;restore(id:string,organizationId:string):Promise<void>;checksum(bytes:Uint8Array):string;moveToPermanentStorage(id:string,organizationId:string):Promise<void>;list(operationId:string,organizationId:string):Promise<DocumentMetadata[]>;updateReview(id:string,organizationId:string,input:{status:DocumentStatus;category:(typeof documentCategories)[number];reviewerNotes:string;retentionUntil:string}):Promise<DocumentMetadata|null>}

export class DatabaseStorageAdapter implements StorageAdapter{
  constructor(private client:Client=db){}
  checksum(bytes:Uint8Array){return createHash("sha256").update(bytes).digest("hex")}
  async upload(input:{operationId:string;organizationId:string;name:string;bytes:Uint8Array;createdBy:string}){await initializeDocumentStorage(this.client);const id=crypto.randomUUID(),hash=this.checksum(input.bytes),now=new Date().toISOString();const scanStatus=process.env.NODE_ENV==="production"?"NOT_SCANNED":"DEMO_SCAN";await this.client.execute({sql:"INSERT INTO operation_documents (id,operation_id,name,hash,content,created_at,organization_id,size,mime,status,scan_status,category,version,reviewer_notes,retention_until,created_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[id,input.operationId,input.name,hash,input.bytes,now,input.organizationId,input.bytes.byteLength,"application/pdf","QUARANTINED",scanStatus,"OUTRO",1,"","",input.createdBy,now]});return (await this.getMetadata(id,input.organizationId))!}
  async getMetadata(id:string,organizationId:string){await initializeDocumentStorage(this.client);const r=await this.client.execute({sql:"SELECT * FROM operation_documents WHERE id=? AND organization_id=?",args:[id,organizationId]});return r.rows[0]?metadata(r.rows[0]):null}
  async createPrivateAccess(id:string,organizationId:string){await initializeDocumentStorage(this.client);const r=await this.client.execute({sql:"SELECT * FROM operation_documents WHERE id=? AND organization_id=?",args:[id,organizationId]});if(!r.rows[0])return null;const m=metadata(r.rows[0]);if(["REJECTED","ARCHIVED"].includes(m.status))return null;const view=new Uint8Array(r.rows[0].content as ArrayBuffer);return{metadata:m,bytes:view.buffer.slice(view.byteOffset,view.byteOffset+view.byteLength) as ArrayBuffer}}
  async list(operationId:string,organizationId:string){await initializeDocumentStorage(this.client);const r=await this.client.execute({sql:"SELECT * FROM operation_documents WHERE operation_id=? AND organization_id=? ORDER BY created_at DESC",args:[operationId,organizationId]});return r.rows.map(metadata)}
  async updateReview(id:string,organizationId:string,input:{status:DocumentStatus;category:(typeof documentCategories)[number];reviewerNotes:string;retentionUntil:string}){await initializeDocumentStorage(this.client);const now=new Date().toISOString();await this.client.execute({sql:"UPDATE operation_documents SET status=?,category=?,reviewer_notes=?,retention_until=?,updated_at=? WHERE id=? AND organization_id=?",args:[input.status,input.category,input.reviewerNotes,input.retentionUntil,now,id,organizationId]});return this.getMetadata(id,organizationId)}
  async quarantine(id:string,organizationId:string){await this.client.execute({sql:"UPDATE operation_documents SET status='QUARANTINED',updated_at=? WHERE id=? AND organization_id=?",args:[new Date().toISOString(),id,organizationId]})}
  async restore(id:string,organizationId:string){await this.client.execute({sql:"UPDATE operation_documents SET status='UPLOADED',updated_at=? WHERE id=? AND organization_id=? AND status='ARCHIVED'",args:[new Date().toISOString(),id,organizationId]})}
  async delete(id:string,organizationId:string){await this.client.execute({sql:"UPDATE operation_documents SET status='ARCHIVED',content=x'',updated_at=? WHERE id=? AND organization_id=?",args:[new Date().toISOString(),id,organizationId]})}
  async moveToPermanentStorage(id:string,organizationId:string){await this.client.execute({sql:"UPDATE operation_documents SET status='SAFE',updated_at=? WHERE id=? AND organization_id=? AND scan_status='CLEAN'",args:[new Date().toISOString(),id,organizationId]})}
}

export const documentStorage:StorageAdapter=new DatabaseStorageAdapter();
