import type { OperationalWorkflow } from "./operational-workflow";

export type AcquisitionProfile={id:string;name:string;version:string;state:string;tribunal:string;minimumPrecatory:number;minimumOfficialEvidence:number;requireDebtor:boolean;officeLabels:[string,string];officeCategories:[string,string];freshDays:number;recentDays:number;weights:{value:number;profile:number;freshness:number;identifiers:number;documents:number;twoOffices:number;noConflict:number}};
export const defaultAcquisitionProfile:AcquisitionProfile={id:"precatorios-sp",name:"Precatórios SP — Padrão",version:"1.0",state:"SP",tribunal:"TJSP",minimumPrecatory:100000,minimumOfficialEvidence:2,requireDebtor:true,officeLabels:["Ofício 1","Ofício 2"],officeCategories:["OFICIO_EMPRESA","OFICIO_EMPRESA"],freshDays:7,recentDays:30,weights:{value:25,profile:20,freshness:15,identifiers:15,documents:10,twoOffices:10,noConflict:5}};
export type Qualification={status:"NOVO"|"EM_QUALIFICACAO"|"QUALIFICADO"|"QUALIFICADO_COM_PENDENCIAS"|"NAO_QUALIFICADO"|"REVISAO_HUMANA"|"RPV_ANALISE_PARTICULAR"|"POSSIVEL_DUPLICADO";score:number;officeCount:number;freshness:"FRESH"|"RECENT"|"STALE"|"UNKNOWN";criteria:{key:string;label:string;ok:boolean;detail:string}[];nextAction:string;reasons:string[]};
export type AcquisitionReadinessState="REJECTED"|"WAITING"|"QUALIFIED_WITH_PENDING"|"READY_FOR_ANALYST";
export type AcquisitionReadinessInput={creditorName:string;amount:number|null;minimumAmount:number;numeroProcessoDEPRE:string;debtor:string;debtorState:string;tribunal:string;targetState:string;targetTribunal:string;officialEvidenceCount:number;requiredOfficialEvidence:number;identityConflict:boolean;contactAvailable?:boolean};
export type AcquisitionReadiness={state:AcquisitionReadinessState;reasons:string[];criteria:{key:string;label:string;mandatory:boolean;ok:boolean;detail:string}[];ready:boolean;nextAction:string};
export function evaluateAcquisitionReadiness(input:AcquisitionReadinessInput):AcquisitionReadiness{
 const hasUsableValue=Number.isFinite(input.amount)&&input.amount!==null&&input.amount>0;
 const valueOk=hasUsableValue&&input.amount!>=input.minimumAmount;
 const debtorMatches=Boolean(input.debtor.trim())&&input.debtorState.toUpperCase()===input.targetState.toUpperCase()&&input.tribunal.toUpperCase().includes(input.targetTribunal.toUpperCase());
 const depreOk=Boolean(input.numeroProcessoDEPRE.trim());
 const creditorOk=Boolean(input.creditorName.trim());
 const evidenceOk=input.officialEvidenceCount>=input.requiredOfficialEvidence;
 const identityOk=!input.identityConflict;
 const criteria=[
  {key:"creditor",label:"Nome do credor",mandatory:true,ok:creditorOk,detail:creditorOk?"Credor identificado com evidência":"Credor não identificado"},
  {key:"value",label:`Valor ≥ ${input.minimumAmount.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}`,mandatory:true,ok:valueOk,detail:input.amount===null||!Number.isFinite(input.amount)?"Valor ausente; revisão necessária":input.amount===0?"Valor zero não é utilizável para qualificação":valueOk?"Valor atende ao mínimo comercial":"Abaixo do mínimo comercial"},
  {key:"depre",label:"Nº Processo DEPRE",mandatory:true,ok:depreOk,detail:depreOk?input.numeroProcessoDEPRE:"Não identificado na fonte consultada"},
  {key:"jurisdiction",label:"Critério São Paulo",mandatory:true,ok:debtorMatches,detail:debtorMatches?`${input.debtor} · ${input.tribunal}`:`Devedora/tribunal fora do perfil ${input.targetState}`},
  {key:"officialEvidence",label:`Ofícios / documentos oficiais: ${input.officialEvidenceCount}/${input.requiredOfficialEvidence}`,mandatory:true,ok:evidenceOk,detail:evidenceOk?"Quantidade mínima de evidências oficiais verificada":"Evidência oficial individualizável insuficiente"},
  {key:"identityConflict",label:"Sem conflito crítico de identidade",mandatory:true,ok:identityOk,detail:identityOk?"Nenhum conflito crítico registrado":"Conflito de identidade requer revisão humana"},
  {key:"contact",label:"Contato localizado",mandatory:false,ok:Boolean(input.contactAvailable),detail:input.contactAvailable?"Contato público localizado; disponibilidade não validada":"Contato não localizado; não bloqueia a elegibilidade"},
 ];
 const reasons=criteria.filter(item=>item.mandatory&&!item.ok).map(item=>item.key==="value"&&input.amount!==null&&input.amount<input.minimumAmount?"BELOW_MINIMUM_VALUE":item.key==="jurisdiction"?"OUTSIDE_SAO_PAULO_PROFILE":item.key==="depre"?"MISSING_DEPRE":item.key==="creditor"?"CREDITOR_NOT_IDENTIFIED":item.key==="officialEvidence"?"OFFICIAL_EVIDENCE_INSUFFICIENT":item.key==="identityConflict"?"IDENTITY_CONFLICT":"VALUE_REQUIRES_REVIEW");
 const rejected=reasons.includes("BELOW_MINIMUM_VALUE")||reasons.includes("OUTSIDE_SAO_PAULO_PROFILE")||input.amount===0;
 const waiting=reasons.includes("MISSING_DEPRE")||reasons.includes("CREDITOR_NOT_IDENTIFIED")||reasons.includes("IDENTITY_CONFLICT")||reasons.includes("VALUE_REQUIRES_REVIEW");
 const state:AcquisitionReadinessState=rejected?"REJECTED":waiting?"WAITING":reasons.length?"QUALIFIED_WITH_PENDING":"READY_FOR_ANALYST";
 const nextAction=state==="READY_FOR_ANALYST"?"REVISAR E ENTRAR EM CONTATO":state==="REJECTED"?reasons[0]:state==="WAITING"?reasons[0]:"Coletar evidência oficial individualizável";
 return{state,reasons,criteria,ready:state==="READY_FOR_ANALYST",nextAction};
}
export function evaluateLead(input:{type:string;amount:number;debtor:string;tribunal:string;process:string;workflow:OperationalWorkflow;checkedAt?:string;conflict?:boolean;duplicate?:boolean},profile:AcquisitionProfile=defaultAcquisitionProfile,now=new Date()):Qualification{
 const credit=input.workflow.credit,offices=credit.qualityOffices.filter(x=>["RECEBIDO","EM_CONFERENCIA","VALIDADO_PARA_TRIAGEM"].includes(x.status)),officeCount=offices.length,days=input.checkedAt?Math.floor((now.getTime()-new Date(input.checkedAt).getTime())/86400000):Infinity,freshness=!Number.isFinite(days)?"UNKNOWN":days<=profile.freshDays?"FRESH":days<=profile.recentDays?"RECENT":"STALE";
 const isRpv=input.type==="RPV",amountOk=isRpv||input.amount>=profile.minimumPrecatory,profileOk=input.tribunal.toUpperCase().includes(profile.tribunal)&&credit.debtorState.toUpperCase()===profile.state&&(!profile.requireDebtor||Boolean(input.debtor.trim())),primaryIdentifier=credit.numeroProcessoDEPRE||credit.precatoryNumber||credit.epesNumber||credit.depreReference||credit.principalRequisitionOfficeNumber,identifierOk=Boolean(primaryIdentifier)&&Boolean(input.process||credit.requisitionProcessNumber||credit.originProcessNumber),documentOk=credit.qualityOffices.filter(x=>x.status!=="PENDENTE"&&x.status!=="NAO_APLICAVEL").length>=1,noConflict=!input.conflict&&!input.duplicate;
 const criteria=[{key:"value",label:"Valor dentro do perfil",ok:amountOk,detail:isRpv?"RPV vai para análise particular; mínimo de precatório não aplicado":amountOk?`Valor igual ou acima de ${profile.minimumPrecatory.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}`:`Abaixo do mínimo comercial de ${profile.minimumPrecatory.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}`},{key:"profile",label:"TJSP e devedor paulista",ok:profileOk,detail:profileOk?`${profile.tribunal} · ${credit.debtorState}`:"Tribunal, estado ou ente devedor precisa de conferência"},{key:"freshness",label:"Fonte recente",ok:freshness==="FRESH"||freshness==="RECENT",detail:freshness==="UNKNOWN"?"Data da consulta não identificada":freshness==="STALE"?"Consulta há mais de 30 dias":`Consulta ${days} dia(s) atrás`},{key:"identifiers",label:"Identificadores",ok:identifierOk,detail:identifierOk?credit.numeroProcessoDEPRE?"Nº Processo DEPRE identificado e processo relacionado":"Há identificador do crédito e processo relacionado":"Falta identificador principal ou processo originário"},{key:"documents",label:"Documentação recebida",ok:documentOk,detail:`${officeCount}/2 ofícios da empresa recebidos ou em conferência`},{key:"twoOffices",label:"Dois ofícios da empresa",ok:officeCount>=2,detail:`${officeCount}/2 recebidos; requisito comercial, não regra jurídica universal`},{key:"noConflict",label:"Sem conflito/duplicidade",ok:noConflict,detail:input.conflict?"Divergência entre fontes para revisão humana":input.duplicate?"Possível duplicidade para conferência":"Nenhuma divergência marcada"}];
 const w=profile.weights,raw=[amountOk?w.value:0,profileOk?w.profile:0,(freshness==="FRESH"?w.freshness:freshness==="RECENT"?Math.round(w.freshness*.6):0),identifierOk?w.identifiers:0,(documentOk?w.documents:0),officeCount>=2?w.twoOffices:0,noConflict?w.noConflict:0].reduce((a,b)=>a+b,0),sum=Object.values(w).reduce((a,b)=>a+b,0),score=sum?Math.round(raw/sum*100):0;
 const criticalReview=input.conflict||credit.qualityOffices.some(x=>x.status==="DIVERGENTE"||x.status==="REVISAO_HUMANA"),all=criteria.every(x=>x.ok),status:Qualification["status"]=isRpv?"RPV_ANALISE_PARTICULAR":input.duplicate?"POSSIVEL_DUPLICADO":criticalReview?"REVISAO_HUMANA":!amountOk||!profileOk?"NAO_QUALIFICADO":all?"QUALIFICADO":"QUALIFICADO_COM_PENDENCIAS";
 const nextAction=isRpv?"Encaminhar para análise particular":input.duplicate?"Conferir possível duplicidade":criticalReview?"Revisar divergência entre fontes":freshness==="STALE"||freshness==="UNKNOWN"?"Atualizar consulta na fonte oficial":officeCount===0?"Solicitar os dois documentos definidos pela empresa":officeCount===1?"Solicitar o documento restante definido pela empresa":!identifierOk?"Conferir identificadores do crédito e do processo":status==="QUALIFICADO"?"Revisar evidências e avaliar conversão para oportunidade":"Conferir aderência ao perfil";
 return{status,score,officeCount,freshness,criteria,nextAction,reasons:criteria.filter(c=>!c.ok).map(c=>c.detail)};
}
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/gi,"").toLowerCase();
export function findLeadDuplicates<T extends {tribunal:string;process:string;debtor:string;workflow:OperationalWorkflow}>(items:T[]){const map=new Map<string,number[]>();items.forEach((item,i)=>{const c=item.workflow.credit;const keys=[c.numeroProcessoDEPRENormalizado&&`d:${norm(item.tribunal)}:${norm(c.numeroProcessoDEPRENormalizado)}`,c.numeroProcessoDEPRE&&!c.numeroProcessoDEPRENormalizado&&`d:${norm(item.tribunal)}:${norm(c.numeroProcessoDEPRE)}`,c.precatoryNumber&&`p:${norm(item.tribunal)}:${norm(c.precatoryNumber)}:${norm(c.precatoryYear)}`,c.epesNumber&&`e:${norm(c.epesNumber)}:${norm(c.epesYear)}`,c.principalRequisitionOfficeNumber&&`r:${norm(c.principalRequisitionOfficeNumber)}`,item.process&&c.precatoryNumber&&`x:${norm(item.process)}:${norm(item.debtor)}:${norm(item.workflow.client.name)}`].filter(Boolean) as string[];for(const key of keys)map.set(key,[...(map.get(key)||[]),i])});const duplicates=new Set<number>();for(const ids of map.values())if(ids.length>1)for(const id of ids)duplicates.add(id);return duplicates;}
