import { createHash } from "node:crypto";
import { createClient, type Client } from "@libsql/client";
import * as pdfjs from "pdfjs-dist/legacy/build/pdf.mjs";
import { getOperation, type Operation } from "@/lib/operations";
import { documentStorage, type StorageAdapter } from "@/lib/document-storage";

const db=createClient({url:process.env.DATABASE_URL||"file:central-precatorios.db",authToken:process.env.DATABASE_AUTH_TOKEN});
type ExtractedField={field:string;value:string;page:number;confidence:number;method:string};
export type PdfAnalysis={id:string;documentId:string;organizationId:string;operationId:string;status:"TEXT_EXTRACTED"|"NO_TEXT"|"FAILED";pages:number;extractedAt:string;fields:ExtractedField[];matchStatus:"MATCH"|"PARTIAL_MATCH"|"CONFLICT"|"INSUFFICIENT_DATA";matchReason:string;autoCategory:string};
async function initialize(client:Client=db){const statements=[`CREATE TABLE IF NOT EXISTS document_analyses(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,operation_id TEXT NOT NULL,document_id TEXT NOT NULL UNIQUE,status TEXT NOT NULL,pages INTEGER NOT NULL,extracted_at TEXT NOT NULL,fields_json TEXT NOT NULL,match_status TEXT NOT NULL,match_reason TEXT NOT NULL,auto_category TEXT NOT NULL)`,"CREATE INDEX IF NOT EXISTS document_analysis_org_idx ON document_analyses(organization_id,operation_id)"];for(let attempt=0;;attempt++){try{await client.batch(statements,"write");return}catch(error){const code=typeof error==="object"&&error!==null&&"code"in error?String(error.code):"";if(code!=="SQLITE_BUSY"||attempt>=4)throw error;await new Promise(resolve=>setTimeout(resolve,25*(attempt+1)))}}}
export async function extractPdfText(bytes:Uint8Array){const task=pdfjs.getDocument({data:new Uint8Array(bytes),useSystemFonts:true,disableFontFace:true});const pdf=await task.promise;const pages:string[]=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push(content.items.map(item=>"str" in item?item.str:"").join(" "))}return{pages,pageCount:pdf.numPages}}
export function detectPdfFields(pages:string[]){const fields:ExtractedField[]=[];const specs:[string,RegExp,number][]=[["processNumber",/\b\d{7}-\d{2}\.\d{4}\.\d\.\d{2}\.\d{4}\b/,95],["precatoryNumber",/\b(?:PRC|PRECAT[ÓO]RIO)\s*(?:N[º°.]?\s*)?[\w./-]{3,40}/i,83],["depreReference",/\bDEPRE\s*(?:N[º°.:]?\s*)?[\w./-]{2,40}/i,86],["officeNumber",/\b(?:OF[IÍ]CIO|REQUISIT[ÓO]RIO)\s*(?:N[º°.]?\s*)?\d{1,8}(?:\/\d{2,4})?/i,78],["date",/\b\d{2}[/-]\d{2}[/-]\d{4}\b/,80],["currency",/R\$\s*[\d.]+(?:,\d{2})?/i,76]];
 pages.forEach((text,index)=>specs.forEach(([field,re,confidence])=>{const match=text.match(re);if(match&&!fields.some(f=>f.field===field))fields.push({field,value:match[0],page:index+1,confidence,method:"pdf-text-regex-v1"})}));return fields}
function category(name:string,text:string){const s=`${name} ${text.slice(0,6000)}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(/oficio|requisitorio/.test(s))return"PRECATORIO";if(/precatorio|depre/.test(s))return"PRECATORIO";if(/procuracao/.test(s))return"PROCURACAO";if(/cpf|cnpj|identidade/.test(s))return"IDENTIDADE";if(/processo|autos/.test(s))return"PROCESSO";return"OUTRO"}
function compare(op:Operation,fields:ExtractedField[]){const get=(name:string)=>fields.find(f=>f.field===name)?.value||"",norm=(s:string)=>s.replace(/\W/g,"").toLowerCase();const extractedProcess=get("processNumber"),knownProcess=op.workflow.credit.requisitionProcessNumber||op.workflow.credit.originProcessNumber||op.process,extractedNumber=get("precatoryNumber"),knownNumber=op.workflow.credit.precatoryNumber;
 if(extractedProcess&&knownProcess&&norm(extractedProcess)!==norm(knownProcess))return{status:"CONFLICT" as const,reason:"O número de processo extraído diverge do processo cadastrado; revisão humana necessária."};if(extractedNumber&&knownNumber&&!norm(extractedNumber).includes(norm(knownNumber))&&!norm(knownNumber).includes(norm(extractedNumber)))return{status:"CONFLICT" as const,reason:"O número de precatório extraído diverge do cadastro; não houve alteração automática."};if((extractedProcess&&knownProcess&&norm(extractedProcess)===norm(knownProcess))||(extractedNumber&&knownNumber&&norm(extractedNumber).includes(norm(knownNumber))))return{status:"MATCH" as const,reason:"Identificador do documento compatível com o cadastro; confirme a evidência original."};if(extractedProcess||extractedNumber||get("depreReference"))return{status:"PARTIAL_MATCH" as const,reason:"Documento contém identificadores, mas falta um identificador correspondente no cadastro."};return{status:"INSUFFICIENT_DATA" as const,reason:"Texto extraído sem identificador suficiente para vinculação automática."}}
export async function analyzePdf(documentId:string,organizationId:string,client:Client=db,storage:StorageAdapter=documentStorage){await initialize(client);const file=await storage.createPrivateAccess(documentId,organizationId);if(!file)return null;const op=await getOperation(file.metadata.operationId,client,organizationId);if(!op)return null;const already=await client.execute({sql:"SELECT * FROM document_analyses WHERE document_id=? AND organization_id=?",args:[documentId,organizationId]});if(already.rows[0])return fromRow(already.rows[0]);const id=crypto.randomUUID(),extractedAt=new Date().toISOString();try{const extracted=await extractPdfText(new Uint8Array(file.bytes)),pageText=extracted.pages,pages=extracted.pageCount,allText=pageText.join(" "),fields=detectPdfFields(pageText),match=compare(op,fields),status=allText.trim()?"TEXT_EXTRACTED":"NO_TEXT",autoCategory=category(file.metadata.name,allText);const result:PdfAnalysis={id,documentId,organizationId,operationId:op.id,status,pages,extractedAt,fields,matchStatus:match.status,matchReason:match.reason,autoCategory};await client.execute({sql:"INSERT INTO document_analyses VALUES(?,?,?,?,?,?,?,?,?,?,?)",args:[id,organizationId,op.id,documentId,status,pages,extractedAt,JSON.stringify(fields),match.status,match.reason,autoCategory]});return result}catch(error){console.error("PDF text extraction failed",error);const failed:PdfAnalysis={id,documentId,organizationId,operationId:op.id,status:"FAILED",pages:0,extractedAt,fields:[],matchStatus:"INSUFFICIENT_DATA",matchReason:"Não foi possível extrair texto deste PDF.",autoCategory:"OUTRO"};await client.execute({sql:"INSERT OR IGNORE INTO document_analyses VALUES(?,?,?,?,?,?,?,?,?,?,?)",args:[id,organizationId,op.id,documentId,failed.status,0,extractedAt,"[]",failed.matchStatus,failed.matchReason,failed.autoCategory]}).catch(()=>{});return failed}}
function fromRow(r:Record<string,unknown>):PdfAnalysis{return{id:String(r.id),documentId:String(r.document_id),organizationId:String(r.organization_id),operationId:String(r.operation_id),status:String(r.status) as PdfAnalysis["status"],pages:Number(r.pages),extractedAt:String(r.extracted_at),fields:JSON.parse(String(r.fields_json)) as ExtractedField[],matchStatus:String(r.match_status) as PdfAnalysis["matchStatus"],matchReason:String(r.match_reason),autoCategory:String(r.auto_category)}}
export async function listPdfAnalyses(operationId:string,organizationId:string,client:Client=db){await initialize(client);const r=await client.execute({sql:"SELECT * FROM document_analyses WHERE operation_id=? AND organization_id=?",args:[operationId,organizationId]});return r.rows.map(fromRow)}
export async function linkMatchedOffice(documentId:string,analysis:PdfAnalysis,organizationId:string){if(analysis.matchStatus!=="MATCH")return false;const office=analysis.fields.find(f=>f.field==="officeNumber"||f.field==="precatoryNumber");if(!office)return false;const doc=await documentStorage.getMetadata(documentId,organizationId);if(!doc)return false;const op=await getOperation(analysis.operationId,undefined,organizationId);if(!op)return false;const normalized=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const named=op.workflow.credit.qualityOffices.filter(x=>normalized(doc.name).includes(normalized(x.label)));if(named.length!==1)return false;const target=named[0];const workflow=structuredClone(op.workflow);workflow.credit.qualityOffices=workflow.credit.qualityOffices.map(x=>x.id===target.id?{...x,status:"RECEBIDO",documentId,receivedAt:new Date().toISOString(),source:`Documento ${doc.name}; identificação explícita no nome do arquivo.`,notes:"Associação automática por nome de arquivo; revisão humana pendente."}:x);const {updateOperation}=await import("@/lib/operations");const saved=await updateOperation({...op,workflow},undefined,organizationId,"pdf-document-matcher");return saved.status==="updated"}
export const pdfHash=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex");
