import { createClient } from "@libsql/client";
import { describe,expect,it } from "vitest";
import { compareSnapshot,extractOfficialLinks,inspectSourceHtml,listSourceSnapshots,officialSources,parseRobots,runOfficialCatalogSync,snapshotHash } from "./source-monitor";
describe("monitor de catálogo público",()=>{
 it("retains only HTTPS links to allowed official hosts",()=>{expect(extractOfficialLinks('<a href="/Precatorios/a">Lista</a><a href="https://evil.example/x">fora</a><a href="http://www.tjsp.jus.br/x">inseguro</a>','https://www.tjsp.jus.br/Precatorios/',["www.tjsp.jus.br"])).toEqual([{label:"Lista",url:"https://www.tjsp.jus.br/Precatorios/a"}])});
 it("classifies first, unchanged, and changed snapshots",()=>{const a={contentHash:snapshotHash("public page A")},b={contentHash:snapshotHash("public page B")};expect(compareSnapshot(null,a)).toBe("FIRST_SEEN");expect(compareSnapshot(a,a)).toBe("UNCHANGED");expect(compareSnapshot(a,b)).toBe("CHANGED")});
 it("follows public robots disallow rules and crawl delay",()=>{const p=parseRobots("User-agent: *\nDisallow: /private\nCrawl-delay: 2");expect(p.allows("/public/list")).toBe(true);expect(p.allows("/private/list")).toBe(false);expect(p.delay).toBe(2)});
 it("stores first snapshots and leaves an unchanged run idempotent",async()=>{const db=createClient({url:"file::memory:"}),fixed=()=>new Date("2026-09-27T12:00:00.000Z"),fetcher=async(input:RequestInfo|URL)=>String(input).endsWith("robots.txt")?new Response("User-agent: *\n",{status:200}):new Response('<html><a href="/Precatorios/Lista">Lista pública</a></html>',{status:200,headers:{"content-type":"text/html"}});try{const first=await runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher,now:fixed,minimumRunIntervalMs:0},db);expect(first.status).toBe("COMPLETED");expect(first.summary.changed).toBe(officialSources.length);const second=await runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher,now:fixed,minimumRunIntervalMs:0},db);expect(second.summary.changed).toBe(0);expect(second.sources.every(s=>s.status==="UNCHANGED")).toBe(true)}finally{db.close()}});
 it("isolates an unavailable source and reports a partial run",async()=>{const db=createClient({url:"file::memory:"}),fetcher=async(input:RequestInfo|URL)=>String(input).endsWith("robots.txt")?new Response("User-agent: *",{status:200}):new Response("<html>página</html>",{status:String(input).includes("/Credores")?503:200,headers:{"content-type":"text/html"}});try{const run=await runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher},db);expect(run.status).toBe("PARTIAL");expect(run.summary.failed).toBe(1);expect(run.summary.leadsDiscovered).toBe(0)}finally{db.close()}});
 it("blocks overlapping runs and keeps run history tenant-scoped",async()=>{const db=createClient({url:"file::memory:"});let release!:()=>void,entered!:()=>void;const waiting=new Promise<void>(r=>release=r),started=new Promise<void>(r=>entered=r);const fetcher=async(input:RequestInfo|URL)=>{if(String(input).endsWith("robots.txt"))return new Response("User-agent: *",{status:200});entered();await waiting;return new Response("<html></html>",{status:200,headers:{"content-type":"text/html"}})};try{const active=runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher},db);await started;await expect(runOfficialCatalogSync({organizationId:"org-a",userId:"user-b",fetcher},db)).rejects.toThrow("Execução já em andamento.");release();const done=await active;expect(done.status).toBe("COMPLETED")}finally{release();db.close()}});
 it("applies a ten-minute per-tenant source polling cooldown",async()=>{const db=createClient({url:"file::memory:"}),fetcher=async(input:RequestInfo|URL)=>String(input).endsWith("robots.txt")?new Response("User-agent: *",{status:200}):new Response("<html></html>",{status:200,headers:{"content-type":"text/html"}});try{await runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher,now:()=>new Date("2026-09-27T12:00:00.000Z")},db);await expect(runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher,now:()=>new Date("2026-09-27T12:01:00.000Z")},db)).rejects.toThrow("SOURCE_SYNC_RATE_LIMITED")}finally{db.close()}});
 it("discovers public form structure without persisting hidden values or mistaking form rows for creditor records",()=>{const html='<form action="/consulta?session=secret" method="post"><select name="entidade"><option value="1">Cidade</option></select><input name="nome"><input type="hidden" name="csrf" value="secret-token"></form><script src="/Captcha/widget.js"></script>';const result=inspectSourceHtml(html,"https://www.tjsp.jus.br/cac/scp/lista.aspx");expect(result.mechanism).toBe("PUBLIC_QUERY_WITH_CAPTCHA");expect(result.entityOptions).toBe(1);expect(result.forms[0].controls).toContain("select:entidade:select");expect(result.forms[0].controls.join(" ")).not.toContain("csrf");expect(result.forms[0].action).not.toContain("secret");expect(result.recordRows).toBe(0)});
 it("checks page health when robots.txt is unverified and preserves independent status",async()=>{const db=createClient({url:"file::memory:"}),fetcher=async(input:RequestInfo|URL)=>String(input).endsWith("robots.txt")?new Response("not published",{status:404}):new Response("<html><form action='/query'><select name='entity'><option>A</option></select></form></html>",{status:200,headers:{"content-type":"text/html"}});try{const run=await runOfficialCatalogSync({organizationId:"org-a",userId:"user-a",fetcher},db);expect(run.sources.every(s=>s.robotsStatus==="UNVERIFIED"&&s.accessStatus==="ACCESSIBLE")).toBe(true);expect(run.summary.accessible).toBe(officialSources.length);const result=await listSourceSnapshots("org-a",db);expect(result[0].diagnostics.entityOptions).toBe(1);expect(result[0].robotsStatus).toBe("UNVERIFIED")}finally{db.close()}});
});
