import { createHash } from "node:crypto";
import { createClient, type Client } from "@libsql/client";
import { createDatabaseClient } from "./database-config";

const db=createDatabaseClient();
export const officialSources=[
 {id:"tjsp-creditors",name:"TJSP · Credores",url:"https://www.tjsp.jus.br/Precatorios/Precatorios/Credores",host:"www.tjsp.jus.br"},
 {id:"tjsp-general",name:"TJSP · Lista Geral",url:"https://www.tjsp.jus.br/Precatorios/Precatorios/ListaGeral",host:"www.tjsp.jus.br"},
 {id:"tjsp-pending",name:"TJSP · Pendentes e disponibilizados",url:"https://www.tjsp.jus.br/Precatorios/Precatorios/ListaPendentes",host:"www.tjsp.jus.br"},
 {id:"tjsp-esaj",name:"TJSP/e-SAJ · Listas de pagamentos",url:"https://esaj.tjsp.jus.br/portalDevedor/abrirConsultaListaPagamentos.do",host:"esaj.tjsp.jus.br"},
 {id:"tjsp-cac-pending",name:"TJSP/CAC · Precatórios pendentes",url:"https://www.tjsp.jus.br/cac/scp/webrelpubliclstpagprecatpendentes.aspx",host:"www.tjsp.jus.br"},
 {id:"tjsp-debtors",name:"TJSP · Entidades devedoras",url:"https://www.tjsp.jus.br/Precatorios/Precatorios/EntidadesDevedoras",host:"www.tjsp.jus.br"},
 {id:"tjsp-notices",name:"TJSP · Comunicados de precatórios",url:"https://www.tjsp.jus.br/Precatorios/Comunicados",host:"www.tjsp.jus.br"},
 {id:"tjsp-depre-notices",name:"TJSP/DEPRE · Comunicados",url:"https://portal.tjsp.jus.br/Depre/Comunicados/Comunicado",host:"portal.tjsp.jus.br"},
] as const;
type FormDiagnostic={action:string;method:string;controls:string[];entityOptions:number;captcha:boolean};
type LinkDiagnostic={url:string;type:string};
type Diagnostic={mechanism:string;forms:FormDiagnostic[];downloads:LinkDiagnostic[];scripts:string[];iframes:string[];recordRows:number;fieldNames:string[];entityOptions?:number;hasCaptcha?:boolean};
export type SourceSnapshot={id:string;sourceId:string;name:string;url:string;status:string;collectedAt:string;httpStatus:number;durationMs:number;contentHash:string;links:{label:string;url:string}[];error:string;changed:boolean;previousCollectedAt:string;robotsStatus:string;accessStatus:string;finalUrl:string;contentType:string;discoveryStatus:string;acquisitionStatus:string;diagnostics:Diagnostic};

function safeLink(raw:string,pageUrl:string){try{const u=new URL(raw,pageUrl);if(u.protocol!=="https:")return null;for(const [key,value] of [...u.searchParams])if(!value||key.length>80||/token|session|captcha|security|state/i.test(key))u.searchParams.delete(key);u.hash="";return u.toString()}catch{return null}}
export function inspectSourceHtml(html:string,pageUrl:string){
 const forms:FormDiagnostic[]=[];const formRx=/<form\b([^>]*)>([\s\S]*?)<\/form\s*>/gi;let f:RegExpExecArray|null;
 while((f=formRx.exec(html))&&forms.length<30){const attrs=f[1],body=f[2],action=safeLink((attrs.match(/action\s*=\s*(["'])(.*?)\1/i)||[])[2]||pageUrl,pageUrl)||pageUrl,method=((attrs.match(/method\s*=\s*(["'])(.*?)\1/i)||[])[2]||"get").toUpperCase(),controls:string[]=[];let c:RegExpExecArray|null;const cr=/<(input|select|textarea|button)\b([^>]*)>/gi;while((c=cr.exec(body))&&controls.length<100){const attrs=c[2],name=(attrs.match(/\bname\s*=\s*(["'])(.*?)\1/i)||[])[2],type=(attrs.match(/\btype\s*=\s*(["'])(.*?)\1/i)||[])[2]||c[1].toLowerCase();if(name&&type.toLowerCase()!=="hidden")controls.push(`${c[1].toLowerCase()}:${name}:${type}`)}forms.push({action,method,controls,entityOptions:(body.match(/<option\b/gi)||[]).length,captcha:/captcha|recaptcha/i.test(body)})}
 const downloads:LinkDiagnostic[]=[];const ar=/<a\b[^>]*href\s*=\s*(["'])(.*?)\1[^>]*>/gi;let a:RegExpExecArray|null;while((a=ar.exec(html))&&downloads.length<100){const u=safeLink(a[2].replace(/&amp;/g,"&"),pageUrl);if(!u)continue;const type=(new URL(u).pathname.match(/\.(pdf|xlsx?|csv|zip|json|xml)$/i)||[])[1]?.toUpperCase();if(type)downloads.push({url:u,type})}
 const scripts=[...html.matchAll(/<script\b[^>]*src\s*=\s*(["'])(.*?)\1/gi)].slice(0,100).map(x=>safeLink(x[2],pageUrl)).filter((x):x is string=>!!x),iframes=[...html.matchAll(/<iframe\b[^>]*src\s*=\s*(["'])(.*?)\1/gi)].slice(0,30).map(x=>safeLink(x[2],pageUrl)).filter((x):x is string=>!!x),hasCaptcha=/captcha|recaptcha/i.test(html),entityOptions=forms.reduce((n,x)=>n+x.entityOptions,0),fieldNames=[...new Set(forms.flatMap(x=>x.controls.map(y=>y.split(":")[1])))].slice(0,100);
 return{mechanism:downloads.length?"PUBLIC_DOWNLOAD":hasCaptcha?"PUBLIC_QUERY_WITH_CAPTCHA":entityOptions?"PUBLIC_ENTITY_QUERY":forms.length?"PUBLIC_HTML_FORM":/<table\b/i.test(html)?"HTML_TABLE":"STATIC_PAGE",forms,downloads,scripts,iframes,recordRows:0,fieldNames,entityOptions,hasCaptcha};
}
export function extractOfficialLinks(html:string,pageUrl:string,allowedHosts:readonly string[]){const links:{label:string;url:string}[]=[];const rx=/<a\b[^>]*href\s*=\s*(["'])(.*?)\1[^>]*>([\s\S]*?)<\/a\s*>/gi;let m:RegExpExecArray|null;while((m=rx.exec(html))&&links.length<400){const url=safeLink(m[2].replace(/&amp;/g,"&"),pageUrl);if(!url||!allowedHosts.includes(new URL(url).hostname))continue;const label=m[3].replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim().slice(0,180);if(label)links.push({label,url})}return[...new Map(links.map(x=>[x.url,x])).values()]}
export function snapshotHash(html:string){return createHash("sha256").update(html).digest("hex")}
export function compareSnapshot(previous:Pick<SourceSnapshot,"contentHash">|null,current:Pick<SourceSnapshot,"contentHash">){return !previous?"FIRST_SEEN":previous.contentHash===current.contentHash?"UNCHANGED":"CHANGED"}
export function parseRobots(text:string){const rules:{agent:string;disallow:string;delay:number}[]=[],lines=text.split(/\r?\n/);let active:string[]=[];for(const raw of lines){const line=raw.split("#")[0].trim();if(!line)continue;const i=line.indexOf(":");if(i<0)continue;const key=line.slice(0,i).trim().toLowerCase(),value=line.slice(i+1).trim();if(key==="user-agent"){active=[value.toLowerCase()];continue}if(active.length&&(key==="disallow"||key==="crawl-delay")){const delay=key==="crawl-delay"?Number(value):0;rules.push({agent:active[0],disallow:key==="disallow"?value:"",delay:Number.isFinite(delay)?delay:0})}}const general=rules.filter(x=>x.agent==="*"),delay=Math.max(0,...general.map(x=>x.delay));return{delay,allows:(path:string)=>!general.some(x=>x.disallow&&path.startsWith(x.disallow))}}

export async function initializeSourceMonitor(client:Client=db){
 await client.execute(`CREATE TABLE IF NOT EXISTS capture_source_runs(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT NOT NULL,status TEXT NOT NULL,actor_user_id TEXT NOT NULL,summary_json TEXT NOT NULL)`);
 await client.execute("CREATE INDEX IF NOT EXISTS capture_source_runs_org_idx ON capture_source_runs(organization_id,started_at DESC)");
 await client.execute(`CREATE TABLE IF NOT EXISTS capture_source_snapshots(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,run_id TEXT NOT NULL,source_id TEXT NOT NULL,name TEXT NOT NULL,source_url TEXT NOT NULL,collected_at TEXT NOT NULL,http_status INTEGER NOT NULL,duration_ms INTEGER NOT NULL,status TEXT NOT NULL,content_hash TEXT NOT NULL,links_json TEXT NOT NULL,error TEXT NOT NULL)`);
 const columns=await client.execute("PRAGMA table_info(capture_source_snapshots)");if(!columns.rows.some(r=>String(r.name)==="diagnostic_json"))await client.execute("ALTER TABLE capture_source_snapshots ADD COLUMN diagnostic_json TEXT NOT NULL DEFAULT '{}'");
 await client.execute("CREATE INDEX IF NOT EXISTS capture_source_snapshots_idx ON capture_source_snapshots(organization_id,source_id,collected_at DESC)");await client.execute("CREATE UNIQUE INDEX IF NOT EXISTS capture_source_running_unique ON capture_source_runs(organization_id) WHERE status='RUNNING'");
}
function rowSnapshot(r:Record<string,unknown>):SourceSnapshot{const d=JSON.parse(String(r.diagnostic_json||"{}")) as Record<string,unknown>,details=(d.details||{}) as Diagnostic;return{id:String(r.id),sourceId:String(r.source_id),name:String(r.name),url:String(r.source_url),status:String(r.status),collectedAt:String(r.collected_at),httpStatus:Number(r.http_status),durationMs:Number(r.duration_ms),contentHash:String(r.content_hash),links:JSON.parse(String(r.links_json)) as SourceSnapshot["links"],error:String(r.error),changed:["CHANGED","FIRST_SEEN"].includes(String(r.status)),previousCollectedAt:"",robotsStatus:String(d.robotsStatus||"UNKNOWN"),accessStatus:String(d.accessStatus||"UNKNOWN"),finalUrl:String(d.finalUrl||r.source_url),contentType:String(d.contentType||""),discoveryStatus:String(d.discoveryStatus||"UNKNOWN"),acquisitionStatus:String(d.acquisitionStatus||"UNKNOWN"),diagnostics:details||{mechanism:"UNKNOWN",forms:[],downloads:[],scripts:[],iframes:[],recordRows:0,fieldNames:[]}}}
export async function listSourceSnapshots(organizationId:string,client:Client=db){await initializeSourceMonitor(client);const r=await client.execute({sql:"SELECT * FROM capture_source_snapshots WHERE organization_id=? ORDER BY collected_at DESC,rowid DESC LIMIT 1000",args:[organizationId]});return r.rows.map(rowSnapshot)}
export async function listSourceRuns(organizationId:string,client:Client=db){await initializeSourceMonitor(client);const r=await client.execute({sql:"SELECT * FROM capture_source_runs WHERE organization_id=? ORDER BY started_at DESC LIMIT 50",args:[organizationId]});return r.rows.map(x=>({id:String(x.id),startedAt:String(x.started_at),finishedAt:String(x.finished_at),status:String(x.status),actorUserId:String(x.actor_user_id),summary:JSON.parse(String(x.summary_json)) as Record<string,number>}))}

export async function runOfficialCatalogSync(input:{organizationId:string;userId:string;fetcher?:typeof fetch;now?:()=>Date;minimumRunIntervalMs?:number;onStarted?:(runId:string,startedAt:string)=>Promise<unknown>},client:Client=db){
 await initializeSourceMonitor(client);const id=crypto.randomUUID(),started=(input.now?.()||new Date()).toISOString(),staleBefore=new Date(Date.parse(started)-600_000).toISOString();await client.execute({sql:"UPDATE capture_source_runs SET finished_at=?,status='FAILED',summary_json=? WHERE organization_id=? AND status='RUNNING' AND started_at<?",args:[started,JSON.stringify({reason:"Execução encerrada por tempo excedido."}),input.organizationId,staleBefore]});
 const recent=await client.execute({sql:"SELECT started_at,status FROM capture_source_runs WHERE organization_id=? ORDER BY started_at DESC LIMIT 1",args:[input.organizationId]});
 const interval=input.minimumRunIntervalMs??600_000;
 if(interval>0&&recent.rows[0]&&String(recent.rows[0].status)!=="RUNNING"&&Date.parse(started)-Date.parse(String(recent.rows[0].started_at))<interval)throw new Error("SOURCE_SYNC_RATE_LIMITED");
 try{await client.execute({sql:"INSERT INTO capture_source_runs VALUES(?,?,?,?,?,?,?)",args:[id,input.organizationId,started,"","RUNNING",input.userId,JSON.stringify({sources:0,changed:0,failed:0,leadsDiscovered:0})]})}catch(error){if(error instanceof Error&&/unique|constraint/i.test(error.message))throw new Error("Execução já em andamento.");throw error}
 await input.onStarted?.(id,started).catch(error=>console.error(JSON.stringify({event:"SOURCE_RUN_AUDIT_FAILED",runId:id,organizationId:input.organizationId,reason:error instanceof Error?error.message:"audit failure"})));
 const fetcher=input.fetcher||fetch,results:SourceSnapshot[]=[],robots=new Map<string,ReturnType<typeof parseRobots>>(),headers={accept:"text/html, application/pdf;q=0.8, text/plain;q=0.9,*/*;q=0.2","user-agent":"CP-SourceMonitor/2.3 (public-source monitor; conservative request rate)"};let failures=0,changed=0;
 for(const source of officialSources){const began=Date.now(),snapshotId=crypto.randomUUID();let status="FAILED",httpStatus=0,contentHash="",links:SourceSnapshot["links"]=[],errorMessage="",robotsStatus="UNVERIFIED",accessStatus="NOT_CHECKED",finalUrl:string=source.url,contentType="",discoveryStatus="UNKNOWN",acquisitionStatus="NOT_IMPLEMENTED",details:Diagnostic={mechanism:"UNKNOWN",forms:[],downloads:[],scripts:[],iframes:[],recordRows:0,fieldNames:[]};
  try{let policy=robots.get(source.host);if(policy)robotsStatus="VERIFIED";else{try{const rr=await fetcher(`https://${source.host}/robots.txt`,{headers,redirect:"follow",signal:AbortSignal.timeout(8_000),cache:"no-store"});if(rr.ok){policy=parseRobots(await rr.text());robotsStatus="VERIFIED";robots.set(source.host,policy)}else robotsStatus="UNVERIFIED"}catch{robotsStatus="UNVERIFIED"}}
   if(policy&&!policy.allows(new URL(source.url).pathname)){robotsStatus="DISALLOWS";accessStatus="NOT_CHECKED_ROBOTS_DISALLOW";throw new Error("robots.txt desautoriza esta página; nenhuma consulta foi realizada.")}
   if(policy?.delay)await new Promise(resolve=>setTimeout(resolve,Math.min(policy.delay*1000,5_000)));
   const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12_000);let response:Response;try{response=await fetcher(source.url,{headers,redirect:"follow",signal:controller.signal,cache:"no-store"})}finally{clearTimeout(timer)}httpStatus=response.status;finalUrl=response.url||source.url;contentType=response.headers.get("content-type")||"";
   if(response.url&&!/(^|\.)tjsp\.jus\.br$/i.test(new URL(response.url).hostname)){accessStatus="REDIRECT_REQUIRES_REVIEW";throw new Error("O redirecionamento saiu dos domínios oficiais TJSP; destino não consultado.")}
   if(!response.ok){accessStatus="INACCESSIBLE";throw new Error(`A página respondeu HTTP ${response.status}.`)}accessStatus="ACCESSIBLE";const body=await response.text();if(body.length>12_000_000)throw new Error("Resposta excede o limite de leitura de 12 MB.");contentHash=snapshotHash(body);
   if(/html/i.test(contentType)&&/<html\b/i.test(body.slice(0,100_000))){details=inspectSourceHtml(body,finalUrl);links=extractOfficialLinks(body,finalUrl,["www.tjsp.jus.br","esaj.tjsp.jus.br","portal.tjsp.jus.br"]);discoveryStatus=details.mechanism==="STATIC_PAGE"?"NOT_DISCOVERED":"FOUND";if(details.hasCaptcha)acquisitionStatus="CAPTACAO_ASSISTIDA";else if((details.entityOptions||0)>0)acquisitionStatus="QUERY_ADAPTER_NOT_IMPLEMENTED";else acquisitionStatus="NOT_IMPLEMENTED"}else if(/pdf|excel|spreadsheet|csv|zip|json|xml/i.test(contentType)){details.mechanism="DIRECT_RESOURCE";discoveryStatus="FOUND";acquisitionStatus="PARSER_NOT_IMPLEMENTED"}else discoveryStatus="NOT_DISCOVERED";
   const prev=await client.execute({sql:"SELECT content_hash FROM capture_source_snapshots WHERE organization_id=? AND source_id=? ORDER BY collected_at DESC,rowid DESC LIMIT 1",args:[input.organizationId,source.id]});status=compareSnapshot(prev.rows[0]?{contentHash:String(prev.rows[0].content_hash)}:null,{contentHash});if(status!=="UNCHANGED")changed++
  }catch(error){if(status==="FAILED")failures++;if(accessStatus==="NOT_CHECKED")accessStatus="INACCESSIBLE";errorMessage=error instanceof Error?error.message:"Falha desconhecida na leitura pública.";if(accessStatus==="NOT_CHECKED_ROBOTS_DISALLOW")status="ROBOTS_DISALLOWS"}
  const collectedAt=(input.now?.()||new Date()).toISOString(),durationMs=Date.now()-began,diagnostic={robotsStatus,accessStatus,finalUrl,contentType,discoveryStatus,acquisitionStatus,details};const snapshot:SourceSnapshot={id:snapshotId,sourceId:source.id,name:source.name,url:source.url,status,collectedAt,httpStatus,durationMs,contentHash,links,error:errorMessage,changed:["CHANGED","FIRST_SEEN"].includes(status),previousCollectedAt:"",robotsStatus,accessStatus,finalUrl,contentType,discoveryStatus,acquisitionStatus,diagnostics:details};
  await client.execute({sql:"INSERT INTO capture_source_snapshots(id,organization_id,run_id,source_id,name,source_url,collected_at,http_status,duration_ms,status,content_hash,links_json,error,diagnostic_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",args:[snapshotId,input.organizationId,id,source.id,source.name,source.url,collectedAt,httpStatus,durationMs,status,contentHash,JSON.stringify(links),errorMessage,JSON.stringify(diagnostic)]});results.push(snapshot);console.info(JSON.stringify({event:"SOURCE_DIAGNOSTIC_COMPLETED",runId:id,sourceId:source.id,organizationId:input.organizationId,pageHealth:status,robotsStatus,accessStatus,discoveryStatus,acquisitionStatus,httpStatus,durationMs,linkCount:links.length}));
 }
 const summary={sources:results.length,changed,failed:failures,leadsDiscovered:0,accessible:results.filter(x=>x.accessStatus==="ACCESSIBLE").length,robotsUnverified:results.filter(x=>x.robotsStatus==="UNVERIFIED").length,acquisitionImplemented:results.filter(x=>x.acquisitionStatus==="WORKING").length};const runStatus=failures===0?"COMPLETED":failures===results.length?"FAILED":"PARTIAL";const finished=(input.now?.()||new Date()).toISOString();await client.execute({sql:"UPDATE capture_source_runs SET finished_at=?,status=?,summary_json=? WHERE id=? AND organization_id=?",args:[finished,runStatus,JSON.stringify(summary),id,input.organizationId]});return{id,startedAt:started,finishedAt:finished,status:runStatus,summary,sources:results};
}
