import Papa from "papaparse";

export type TjspLeadRow={creditNumber:string;processNumber:string;numeroProcessoDEPRE?:string;numeroAutos?:string;epesNumber?:string;epesYear?:string;originProcessNumber?:string;protocolDate?:string;paymentOrder?:string;creditor:string;debtor:string;municipality:string;amount:number|null;valueDate:string;precatoryYear?:string;type:"PRECATORY"|"RPV";court:string;sourceUrl:string;sourcePage?:number;sourceRecord?:number};
const normalize=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const aliases:Record<string,string[]>={creditNumber:["numero do precatorio","numero precatorio","precatorio","numero requisitorio","requisitorio","prc","opv"],numeroProcessoDEPRE:["n processo depre","numero processo depre","processo depre"],numeroAutos:["numero de autos","n de autos"],epesNumber:["ep es","es ep","epes"],epesYear:["ano ep es","ano es ep","ano epes"],originProcessNumber:["processo originario","autos originarios"],processNumber:["numero do processo","numero processo","numero cnj","processo cnj","processo requisitorio"],creditor:["credor","beneficiario","nome do credor","nome beneficiario","titular"],debtor:["entidade devedora","devedor","ente devedor","entidade","municipio","prefeitura"],municipality:["municipio","comarca","cidade"],amount:["valor atualizado","valor do credito","valor atualizado do credito","valor requisitado","valor total","valor nominal","valor"],valueDate:["data base","data de atualizacao","data atualizacao","atualizado em","referencia"],protocolDate:["data do protocolo","data protocolo"],paymentOrder:["ordem de pagamento","ordem pagamento"],precatoryYear:["ano do precatorio","ano precatorio","ano requisitorio","ano"],type:["tipo","classe","modalidade","natureza"],court:["tribunal","orgao julgador","vara"],sourcePage:["pagina da fonte","pagina"],sourceRecord:["registro na pagina","registro"]};
export type DatasetFieldProfile={name:string;type:"EMPTY"|"NUMBER"|"DATE"|"BOOLEAN"|"TEXT"|"MIXED";nullRate:number;uniqueRate:number;malformed:number;samples:string[];candidateField:keyof typeof aliases|null};
export type DatasetProfile={recordCount:number;duplicateRows:number;fields:DatasetFieldProfile[];candidateIdentityFields:string[]};
function profileValueType(value:string):"NUMBER"|"DATE"|"BOOLEAN"|"TEXT"{const text=value.trim();if(/^(?:R\$\s*)?-?(?:\d{1,3}(?:\.\d{3})+|\d+)(?:,\d+)?$/.test(text)||/^-?\d+\.\d+$/.test(text))return"NUMBER";if(/^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$|^\d{4}-\d{2}-\d{2}$/.test(text))return"DATE";if(/^(true|false|sim|nao|não|s|n)$/i.test(text))return"BOOLEAN";return"TEXT"}
function canonicalField(header:string){const normalized=normalize(header);return(Object.keys(aliases) as (keyof typeof aliases)[]).find(field=>aliases[field].some(alias=>{const candidate=normalize(alias);return normalized===candidate||normalized.startsWith(`${candidate} `)||candidate.startsWith(`${normalized} `)}))||null}
export function profileTjspDataset(rows:string[][]):DatasetProfile{const headers=rows[0]||[],records=rows.slice(1).filter(row=>row.some(value=>String(value??"").trim())),duplicateKeys=new Set<string>(),duplicateRows=records.reduce((count,row)=>{const key=row.map(value=>normalize(String(value??""))).join("|");if(duplicateKeys.has(key))return count+1;duplicateKeys.add(key);return count},0),fields=headers.map((name,index)=>{const values=records.map(row=>String(row[index]??"").trim()),present=values.filter(Boolean),types=present.map(profileValueType),frequencies=new Map<string,number>();for(const type of types)frequencies.set(type,(frequencies.get(type)||0)+1);const dominant=[...frequencies].toSorted((a,b)=>b[1]-a[1])[0]?.[0] as DatasetFieldProfile["type"]|undefined,distinct=new Set(present.map(value=>normalize(value)));return{name:String(name||`Coluna ${index+1}`),type:present.length===0?"EMPTY":new Set(types).size>1?"MIXED":dominant||"EMPTY",nullRate:records.length?Number(((records.length-present.length)/records.length).toFixed(4)):0,uniqueRate:present.length?Number((distinct.size/present.length).toFixed(4)):0,malformed:dominant?types.filter(type=>type!==dominant).length:0,samples:[...new Set(present.map(value=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").toUpperCase()))].slice(0,3),candidateField:canonicalField(String(name))}});return{recordCount:records.length,duplicateRows,fields,candidateIdentityFields:fields.filter(field=>["creditNumber","numeroProcessoDEPRE","epesNumber","processNumber","originProcessNumber"].includes(String(field.candidateField))).map(field=>field.name)}}
export function parseAmount(v:unknown):number|null{if(typeof v==="number"&&Number.isFinite(v))return v;const s=String(v??"").trim().replace(/R\$/gi,"").replace(/\s/g,"");if(!s)return null;const normalized=s.includes(",")?s.replace(/\./g,"").replace(",","."):s;const n=Number(normalized.replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:null}
export function normalizeProcessIdentifier(value:string){return value.replace(/\D/g,"")}
function value(row:Record<string,unknown>,field:keyof typeof aliases){const headers=Object.keys(row),exact=headers.find(key=>aliases[field].some(alias=>normalize(key)===normalize(alias)));if(exact)return row[exact];const partial=headers.find(key=>aliases[field].some(a=>{const header=normalize(key),alias=normalize(a);return header.startsWith(`${alias} `)||alias.startsWith(`${header} `)}));return partial?row[partial]:undefined}
export function parseTjspCsv(text:string,sourceUrl="https://www.tjsp.jus.br/Precatorios/Precatorios/ListaGeral"):{rows:TjspLeadRow[];errors:string[]}{
 const delimiter=text.split(/\r?\n/,1)[0].includes(";")?";":text.split(/\r?\n/,1)[0].includes("\t")?"\t":",";
 const parsed=Papa.parse<Record<string,unknown>>(text,{header:true,skipEmptyLines:"greedy",delimiter,transformHeader:(h:string)=>h.replace(/^\uFEFF/,"").trim()});const errors=parsed.errors.map(e=>`Linha ${(e.row??0)+2}: ${e.message}`);const rows:TjspLeadRow[]=[];
 for(const [i,row] of parsed.data.entries()){
  const creditNumber=String(value(row,"creditNumber")??"").trim(),creditor=String(value(row,"creditor")??"").trim();
  const processNumber=String(value(row,"processNumber")??"").trim(),numeroProcessoDEPRE=String(value(row,"numeroProcessoDEPRE")??"").trim(),numeroAutos=String(value(row,"numeroAutos")??"").trim(),originProcessNumber=String(value(row,"originProcessNumber")??"").trim(),debtor=String(value(row,"debtor")??"").trim(),municipality=String(value(row,"municipality")??"").trim()||debtor.replace(/^(prefeitura municipal de|municipio de)\s*/i,"");
  if(!creditNumber&&!processNumber&&!numeroProcessoDEPRE&&!numeroAutos&&!originProcessNumber){if(Object.values(row).some(Boolean))errors.push(`Linha ${i+2}: faltam número de precatório, processo ou Nº Processo DEPRE.`);continue}
  const typeText=normalize(value(row,"type")??creditNumber),type=/\brpv\b|pequeno valor|opv/.test(typeText)?"RPV":"PRECATORY";
    const epesRaw=String(value(row,"epesNumber")??"").trim(),epesParts=epesRaw.match(/^(\d+)\s*[/.-]\s*(\d{4})$/);
    rows.push({creditNumber,processNumber,numeroProcessoDEPRE,numeroAutos,epesNumber:epesParts?.[1]||epesRaw,epesYear:epesParts?.[2]||String(value(row,"epesYear")??"").trim(),originProcessNumber,protocolDate:String(value(row,"protocolDate")??"").trim(),paymentOrder:String(value(row,"paymentOrder")??"").trim(),creditor,debtor,municipality,amount:parseAmount(value(row,"amount")),valueDate:String(value(row,"valueDate")??"").trim(),precatoryYear:String(value(row,"precatoryYear")??"").trim().match(/20\d{2}/)?.[0]||"",type,court:String(value(row,"court")??"TJSP"),sourceUrl,sourcePage:Number(value(row,"sourcePage"))||undefined,sourceRecord:Number(value(row,"sourceRecord"))||undefined});
 }
 return {rows,errors};
}
