import Papa from "papaparse";
import { Unzip, UnzipInflate, UnzipPassThrough } from "fflate";
import * as pdfjs from "pdfjs-dist/legacy/build/pdf.mjs";
import { extractCacReportHeader, TjspCacRecordParser, type CacHeaderEvidence, type CacTextItem, type TjspCacRecord } from "./tjsp-cac-record-parser";
export { extractCacReportHeader, TjspCacRecordParser } from "./tjsp-cac-record-parser";
export type { CacFieldEvidence, CacHeaderEvidence, CacParserStats, CacRejectedCandidate, CacRejectionReason, CacTextItem, TjspCacRecord } from "./tjsp-cac-record-parser";

const MAX_FILE_BYTES=20*1024*1024;
const MAX_ARCHIVE_ENTRIES=32;
const headers=["Ordem de Pagamento","Número do precatório","Nº Processo DEPRE","Nº de autos","EP/ES","Credor","Entidade devedora","Município","Valor atualizado","Tipo","Tribunal","Natureza","Data do protocolo","Protocolo","Protocolo geral","Ordem orçamentária","Superpreferência","Processo originário","Autos antigos","Página da fonte","Registro na página","Arquivo interno","Nome do arquivo original","SHA-256 do arquivo original","ID da sessão de captura","Modo de captura"];
type PdfItem={str:string;transform:number[]};
export function parseTjspCacPage(items:readonly CacTextItem[],page:number,archiveEntry=""):TjspCacRecord[]{const parser=new TjspCacRecordParser({archiveEntry});parser.pushPage(page,items);return parser.finish().records}
export function parseTjspCacPages(pages:readonly {page:number;items:readonly CacTextItem[]}[],options:{archiveEntry?:string;documentId?:string;reportHeaderDebtor?:CacHeaderEvidence|null}={}){const parser=new TjspCacRecordParser(options);for(const page of pages)parser.pushPage(page.page,page.items);return parser.finish()}
export function cacRecordsToCsv(records:readonly TjspCacRecord[],metadata:{sourceFileName?:string;sourceFileChecksum?:string;captureSessionId?:string;captureMode?:string}={}){const rows=[headers,...records.map(record=>[record.paymentOrder,record.creditNumber,record.numeroProcessoDEPRE,record.numeroAutos,record.epesNumber?`${record.epesNumber}${record.epesYear?`/${record.epesYear}`:""}`:"",record.creditor,record.debtor,record.municipality,record.amount===null?"":String(record.amount),record.type,"TJSP",record.nature,record.protocolDate,record.protocol,record.generalProtocol,record.budgetOrder,record.superPriority,record.originProcessNumber,record.legacyProcess,String(record.page),String(record.record),record.archiveEntry,metadata.sourceFileName||"",metadata.sourceFileChecksum||"",metadata.captureSessionId||"",metadata.captureMode||"ASSISTED"])];return Papa.unparse(rows,{delimiter:";"})}
function safeEntryName(name:string){return name.replace(/\\/g,"/").split("/").pop()?.replace(/[\r\n]/g,"_").slice(0,160)||"relatorio.pdf"}
function extractPdfFromZip(bytes:Uint8Array){let entryCount=0,pdfCount=0,total=0,pdfBytes:Uint8Array|undefined,entryName="",problem="";const unzip=new Unzip(file=>{entryCount++;if(entryCount>MAX_ARCHIVE_ENTRIES){problem="O ZIP contém entradas demais.";return}if(!/\.pdf$/i.test(file.name))return;pdfCount++;if(pdfCount>1){problem="O ZIP deve conter somente um PDF de relatório.";file.terminate();return}if(file.originalSize!==undefined&&file.originalSize>MAX_FILE_BYTES){problem="O PDF extraído excede 20 MB.";file.terminate();return}entryName=safeEntryName(file.name);const chunks:Uint8Array[]=[];file.ondata=(error,chunk,final)=>{if(error){problem="Não foi possível extrair o PDF do ZIP.";return}total+=chunk.length;if(total>MAX_FILE_BYTES){problem="O PDF extraído excede 20 MB.";file.terminate();return}chunks.push(chunk);if(final){pdfBytes=new Uint8Array(total);let offset=0;for(const part of chunks){pdfBytes.set(part,offset);offset+=part.length}}};try{file.start()}catch{problem="O método de compactação do PDF não é suportado."}});unzip.register(UnzipInflate);unzip.register(UnzipPassThrough);try{unzip.push(bytes,true)}catch{problem=problem||"O arquivo ZIP é inválido ou está corrompido."}if(problem)throw new Error(problem);if(pdfCount!==1||!pdfBytes)throw new Error("O ZIP precisa conter exatamente um PDF de relatório.");return{bytes:pdfBytes,entryName}}
export async function readTjspCacReport(fileBytes:Uint8Array,fileName:string,options:{documentId?:string}={}){if(fileBytes.byteLength>MAX_FILE_BYTES)throw new Error("O arquivo excede 20 MB.");const extension=fileName.split(".").pop()?.toLowerCase();let pdfBytes=fileBytes,archiveEntry=safeEntryName(fileName);if(extension==="zip"){const extracted=extractPdfFromZip(fileBytes);pdfBytes=extracted.bytes;archiveEntry=extracted.entryName}else if(extension!=="pdf")throw new Error("Use PDF ou ZIP contendo um único PDF oficial do CAC.");if(String.fromCharCode(...pdfBytes.subarray(0,5))!=="%PDF-")throw new Error("A extensão não corresponde a um PDF válido.");const task=pdfjs.getDocument({data:new Uint8Array(pdfBytes),useSystemFonts:true,disableFontFace:true}),pdf=await task.promise;let parser:TjspCacRecordParser|null=null,headerText="";for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const page=await pdf.getPage(pageNumber),content=await page.getTextContent(),items=content.items.filter((item):item is typeof item&PdfItem=>"str"in item).map(item=>({text:item.str,x:Math.round(item.transform[4]),y:Math.round(item.transform[5])}));if(pageNumber===1){headerText=items.map(item=>item.text).join(" ");parser=new TjspCacRecordParser({archiveEntry,documentId:options.documentId,reportHeaderDebtor:extractCacReportHeader(items)})}parser!.pushPage(pageNumber,items)}if(!/pendentes/i.test(headerText)||!parser)throw new Error("O PDF não corresponde à estrutura reconhecida da lista CAC de precatórios pendentes.");const parsed=parser.finish();return{archiveEntry,pdfPages:pdf.numPages,records:parsed.records,rejectedCandidates:parsed.rejected,parserStats:parsed.stats,csv:cacRecordsToCsv(parsed.records)}}
