import { z } from "zod";
import { appendAudit } from "@/lib/audit";
import { documentCategories, documentStatuses, documentStorage } from "@/lib/document-storage";
import { requireTenantPermission } from "@/lib/tenant";
import { getOperation } from "@/lib/operations";
export const runtime="nodejs"; const MAX=5*1024*1024;
const reviewSchema=z.object({id:z.string().uuid(),status:z.enum(documentStatuses),category:z.enum(documentCategories),reviewerNotes:z.string().trim().max(3000),retentionUntil:z.union([z.literal(""),z.iso.date()])}).strict();
function requestId(request:Request){return request.headers.get("x-request-id")||crypto.randomUUID()}
function sameOrigin(request:Request){const origin=request.headers.get("origin");return Boolean(origin)&&origin===new URL(request.url).origin}
export async function GET(request:Request){try{const tenant=await requireTenantPermission(request.headers,"document:read");const url=new URL(request.url),id=url.searchParams.get("id"),operationId=url.searchParams.get("operation");
 if(id){if(!z.string().uuid().safeParse(id).success)return Response.json({code:"BAD_REQUEST",error:"Documento inválido."},{status:400});const access=await documentStorage.createPrivateAccess(id,tenant.organizationId);if(!access)return Response.json({code:"NOT_FOUND",error:"Documento indisponível ou sem autorização."},{status:404});await appendAudit({organizationId:tenant.organizationId,actorUserId:tenant.userId,action:"DOCUMENT_DOWNLOADED",entityType:"document",entityId:id,previousStateSummary:{},nextStateSummary:{status:access.metadata.status},metadata:{operationId:access.metadata.operationId},requestId:requestId(request),source:"DOCUMENT_API"});return new Response(access.bytes,{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(access.metadata.name)}`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}})}
 if(!operationId||!z.string().uuid().safeParse(operationId).success)return Response.json({code:"BAD_REQUEST",error:"Operação inválida."},{status:400});if(!await getOperation(operationId,undefined,tenant.organizationId))return Response.json({code:"NOT_FOUND",error:"Operação não encontrada."},{status:404});return Response.json({documents:await documentStorage.list(operationId,tenant.organizationId)},{headers:{"cache-control":"no-store"}})
 }catch(error){if(error instanceof Response)return error;console.error("Document GET failure",error);return Response.json({code:"INTERNAL_ERROR",error:"Não foi possível consultar os documentos."},{status:500})}}
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({code:"FORBIDDEN",error:"Origem não autorizada."},{status:403});const operationId=new URL(request.url).searchParams.get("operation");if(!operationId||!z.string().uuid().safeParse(operationId).success)return Response.json({code:"BAD_REQUEST",error:"Operação inválida."},{status:400});if(request.headers.get("content-type")!=="application/pdf")return Response.json({code:"BAD_REQUEST",error:"Envie um arquivo PDF."},{status:400});
 try{const tenant=await requireTenantPermission(request.headers,"document:upload");if(!await getOperation(operationId,undefined,tenant.organizationId))return Response.json({code:"NOT_FOUND",error:"Operação não encontrada."},{status:404});const reader=request.body?.getReader();if(!reader)return Response.json({code:"BAD_REQUEST",error:"Arquivo vazio."},{status:400});let size=0;const chunks:Uint8Array[]=[];while(true){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX){await reader.cancel();return Response.json({code:"BAD_REQUEST",error:"O limite é de 5 MB por PDF."},{status:413})}chunks.push(value)}const bytes=Buffer.concat(chunks);if(bytes.subarray(0,5).toString()!=="%PDF-")return Response.json({code:"VALIDATION_FAILED",error:"O conteúdo não corresponde a um PDF válido."},{status:400});const raw=decodeURIComponent(request.headers.get("x-file-name")||"documento.pdf");if(!raw.toLowerCase().endsWith(".pdf"))return Response.json({code:"VALIDATION_FAILED",error:"A extensão do arquivo deve ser .pdf."},{status:400});const name=raw.replace(/[\r\n\/\\]/g,"_").slice(0,180);const document=await documentStorage.upload({operationId,organizationId:tenant.organizationId,name,bytes,createdBy:tenant.userId});await appendAudit({organizationId:tenant.organizationId,actorUserId:tenant.userId,action:"DOCUMENT_UPLOADED",entityType:"document",entityId:document.id,previousStateSummary:{},nextStateSummary:{status:document.status,scanStatus:document.scanStatus},metadata:{operationId,size:document.size,hash:document.hash},requestId:requestId(request),source:"DOCUMENT_API"});return Response.json({document},{status:201})
 }catch(error){if(error instanceof Response)return error;const message=error instanceof Error&&error.message.includes("UNIQUE")?"Este PDF já está anexado à operação.":"Não foi possível armazenar o documento.";return Response.json({code:"CONFLICT",error:message},{status:error instanceof Error&&error.message.includes("UNIQUE")?409:500})}}
export async function PATCH(request:Request){
 if(!sameOrigin(request))return Response.json({code:"FORBIDDEN",error:"Origem não autorizada."},{status:403});
 try{const tenant=await requireTenantPermission(request.headers,"document:review");const input=reviewSchema.parse(await request.json());const before=await documentStorage.getMetadata(input.id,tenant.organizationId);if(!before)return Response.json({code:"NOT_FOUND",error:"Documento não encontrado."},{status:404});
  if(input.status==="SAFE"&&before.scanStatus!=="CLEAN")return Response.json({code:"VALIDATION_FAILED",error:"Um documento sem varredura real não pode ser marcado como seguro. Use Recebido ou mantenha em quarentena."},{status:409});
  const after=await documentStorage.updateReview(input.id,tenant.organizationId,input);await appendAudit({organizationId:tenant.organizationId,actorUserId:tenant.userId,action:"DOCUMENT_STATUS_CHANGED",entityType:"document",entityId:input.id,previousStateSummary:{status:before.status,category:before.category},nextStateSummary:{status:after?.status||input.status,category:after?.category||input.category},metadata:{operationId:before.operationId},requestId:requestId(request),source:"DOCUMENT_API"});return Response.json({document:after})
 }catch(error){if(error instanceof Response)return error;if(error instanceof z.ZodError)return Response.json({code:"VALIDATION_FAILED",error:"Revisão documental inválida.",issues:error.issues},{status:400});return Response.json({code:"INTERNAL_ERROR",error:"Não foi possível revisar o documento."},{status:500})}}
