import {NextResponse} from "next/server";
import {createClient} from "@libsql/client";
import {z} from "zod";
import {requireTenantPermission} from "@/lib/tenant";
import {appendAudit} from "@/lib/audit";
import {defaultAcquisitionProfile} from "@/lib/lead-qualification";
import {createDatabaseClient} from "@/lib/database-config";
export const runtime="nodejs";
const db=createDatabaseClient();
const schema=z.object({minimumPrecatory:z.number().finite().nonnegative().max(1_000_000_000_000),minimumOfficialEvidence:z.number().int().min(2).max(10).default(2),state:z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).default("SP"),tribunal:z.string().trim().min(2).max(40).default("TJSP"),officeLabels:z.tuple([z.string().trim().min(1).max(120),z.string().trim().min(1).max(120)]),freshDays:z.number().int().min(1).max(365),recentDays:z.number().int().min(1).max(730)}).strict();
async function init(){await db.execute("CREATE TABLE IF NOT EXISTS acquisition_profiles (organization_id TEXT PRIMARY KEY, profile_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL)")}
export async function GET(request:Request){try{const t=await requireTenantPermission(request.headers,"operation:read");await init();const r=await db.execute({sql:"SELECT profile_json,version,updated_at FROM acquisition_profiles WHERE organization_id=?",args:[t.organizationId]});if(!r.rows[0])return NextResponse.json({profile:defaultAcquisitionProfile});const profile={...defaultAcquisitionProfile,...JSON.parse(String(r.rows[0].profile_json)),version:String(r.rows[0].version)};return NextResponse.json({profile,updatedAt:String(r.rows[0].updated_at)},{headers:{"cache-control":"no-store"}})}catch(e){if(e instanceof Response)return e;return NextResponse.json({error:"Não foi possível carregar os critérios."},{status:500})}}
export async function PUT(request:Request){if(request.headers.get("origin")!==new URL(request.url).origin)return NextResponse.json({error:"Origem não autorizada."},{status:403});try{const t=await requireTenantPermission(request.headers,"operation:write");if(!["owner","admin"].includes(t.role.toLowerCase()))return NextResponse.json({error:"Somente proprietários e administradores podem alterar o perfil."},{status:403});const input=schema.parse(await request.json());if(input.recentDays<input.freshDays)return NextResponse.json({error:"O período recente deve ser igual ou maior que o período atualizado."},{status:400});await init();const before=await db.execute({sql:"SELECT version FROM acquisition_profiles WHERE organization_id=?",args:[t.organizationId]}),version=Number(before.rows[0]?.version||0)+1,profile={...defaultAcquisitionProfile,...input,version:String(version)};await db.execute({sql:"INSERT INTO acquisition_profiles (organization_id,profile_json,version,updated_at) VALUES (?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET profile_json=excluded.profile_json,version=excluded.version,updated_at=excluded.updated_at",args:[t.organizationId,JSON.stringify(input),version,new Date().toISOString()]});await appendAudit({organizationId:t.organizationId,actorUserId:t.userId,action:"OPPORTUNITY_UPDATED",entityType:"acquisition_profile",entityId:profile.id,previousStateSummary:{version:version-1},nextStateSummary:{version,minimum:input.minimumPrecatory,minimumOfficialEvidence:input.minimumOfficialEvidence,state:input.state,tribunal:input.tribunal,officeLabels:input.officeLabels.join(" | ")},metadata:{},requestId:crypto.randomUUID(),source:"LEAD_CENTER_PROFILE"});return NextResponse.json({profile})}catch(e){if(e instanceof Response)return e;if(e instanceof z.ZodError)return NextResponse.json({error:"Critérios inválidos."},{status:400});return NextResponse.json({error:"Não foi possível salvar os critérios."},{status:500})}}
