import { NextResponse } from "next/server";
import Papa from "papaparse";
import * as XLSX from "xlsx";
import { requireTenantPermission } from "@/lib/tenant";
import { profileTjspDataset } from "@/lib/tjsp-import";
import { readTjspCacReport } from "@/lib/tjsp-cac-report";

export const runtime="nodejs";
const MAX=20*1024*1024;
export async function POST(request:Request){try{await requireTenantPermission(request.headers,"operation:write");const form=await request.formData(),file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:"Selecione um arquivo CSV ou Excel."},{status:400});if(file.size>MAX)return NextResponse.json({error:"O arquivo excede 20 MB."},{status:413});const name=file.name.replace(/[\r\n/\\]/g,"_").slice(0,160),ext=name.split(".").pop()?.toLowerCase();if(!["csv","xls","xlsx","pdf","zip"].includes(ext||""))return NextResponse.json({error:"Use CSV, XLS, XLSX, PDF ou ZIP."},{status:415});const bytes=new Uint8Array(await file.arrayBuffer());if(ext==="pdf"||ext==="zip"){if(String(form.get("sourceId")||"")!=="tjsp-cac-assisted")return NextResponse.json({error:"PDF e ZIP são aceitos somente para a fonte assistida TJSP/CAC."},{status:400});try{const report=await readTjspCacReport(bytes,name),parsed=Papa.parse<string[]>(report.csv,{header:false,skipEmptyLines:true,delimiter:";"}),rows=parsed.data as string[][],profile=profileTjspDataset(rows);return NextResponse.json({fileName:name,kind:"pdf",sheets:[{name:report.archiveEntry,rows:rows.slice(0,101),recordsFound:profile.recordCount,profile,profileSampled:false}],selectedSheet:report.archiveEntry,headers:rows[0]||[],preview:rows.slice(1,6),recordsFound:profile.recordCount,profile,profileSampled:false,errors:parsed.errors.slice(0,20).map(error=>error.message)})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Não foi possível analisar o PDF oficial do CAC."},{status:400})}}if(ext==="csv"){const text=new TextDecoder("utf-8").decode(bytes),parsed=Papa.parse<string[]>(text,{skipEmptyLines:true});const rows=parsed.data as string[][];return NextResponse.json({fileName:name,kind:"csv",sheets:[{name:"CSV",rows:rows.slice(0,101)}],selectedSheet:"CSV",headers:rows[0]||[],preview:(rows.slice(1,6)),recordsFound:Math.max(rows.length-1,0),profile:profileTjspDataset(rows),profileSampled:false,suggestedHeaderRow:1,errors:parsed.errors.slice(0,20).map(e=>e.message)})}
const xlsMagic=bytes.length>8&&bytes[0]===0xd0&&bytes[1]===0xcf&&bytes[2]===0x11&&bytes[3]===0xe0,xlsxMagic=bytes.length>4&&bytes[0]===0x50&&bytes[1]===0x4b;if((ext==="xls"&&!xlsMagic)||(ext==="xlsx"&&!xlsxMagic))return NextResponse.json({error:"A extensão não corresponde ao conteúdo do arquivo."},{status:400});const book=XLSX.read(bytes,{type:"array",cellDates:false,sheetRows:101});const sheets=book.SheetNames.map(sheetName=>{const allRows=XLSX.utils.sheet_to_json<string[]>(book.Sheets[sheetName],{header:1,raw:false,defval:"",blankrows:false});return{name:sheetName,rows:allRows.slice(0,101),recordsFound:Math.max(allRows.length-1,0),profile:profileTjspDataset(allRows),profileSampled:true}});const likely=sheets.filter(s=>s.rows.some(r=>r.some(v=>/credor|benefici|devedor|precat|valor|processo/i.test(String(v)))));return NextResponse.json({fileName:name,kind:"xlsx",sheets,selectedSheet:"",headers:[],preview:[],recordsFound:0,suggestedSheets:likely.map(s=>s.name),message:sheets.length>1?"Escolha a planilha que deseja importar.":"Revise a planilha e mapeie as colunas."})}catch(e){if(e instanceof Response)return e;console.error("Capture preview failed",e);return NextResponse.json({error:"Não foi possível interpretar esta planilha."},{status:400})}}
