import { test, expect } from "@playwright/test";
import * as XLSX from "xlsx";
import { zipSync } from "fflate";

function syntheticPdf(){
  const stream="BT /F1 12 Tf 50 700 Td (Processo 1000001-00.2020.8.26.0001 PRECATORIO PRC-CP-2026-991 DEPRE 000123 Oficio 1 R$ 250.000,00) Tj ET";
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",`<< /Length ${Buffer.byteLength(stream,"latin1")} >>\nstream\n${stream}\nendstream`];
  let output="%PDF-1.4\n";const offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(output,"latin1"));output+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`}const xref=Buffer.byteLength(output,"latin1");output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${String(o).padStart(10,"0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(output,"latin1");
}

function syntheticCacZip(){
  const items:[number,number,string][]=[
    [60,800,"Lista de precatorios pendentes de pagamento"],[75,734,"Ordem"],[108,734,"1"],
    [124,734,"Pagamento:"],[196,734,"2026"],[343,734,"Nº Processo DEPRE:"],[448,734,"1234567-12.2024.8.26.0001"],
    [75,722,"Natureza:"],[196,722,"ALIMENTAR"],[75,715,"ES/EP:"],[196,715,"5910/2014"],[108,710,"autos:"],[196,710,"7654321-12.2020.8.26.0001"],
    [339,710,"Ordem Orçamentária:"],[448,710,"2025"],[349,698,"Valor atualizado:"],[554,698,"250.000,00"],
    [75,685,"Data"],[189,685,"01/09/2026"],[119,685,"Protocolo:"],[441,685,"12345"],
    [75,647,"Devedora:"],[147,647,"MUNICIPIO TESTE"],
  ];
  const escape=(text:string)=>text.replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
  const stream=items.map(([x,y,text])=>`BT /F1 10 Tf 1 0 0 1 ${x} ${y} Tm (${escape(text)}) Tj ET`).join("\n");
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",`<< /Length ${Buffer.byteLength(stream,"latin1")} >>\nstream\n${stream}\nendstream`];
  let pdf="%PDF-1.4\n";const offsets=[0];for(let index=0;index<objects.length;index++){offsets.push(Buffer.byteLength(pdf,"latin1"));pdf+=`${index+1} 0 obj\n${objects[index]}\nendobj\n`}const xref=Buffer.byteLength(pdf,"latin1");pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,"0")} 00000 n \n`).join("")}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(zipSync({"ListaPrecatorioPendente_TESTE.pdf":Buffer.from(pdf,"latin1")}));
}

test("public business entry explains the synthetic demo without exposing records",async({page})=>{
  await page.goto("/");
  const platformNavigation=page.waitForURL("**/plataforma");
  await page.getByRole("link",{name:/Conhecer plataforma/}).click();
  await platformNavigation;
  await expect(page.getByRole("heading",{name:"Central de captação e operação de precatórios."})).toBeVisible();
  await page.getByRole("link",{name:/Ver demonstração/}).click();
  await expect(page.getByText("Demonstração · Dados sintéticos — sem validade real",{exact:false})).toBeVisible();
  await expect(page.getByText("DEMO-DEPRE-0001").first()).toBeVisible();
  await expect(page.getByText("Fonte sintética CP — demonstração").first()).toBeVisible();
  await expect(page.getByRole("link",{name:/Entrar para abrir a demo/})).toHaveAttribute("href","/conta");
  await expect(page.getByText("Credor Sintético Um")).toHaveCount(0);
});

test("Lead Center importa, preserva conflito, mostra fonte e converte para oportunidade",async({page,request})=>{
  const email=`cp-e2e-${Date.now()}@example.invalid`;
  await page.goto("/");
  await expect(page.locator("body")).toContainText("Central Precatórios");
  await page.goto("/conta");
  await page.getByRole("button",{name:"Ainda não tenho conta"}).click();
  await page.getByLabel("Seu nome").fill("Teste CP E2E");
  await page.getByLabel("E-mail").fill(email);
  await page.getByLabel("Senha").fill("Senha-Local-E2E-2026!");
  await page.getByRole("button",{name:"Criar conta"}).click();
  await expect(page.getByRole("heading",{name:"Olá, Teste CP E2E."})).toBeVisible({timeout:20_000});
  await page.getByLabel("Nome da empresa").fill("CP Testes");
  await page.getByLabel("Identificador").fill(`cp-e2e-${Date.now()}`);
  await page.getByRole("button",{name:"Criar organização"}).click();
  await expect(page.getByRole("link",{name:/Abrir mesa de CP Testes/})).toBeVisible({timeout:15_000});
  const workspaceNavigation = page.waitForURL("**/workspace");
  await page.getByRole("link",{name:/Abrir mesa de CP Testes/}).click();
  await workspaceNavigation;
  await expect(page.getByRole("heading",{name:"Operações"})).toBeVisible();
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  await expect(page.getByRole("heading",{name:"Central de Captação"})).toBeVisible();
  const demoLoadResponse=page.waitForResponse(r=>r.url().includes("/api/demo")&&r.request().method()==="POST",{timeout:90_000});
  await page.getByRole("button",{name:"Carregar demonstração"}).click();
  const demoLoad=await demoLoadResponse;
  expect(demoLoad.status(),await demoLoad.text()).toBe(200);
  await expect(page.getByRole("heading",{name:"Lead captado · demonstração"})).toBeVisible({timeout:30_000});
  await expect(page.getByText(/DADOS DE DEMONSTRAÇÃO — totais abaixo consideram somente registros sintéticos/)).toBeVisible();
  await expect(page.locator("article").filter({hasText:"Operações demonstrativas"})).toContainText("1");
  await expect(page.getByRole("button",{name:"Exemplos sintéticos",exact:true})).toHaveAttribute("aria-pressed","true");
  const demoRow=page.getByRole("row").filter({hasText:"João da Silva — DEMONSTRAÇÃO"});
  await expect(demoRow).toContainText("DEMO-DEPRE-0001");
  await expect(demoRow).toContainText(/187\.450,32/);
  await expect(demoRow).toContainText("Fazenda Demonstrativa do Estado de São Paulo");
  await expect(demoRow).toContainText("Natureza: Alimentar");
  await expect(demoRow).toContainText("PERFIL ADERENTE");
  await demoRow.getByRole("button",{name:"Abrir ficha"}).click();
  await expect(page.getByText("João da Silva — DEMONSTRAÇÃO").first()).toBeVisible();
  await expect(page.getByText("CREDOR IDENTIFICADO")).toBeVisible();
  await expect(page.getByText("CURRENT HOLDER CONFIRMED")).toBeVisible();
  await expect(page.getByText("SIMULAÇÃO — DADOS SINTÉTICOS · SEM CONSULTA A FONTE EXTERNA")).toBeVisible();
  await expect(page.getByLabel("Última Validação")).not.toHaveValue("Nunca");
  await page.getByRole("button",{name:"Ver evidências"}).click();
  await expect(page.getByText("Fonte sintética CP — demonstração").first()).toBeVisible();
  await expect(page.getByText("DEMO-CAC-001",{exact:true})).toBeVisible();
  await expect(page.getByText(/Data de coleta:/)).toBeVisible();
  await expect(page.getByText("Confiança: 100%")).toBeVisible();
  await expect(page.getByText("Status: COMPATÍVEL")).toBeVisible();
  await expect(page.getByText(/Trecho: DEMONSTRAÇÃO CP — Nº Processo DEPRE: DEMO-DEPRE-0001/)).toBeVisible();
  await page.getByRole("tab",{name:"Qualificação"}).click();
  await expect(page.getByText(/QUALIFICADO COM PENDENCIAS/)).toBeVisible();
  await expect(page.getByRole("button",{name:"Converter lead em oportunidade"})).toBeVisible();
  const originalId=(await page.locator('[class*="detailHead"] small').innerText()).split(" · ")[0];
  await page.getByRole("button",{name:"Converter lead em oportunidade"}).click();
  await expect(page.getByRole("status").filter({hasText:"Lead convertido em oportunidade mantendo o mesmo registro"})).toBeVisible();
  await expect(page.locator('[class*="detailHead"] small')).toContainText(originalId);
  await expect(page.locator('[class*="detailHead"] small')).toContainText("TRIAGE");
  await page.goto("/crm");
  await expect(page.getByRole("heading",{name:"CRM operacional"})).toBeVisible();
  const canonicalOperationId = await page.evaluate(async () => {
    const response = await fetch("/api/operations");
    const body = await response.json() as { operations: Array<{ id: string; workflow: { credit: { numeroProcessoDEPRE: string } } }> };
    return body.operations.find((operation) => operation.workflow.credit.numeroProcessoDEPRE === "DEMO-DEPRE-0001")?.id ?? null;
  });
  if (!canonicalOperationId) throw new Error("Synthetic demo operation was not returned by the tenant API.");
  const unauthorizedMutation = await request.post("/api/crm", { data: { action: "create", id: crypto.randomUUID(), operationId: canonicalOperationId } });
  expect(unauthorizedMutation.status()).toBe(403);
  await page.getByLabel("ID da operação").fill(canonicalOperationId);
  await page.getByRole("button",{name:"Criar registro CRM"}).click();
  const crmCard=page.locator("article").filter({hasText:canonicalOperationId});
  await expect(crmCard).toBeVisible({timeout:15_000});
  await crmCard.getByLabel("Estágio").selectOption("QUALIFICATION");
  await expect(crmCard.getByLabel("Estágio")).toHaveValue("QUALIFICATION");
  await crmCard.getByLabel("Estágio").selectOption("CONTACT_PENDING");
  await crmCard.getByRole("button",{name:"Registrar contato concluído"}).click();
  await crmCard.getByLabel("Estágio").selectOption("CONTACTED");
  await expect(crmCard.getByLabel("Estágio")).toHaveValue("CONTACTED");
  await crmCard.getByRole("button",{name:"Criar tarefa"}).click();
  await crmCard.getByRole("button",{name:"Registrar nota"}).click();
  const taskAudit = await page.evaluate(async () => (await (await fetch("/api/audit?entityType=crm_task")).json()).events as { action: string }[]);
  const activityAudit = await page.evaluate(async () => (await (await fetch("/api/audit?entityType=crm_activity")).json()).events as { action: string }[]);
  expect(taskAudit.some((event) => event.action === "CRM_TASK_CREATED")).toBe(true);
  expect(activityAudit.some((event) => event.action === "CRM_ACTIVITY_RECORDED")).toBe(true);
  await page.reload();
  await expect(page.locator("article").filter({hasText:canonicalOperationId}).getByLabel("Estágio")).toHaveValue("CONTACTED");
  await page.goto("/workspace");
  await page.getByRole("button",{name:"Captação",exact:true}).click();
  await page.getByRole("button",{name:"Exemplos sintéticos",exact:true}).click();
  await page.getByRole("button",{name:"Operações",exact:true}).click();
  const demoOperationCard = page.getByRole("button").filter({hasText:"DEMONSTRAÇÃO — João da Silva"}).first();
  await expect(demoOperationCard).toBeVisible();
  await demoOperationCard.click();
  await page.getByRole("tab",{name:"Documentos"}).click();
  await expect(page.getByText("Documento demonstrativo — identificação do crédito.pdf")).toBeVisible();
  await expect(page.getByText(/TEXT_EXTRACTED.*correspondência MATCH/)).toBeVisible();
  await expect(page.getByText("DOCUMENTO DE DEMONSTRAÇÃO — SEM VALIDADE REAL")).toBeVisible();
  await expect(page.getByRole("button",{name:"Abrir revisão jurídica"})).toBeVisible();
  await page.getByRole("tab",{name:"Jurídico"}).click();
  await expect(page.getByText("SIMULAÇÃO — DADOS SINTÉTICOS · SEM APROVAÇÃO JURÍDICA REAL")).toBeVisible();
  await expect(page.getByLabel("Decisão")).toHaveValue("APPROVED_WITH_REMARKS");
  await expect(page.getByText(/Documento demonstrativo sujeito à conferência humana/)).toBeVisible();
  await page.getByRole("button",{name:"Ir para precificação"}).click();
  await expect(page.getByText("CENÁRIO SINTÉTICO — SEM VALIDADE REAL")).toBeVisible();
  await expect(page.getByText(/Valor de referência:.*187\.450,32/)).toBeVisible();
  await expect(page.getByText(/oferta indicativa.*142\.460,26/i)).toBeVisible();
  await page.getByRole("button",{name:"Registrar proposta\/oferta"}).click();
  await page.getByRole("button",{name:"Nova proposta\/oferta"}).click();
  await expect(page.getByRole("heading",{name:"Proposta / oferta"})).toBeVisible();
  await expect(page.getByLabel("Valor")).toHaveValue("142460.26");
  await expect(page.getByLabel("Criada por")).toHaveValue("Analista de demonstração");
  await expect(page.getByLabel("Data e hora")).not.toHaveValue("");
  await expect(page.getByLabel("Condições")).toHaveValue(/Proposta demonstrativa/);
  const offerSave = page.waitForResponse(response => response.url().endsWith("/api/operations") && response.request().method() === "PUT");
  await page.getByRole("button",{name:"Salvar",exact:true}).click();
  const offerSaveResponse = await offerSave;
  expect(offerSaveResponse.status()).toBe(200);
  const savedOffer = await offerSaveResponse.json() as { operation: { workflow: { commercialStatus: string; negotiations: unknown[] } } };
  expect(savedOffer.operation.workflow).toMatchObject({ commercialStatus: "OFFERED" });
  expect(savedOffer.operation.workflow.negotiations).toHaveLength(1);
  const offerAudit = await page.evaluate(async (operationId) => {
    const response = await fetch(`/api/audit?entityType=opportunity&entityId=${encodeURIComponent(operationId)}`);
    return (await response.json()).events as { action: string }[];
  }, canonicalOperationId);
  expect(offerAudit.some((event) => event.action === "OFFER_CREATED")).toBe(true);
  await page.getByRole("tab",{name:"Visão geral"}).click();
  await expect(page.getByText("DEMO-DEPRE-0001").first()).toBeVisible();
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  const convertedDemoRow=page.getByRole("row").filter({hasText:"João da Silva — DEMONSTRAÇÃO"});
  await expect(convertedDemoRow).toBeVisible();
  await convertedDemoRow.getByRole("button",{name:"Abrir ficha"}).click();
  await expect(page.locator('[class*="detailHead"] small')).toContainText("TRIAGE");
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  await page.getByRole("button",{name:"Base operacional"}).click();
  await expect(page.getByRole("heading",{name:"Oportunidades disponíveis"})).toBeVisible();
  await expect(page.locator("article").filter({hasText:"Operações de produção"})).toContainText("0");
  await expect(page.getByText(/Esta fonte exige uma etapa humana para concluir a consulta/)).toBeVisible();
  await expect(page.getByRole("link",{name:/Abrir consulta TJSP\/CAC/})).toBeVisible();
  await expect(page.getByRole("link",{name:/Importar resultado CAC/})).toBeVisible();
  await page.getByLabel("Fonte desta lista").selectOption("tjsp-cac-assisted");
  const csv="Número do precatório;Número do processo;Credor;Entidade devedora;Município;Valor atualizado;Tipo;Tribunal\nPRC-CP-2026-991;1000001-00.2020.8.26.0001;Credor Sintético Um;Município de Teste;Campinas;R$ 250.000,00;Precatório;TJSP\nRPV-CP-2026-992;1000002-00.2020.8.26.0001;Credora Sintética Dois;Município de Teste;Santos;R$ 12.000,00;RPV;TJSP";
  await page.locator("#lead-import-file").setInputFiles({name:"lista-tjsp-e2e.csv",mimeType:"text/csv",buffer:Buffer.from(csv)});
  await expect(page.getByText(/2 registros encontrados/)).toBeVisible({timeout:30_000});
  await expect(page.getByText(/2 registros perfilados \(arquivo completo\).*linhas duplicadas/i)).toBeVisible();
  const firstImport=page.waitForResponse(r=>r.url().includes("/api/capture/import"),{timeout:45_000});
  await page.getByRole("button",{name:"Importar planilha"}).click();
  const firstImportResponse=await firstImport;
  const firstBody=await firstImportResponse.text(),firstHeaders=await firstImportResponse.request().allHeaders();
  expect(firstImportResponse.status(),`${firstBody} ${JSON.stringify({url:firstImportResponse.url(),origin:firstHeaders.origin,referer:firstHeaders.referer,fetchSite:firstHeaders["sec-fetch-site"]})}`).toBe(200);
  await expect(page.getByRole("status").filter({hasText:/2 novos|já foi processada/})).toBeVisible({timeout:20_000});
  await expect(page.getByText("Credor Sintético Um")).toBeVisible();
  await expect(page.locator("article").filter({hasText:"Operações de produção"})).toContainText("2");
  await expect(page.getByText(/RPV · análise particular \(1\)/)).toBeVisible();
  await expect(page.getByText(/Histórico de importações \(1\)/)).toBeVisible();
  await expect(page.getByText(/TJSP\/CAC · Captura assistida · ASSISTED/)).toBeVisible();
  await page.getByText("Benchmark Mode · comparar saída externa com CP").click();
  await page.locator("#benchmark-file").setInputFiles({name:"robot-externo.csv",mimeType:"text/csv",buffer:Buffer.from("Número do precatório;Número do processo;Credor;Entidade devedora;Município;Valor atualizado;Tipo;Tribunal\nPRC-CP-2026-991;1000001-00.2020.8.26.0001;Credor Sintético Um;Município de Teste;Campinas;R$ 250.000,00;Precatório;TJSP\nPRC-ROBOT-777;1000777-00.2020.8.26.0001;Credor Externo;Município de Teste;Santos;R$ 130.000,00;Precatório;TJSP")});
  await page.getByRole("button",{name:"Gerar comparação factual"}).click();
  await expect(page.getByRole("status").filter({hasText:"linhas comparadas"})).toContainText("2 linhas comparadas");
  await expect(page.getByText("Correspondências").first()).toBeVisible();

  const conflict="Número do precatório;Número do processo;Credor;Entidade devedora;Município;Valor atualizado;Tipo;Tribunal\nPRC-CP-2026-991;1000001-00.2020.8.26.0001;Credor Sintético Um;Município de Teste;Campinas;R$ 275.000,00;Precatório;TJSP";
  await page.locator("#lead-import-file").setInputFiles({name:"lista-tjsp-e2e-atualizada.csv",mimeType:"text/csv",buffer:Buffer.from(conflict)});
  await page.getByRole("button",{name:"Importar planilha"}).click();
  await expect(page.getByRole("status").filter({hasText:"conflitos"})).toContainText("1 conflitos",{timeout:20_000});
  await expect(page.getByText(/Histórico de importações \(2\)/)).toBeVisible();

  await page.getByRole("button",{name:"Abrir ficha"}).first().click();
  await page.getByRole("tab",{name:"Documentos"}).click();
  await page.getByLabel(/Adicionar PDF/).setInputFiles({name:"Oficio 1 - sintetico.pdf",mimeType:"application/pdf",buffer:syntheticPdf()});
  await expect(page.getByText(/correspondência MATCH/)).toBeVisible({timeout:30_000});
  await page.getByRole("tab",{name:"Qualificação"}).click();
  await page.getByRole("button",{name:"Converter lead em oportunidade"}).click();
  await expect(page.getByText(/Lead convertido em oportunidade mantendo o mesmo registro/)).toBeVisible({timeout:15_000});
  await page.getByRole("tab",{name:"Histórico"}).click();
  await expect(page.getByText(/LEAD_CONVERTED|Lead convertido/i).first()).toBeVisible({timeout:15_000});
  await page.getByRole("tab",{name:"Documentos"}).click();
  await expect(page.getByText("Oficio 1 - sintetico.pdf")).toBeVisible();
  await page.getByRole("button",{name:"Operações"}).click();
  await page.getByText(/Precatório PRC-CP-2026-991/).first().click();
  await page.getByRole("tab",{name:"Cadastro"}).click();
  await expect(page.getByLabel("Origem / fonte consultada")).toHaveValue(/Lead Center/);
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  const book=XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([["Notas"],["Planilha irrelevante"]]),"Notas");
  XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([["Número Precatório","Processo","Credor","Devedor","Município","Valor","Tipo","Tribunal"],["PRC-CP-XLSX-333","1000003-00.2020.8.26.0001","Credor XLSX Sintético","Município de Teste","São Paulo","R$ 180.000,00","Precatório","TJSP"]]),"Credores");
  await page.locator("#lead-import-file").setInputFiles({name:"lista-tjsp-e2e.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:XLSX.write(book,{type:"buffer",bookType:"xlsx"})});
  await expect(page.getByRole("combobox",{name:"Planilha"})).toBeVisible({timeout:30_000});
  await expect(page.getByRole("button",{name:"Importar planilha"})).toBeDisabled();
  await page.getByRole("combobox",{name:"Planilha"}).selectOption("Credores");
  await page.getByRole("button",{name:"Importar planilha"}).click();
  await expect(page.getByRole("status").filter({hasText:"novos"})).toContainText("1 novos",{timeout:30_000});
  await expect(page.getByText("Credor XLSX Sintético")).toBeVisible();
  const cacZip=syntheticCacZip();
  await page.locator("#lead-import-file").setInputFiles({name:"SCP_DEPRE_LISTAPRECATORIOPENDENTE_TESTE.ZIP",mimeType:"application/zip",buffer:cacZip});
  await expect(page.getByLabel("Fonte desta lista")).toHaveValue("tjsp-cac-assisted");
  await page.getByLabel("Data da lista/publicação (se indicada no relatório)").fill("2026-09-04");
  await expect(page.getByText(/1 registros perfilados/)).toBeVisible({timeout:30_000});
  const cacImportPromise=page.waitForResponse(r=>r.url().includes("/api/capture/import-cac")&&r.request().method()==="POST");
  await page.getByRole("button",{name:"Importar planilha"}).click();
  const cacResponse=await cacImportPromise,cacBody=await cacResponse.json();
  expect(cacResponse.status()).toBe(200);
  expect(cacBody.summary.read).toBe(1);
  expect(cacBody.notice).toContain("2026-09-04");
  await expect(page.getByRole("status").filter({hasText:/1 novos/})).toContainText("1 novos",{timeout:30_000});
  await expect(page.getByText("1234567-12.2024.8.26.0001").first()).toBeVisible();
  await expect(page.getByText("Nº Processo DEPRE").first()).toBeVisible();
  await expect(page.getByText("data-base 2026-09-04").first()).toBeVisible();
  await page.getByText("1234567-12.2024.8.26.0001").first().click();
  await expect(page.getByText("EP/ES: 5910/2014")).toBeVisible();
  await page.getByRole("tab",{name:"Qualificação"}).click();
  await expect(page.getByLabel("Nº Processo DEPRE")).toHaveValue("1234567-12.2024.8.26.0001");
  await expect(page.getByText("Valor normalizado: 12345671220248260001")).toBeVisible();
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  await page.locator("#lead-import-file").setInputFiles({name:"SCP_DEPRE_LISTAPRECATORIOPENDENTE_TESTE.ZIP",mimeType:"application/zip",buffer:cacZip});
  await expect(page.getByText(/1 registros perfilados/)).toBeVisible({timeout:30_000});
  await page.getByRole("button",{name:"Importar planilha"}).click();
  await expect(page.getByRole("status").filter({hasText:/já foi processada/})).toBeVisible({timeout:30_000});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("button",{name:"Captação", exact: true}).click();
  await expect(page.getByRole("heading",{name:"Oportunidades disponíveis"})).toBeVisible();
  const width=await page.evaluate(()=>document.documentElement.scrollWidth);
  expect(width).toBeLessThanOrEqual(390);
});
