"use client";import{useCallback,useEffect,useState}from"react";import{FileCheck2,RefreshCw,ShieldAlert}from"lucide-react";import styles from"./operations.module.css";
type Document={id:string;name:string;hash:string;size:number;status:"UPLOADED"|"QUARANTINED"|"SCANNING"|"SAFE"|"REJECTED"|"ARCHIVED";scanStatus:string;category:string;version:number;reviewerNotes:string;retentionUntil:string;createdAt:string};
const statusLabels:Record<string,string>={UPLOADED:"Recebido",QUARANTINED:"Em quarentena",SCANNING:"Em verificação",SAFE:"Validado pelo fluxo configurado",REJECTED:"Rejeitado",ARCHIVED:"Arquivado"};
const categories=["IDENTIDADE","CPF_CNPJ","COMPROVANTE_ENDERECO","PRECATORIO","PROCESSO","PROCURACAO","PARECER_JURIDICO","PROPOSTA","CESSAO","OUTRO"];
export default function Documents({operation}:{operation:string}){const[docs,setDocs]=useState<Document[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{setError("");setLoading(true);try{const r=await fetch(`/api/operations/documents?operation=${operation}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setDocs(d.documents)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar documentos.")}finally{setLoading(false)}},[operation]);useEffect(()=>{void refresh()},[refresh]);
 async function upload(file:File){setBusy(true);setError("");setMessage("");try{if(file.size>5*1024*1024)throw Error("O limite é de 5 MB por arquivo.");if(file.type!=="application/pdf"||!file.name.toLowerCase().endsWith(".pdf"))throw Error("Selecione um arquivo PDF.");const r=await fetch(`/api/operations/documents?operation=${operation}`,{method:"POST",headers:{"content-type":"application/pdf","x-file-name":encodeURIComponent(file.name)},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage("PDF recebido em quarentena. Nenhuma varredura real foi executada.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Falha no envio.")}finally{setBusy(false)}}
 async function review(doc:Document,patch:Partial<Document>){setBusy(true);setError("");try{const payload={id:doc.id,status:patch.status||doc.status,category:patch.category||doc.category,reviewerNotes:patch.reviewerNotes??doc.reviewerNotes,retentionUntil:patch.retentionUntil??doc.retentionUntil};const r=await fetch("/api/operations/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);setDocs(v=>v.map(x=>x.id===doc.id?d.document:x));setMessage("Classificação documental atualizada e auditada.")}catch(e){setError(e instanceof Error?e.message:"Falha na revisão.")}finally{setBusy(false)}}
 const active=docs.filter(d=>!['ARCHIVED','REJECTED'].includes(d.status)),complete=active.length?Math.round(active.filter(d=>d.category!=="OUTRO"&&['UPLOADED','SAFE'].includes(d.status)).length/active.length*100):0;
 return <div><div className={styles.documentHead}><div><h3>Central de documentos</h3><p>Completude operacional: <b>{complete}%</b> · {active.length} arquivo(s) ativo(s).</p></div><button onClick={()=>void refresh()} disabled={loading||busy}><RefreshCw size={16}/> Atualizar</button></div><div className={styles.notice}><ShieldAlert/><div><b>Armazenamento privado do MVP</b><p>Downloads exigem sessão, organização e permissão. Sem antivírus configurado, novos arquivos permanecem em quarentena com status DEMO_SCAN/NOT_SCANNED — nunca são marcados como seguros automaticamente.</p></div></div><label>Adicionar PDF de até 5 MB<input disabled={busy} type="file" accept="application/pdf,.pdf" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value=""}}/></label>{busy&&<p role="status">Processando documento…</p>}{loading&&<p role="status">Carregando documentos…</p>}{error&&<div className={styles.error} role="alert">{error} <button onClick={()=>void refresh()}>Tentar novamente</button></div>}{message&&<p className={styles.success} role="status">{message}</p>}{!loading&&!error&&docs.length===0?<p>Nenhum PDF anexado. A lista de documentos necessários deve ser definida para este caso.</p>:docs.map(d=><article key={d.id} className={styles.documentCard}><div><a href={`/api/operations/documents?id=${d.id}`} download>{d.name}</a><p>{statusLabels[d.status]} · {d.scanStatus} · versão {d.version} · {(d.size/1024).toFixed(1)} KB</p><small>SHA-256: {d.hash}</small></div><div className={styles.fields}><label>Categoria<select disabled={busy} value={d.category} onChange={e=>void review(d,{category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select disabled={busy} value={d.status} onChange={e=>void review(d,{status:e.target.value as Document["status"]})}>{["UPLOADED","QUARANTINED","SCANNING","SAFE","REJECTED","ARCHIVED"].map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></label><label>Retenção até<input type="date" value={d.retentionUntil} onChange={e=>void review(d,{retentionUntil:e.target.value})}/></label></div><label>Notas do revisor<textarea value={d.reviewerNotes} onChange={e=>setDocs(v=>v.map(x=>x.id===d.id?{...x,reviewerNotes:e.target.value}:x))} onBlur={()=>void review(d,{reviewerNotes:d.reviewerNotes})}/></label></article>)}</div>}
