"use client";

import { AlertTriangle, CheckCircle2, Plus, Scale, ShieldCheck } from "lucide-react";
import { allowedTransitions, calculatePricing, nextActionFor, transitionBlockReason, type OperationalWorkflow } from "@/lib/operational-workflow";
import styles from "./operations.module.css";

type Props = { workflow: OperationalWorkflow; persistedStage: OperationalWorkflow["stage"]; mode: string; onChange: (workflow: OperationalWorkflow) => void };
const money = (n:number) => n.toLocaleString("pt-BR", { style:"currency", currency:"BRL" });
const labels:Record<string,string>={NEW:"Novo",TRIAGE:"Triagem",QUERY:"Consulta",VALIDATION:"Validação",DOCUMENTS:"Documentos",LEGAL_REVIEW:"Revisão jurídica",APPROVED:"Aprovado",PROPOSAL:"Proposta",NEGOTIATION:"Negociação",ACCEPTED:"Aceito",CESSION:"Cessão",POST_CESSION:"Pós-cessão",COMPLETED:"Concluído",REJECTED:"Reprovado",LOST:"Perdido",BLOCKED:"Bloqueado",CANCELLED:"Cancelado"};

export default function OperationalCase({workflow:w, persistedStage, mode, onChange}:Props) {
  const set = (patch:Partial<OperationalWorkflow>) => onChange({...w,...patch});
  const now = () => new Date().toISOString();
  if (mode === "Visão geral") return <div className={styles.form}>
    <div className={styles.caseSummary}>
      <article><small>PRÓXIMA AÇÃO</small><strong>{nextActionFor(w)}</strong><span>{w.nextAction.dueAt || "Defina um prazo"}</span></article>
      <article><small>CONFIANÇA DO ANALISTA</small><strong>{w.confidence}%</strong><span>Classificação manual, apoiada pelas evidências</span></article>
      <article><small>JURÍDICO</small><strong>{w.legalStatus}</strong><span>{w.legalReviews.length} revisão(ões)</span></article>
      <article><small>DOCUMENTOS</small><strong>{w.documentStatus}</strong><span>Status de conferência</span></article>
    </div>
    <h3>Identificação do caso</h3>
    <div className={styles.fields}>
      <label>Credor<input value={w.client.name} onChange={e=>set({client:{...w.client,name:e.target.value}})}/></label>
      <label>CPF/CNPJ<input value={w.client.document} onChange={e=>set({client:{...w.client,document:e.target.value}})}/></label>
      <label>Telefone<input value={w.client.phone} onChange={e=>set({client:{...w.client,phone:e.target.value}})}/></label>
      <label>E-mail<input type="email" value={w.client.email} onChange={e=>set({client:{...w.client,email:e.target.value}})}/></label>
      <label>Número do precatório<input value={w.credit.precatoryNumber} onChange={e=>set({credit:{...w.credit,precatoryNumber:e.target.value}})}/></label>
      <label>Natureza<input value={w.credit.nature} onChange={e=>set({credit:{...w.credit,nature:e.target.value}})}/></label>
      <label>Prioridade<select value={w.priority} onChange={e=>set({priority:e.target.value as OperationalWorkflow["priority"]})}>{["LOW","MEDIUM","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</select></label>
      <label>Confiança atribuída pelo analista (%)<input type="number" min="0" max="100" value={w.confidence} onChange={e=>set({confidence:Number(e.target.value)})}/></label>
      <label>Status documental<select value={w.documentStatus} onChange={e=>set({documentStatus:e.target.value as OperationalWorkflow["documentStatus"]})}>{[["MISSING","Ausente"],["INCOMPLETE","Incompleto"],["READY","Conferido"],["REVIEW_REQUIRED","Revisão necessária"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    </div>
    <h3>Fluxo controlado</h3><div className={styles.workflowSteps}><b>{labels[w.stage]||w.stage}</b>{w.stage!==persistedStage?<span>Salve esta etapa antes de avançar novamente.</span>:allowedTransitions[w.stage].map(stage=>{const reason=transitionBlockReason(w,stage);return <button title={reason||undefined} disabled={Boolean(reason)} key={stage} onClick={()=>set({stage})}>Avançar para {labels[stage]||stage}</button>})}</div>
    <h3>Próxima ação</h3><div className={styles.fields}><label>Ação<input value={w.nextAction.title} onChange={e=>set({nextAction:{...w.nextAction,title:e.target.value}})}/></label><label>Prazo<input type="date" value={w.nextAction.dueAt.slice(0,10)} onChange={e=>set({nextAction:{...w.nextAction,dueAt:e.target.value}})}/></label><label>Estado<select value={w.nextAction.status} onChange={e=>set({nextAction:{...w.nextAction,status:e.target.value as OperationalWorkflow["nextAction"]["status"]}})}>{["PENDING","DONE","BLOCKED"].map(v=><option key={v}>{v}</option>)}</select></label></div>
  </div>;

  if (mode === "Consulta e validação") return <div className={styles.form}>
    <div className={styles.notice}><ShieldCheck/><div><b>Evidência, não adivinhação</b><p>Registre a fonte, a referência e o grau de confiança. Uma fonte isolada não representa cobertura nacional.</p></div></div>
    <label>Status da consulta<select value={w.queryStatus} onChange={e=>set({queryStatus:e.target.value as OperationalWorkflow["queryStatus"]})}>{[["NOT_STARTED","Não iniciada"],["RUNNING","Em andamento"],["CONFIRMED","Confirmada por evidência"],["PARTIAL","Compatível / parcial"],["UNAVAILABLE","Fonte indisponível"],["MANUAL_REQUIRED","Consulta assistida necessária"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <button onClick={()=>set({evidence:[...w.evidence,{id:crypto.randomUUID(),source:"Fonte oficial a confirmar",sourceType:"OFFICIAL",reference:"",retrievedAt:now(),confidence:0,status:"REVISÃO HUMANA NECESSÁRIA",notes:""}]})}><Plus size={16}/> Registrar evidência</button>
    {w.evidence.map((e,i)=><article className={styles.proposal} key={e.id}><div className={styles.fields}><label>Fonte<input value={e.source} onChange={x=>set({evidence:w.evidence.map((v,j)=>j===i?{...v,source:x.target.value}:v)})}/></label><label>Referência/URL<input value={e.reference} onChange={x=>set({evidence:w.evidence.map((v,j)=>j===i?{...v,reference:x.target.value}:v)})}/></label><label>Confiança<input type="number" min="0" max="100" value={e.confidence} onChange={x=>set({evidence:w.evidence.map((v,j)=>j===i?{...v,confidence:Number(x.target.value)}:v)})}/></label><label>Status<select value={e.status} onChange={x=>set({evidence:w.evidence.map((v,j)=>j===i?{...v,status:x.target.value as typeof e.status}:v)})}>{["CONFIRMADO","COMPATÍVEL","INCOMPLETO","NÃO ENCONTRADO","FONTE INDISPONÍVEL","REVISÃO HUMANA NECESSÁRIA"].map(v=><option key={v}>{v}</option>)}</select></label></div></article>)}
    <button onClick={()=>set({validations:[...w.validations,{id:crypto.randomUUID(),check:"Nova verificação",severity:"INFO",status:"PENDING",explanation:""}]})}><Plus size={16}/> Adicionar verificação</button>
    {w.validations.map((v,i)=><article className={styles.validation} key={v.id}><AlertTriangle size={17}/><input aria-label="Verificação" value={v.check} onChange={e=>set({validations:w.validations.map((x,j)=>j===i?{...x,check:e.target.value}:x)})}/><select aria-label="Severidade" value={v.severity} onChange={e=>set({validations:w.validations.map((x,j)=>j===i?{...x,severity:e.target.value as typeof v.severity}:x)})}>{["INFO","WARNING","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Resultado" value={v.status} onChange={e=>set({validations:w.validations.map((x,j)=>j===i?{...x,status:e.target.value as typeof v.status}:x)})}>{["PENDING","PASSED","FAILED","HUMAN_REVIEW"].map(x=><option key={x}>{x}</option>)}</select></article>)}
  </div>;

  if (mode === "Jurídico") return <div className={styles.form}><div className={styles.notice}><Scale/><div><b>Decisão humana obrigatória</b><p>O CP organiza o dossiê e as pendências; não substitui a revisão de profissional habilitado.</p></div></div><button onClick={()=>set({legalStatus:"PENDING",legalReviews:[...w.legalReviews,{id:crypto.randomUUID(),status:"PENDING",reviewer:"",requestedAt:now(),reviewedAt:"",observations:"",dossierVersion:w.legalReviews.length+1}]})}><Plus size={16}/> Enviar para jurídico</button>{w.legalReviews.map((r,i)=><article className={styles.proposal} key={r.id}><div className={styles.fields}><label>Revisor<input value={r.reviewer} onChange={e=>set({legalReviews:w.legalReviews.map((x,j)=>j===i?{...x,reviewer:e.target.value}:x)})}/></label><label>Decisão<select value={r.status} onChange={e=>{const status=e.target.value as typeof r.status;set({legalStatus:status==="APPROVED"?"APPROVED":status==="APPROVED_WITH_REMARKS"?"REMARKS":status==="REJECTED"?"REJECTED":"PENDING",legalReviews:w.legalReviews.map((x,j)=>j===i?{...x,status,reviewedAt:status==="PENDING"?"":now()}:x)})}}>{["PENDING","APPROVED","APPROVED_WITH_REMARKS","NEEDS_DOCUMENTS","REJECTED"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Observações<textarea value={r.observations} onChange={e=>set({legalReviews:w.legalReviews.map((x,j)=>j===i?{...x,observations:e.target.value}:x)})}/></label></article>)}</div>;

  if (mode === "Precificação") return <div className={styles.form}><p>Cálculos determinísticos: valor disponível = bruto − deduções − gravames; oferta = disponível × (1 − margem) − custos.</p><button onClick={()=>{const base={grossAmount:w.credit.grossAmount,deductions:0,encumbrances:0,transactionCosts:0,targetMarginPercent:20};const result=calculatePricing(base);set({commercialStatus:"PRICING",pricingScenarios:[...w.pricingScenarios,{id:crypto.randomUUID(),name:"BASE",...base,...result,createdAt:now(),assumptions:"Cenário indicativo sujeito à conferência documental e jurídica."}]})}}><Plus size={16}/> Criar cenário base</button>{w.pricingScenarios.map((p,i)=>{const update=(key:keyof typeof p,value:string|number)=>{const next={...p,[key]:value};const calc=calculatePricing(next);set({pricingScenarios:w.pricingScenarios.map((x,j)=>j===i?{...next,...calc}:x)})};return <article className={styles.proposal} key={p.id}><h3>{p.name} · oferta indicativa {money(p.offerAmount)}</h3><div className={styles.fields}>{([['grossAmount','Valor bruto'],['deductions','Deduções'],['encumbrances','Gravames'],['transactionCosts','Custos'],['targetMarginPercent','Margem alvo (%)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={p[key]} onChange={e=>update(key,Number(e.target.value))}/></label>)}</div><p>Disponível estimado: <b>{money(p.availableAmount)}</b>. Sem oferta vinculante ou decisão automática.</p></article>})}</div>;

  if (mode === "Negociação") return <div className={styles.form}><button onClick={()=>set({commercialStatus:"OFFERED",negotiations:[...w.negotiations,{id:crypto.randomUUID(),type:"OFFER",amount:0,at:now(),author:"",conditions:"Rascunho sujeito à confirmação humana."}]})}><Plus size={16}/> Registrar oferta</button>{w.negotiations.map((n,i)=><article className={styles.proposal} key={n.id}><div className={styles.fields}><label>Evento<select value={n.type} onChange={e=>{const type=e.target.value as typeof n.type;set({commercialStatus:type==="ACCEPTED"?"ACCEPTED":type==="REJECTED"?"LOST":"NEGOTIATING",negotiations:w.negotiations.map((x,j)=>j===i?{...x,type}:x)})}}>{["OFFER","COUNTEROFFER","ACCEPTED","REJECTED"].map(x=><option key={x}>{x}</option>)}</select></label><label>Valor<input type="number" min="0" value={n.amount} onChange={e=>set({negotiations:w.negotiations.map((x,j)=>j===i?{...x,amount:Number(e.target.value)}:x)})}/></label><label>Autor<input value={n.author} onChange={e=>set({negotiations:w.negotiations.map((x,j)=>j===i?{...x,author:e.target.value}:x)})}/></label></div><label>Condições<textarea value={n.conditions} onChange={e=>set({negotiations:w.negotiations.map((x,j)=>j===i?{...x,conditions:e.target.value}:x)})}/></label></article>)}</div>;

  if (mode === "Cessão") return <div className={styles.form}><div className={styles.notice}><CheckCircle2/><div><b>Coordenação da cessão</b><p>O CP registra checklist e marcos. Assinatura, protocolo e pagamento dependem de ação humana ou conector configurado.</p></div></div><label>Marco atual<select value={w.cessionStatus} onChange={e=>set({cessionStatus:e.target.value as OperationalWorkflow["cessionStatus"]})}>{["NOT_STARTED","DOCUMENT_CHECK","LEGAL_APPROVAL","FORMALIZATION","PROTOCOL","COMMUNICATION","MONITORING","COMPLETED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></label></div>;

  return <div className={styles.form}><button onClick={()=>set({monitoring:[...w.monitoring,{id:crypto.randomUUID(),date:now(),type:"OUTRO",source:"Registro interno",description:"",importance:"MEDIUM",reviewed:false}]})}><Plus size={16}/> Registrar evento</button>{w.monitoring.map((m,i)=><article className={styles.event} key={m.id}><AlertTriangle size={16}/><div><b>{m.type.replaceAll("_"," ")}</b><textarea aria-label="Descrição do evento" value={m.description} onChange={e=>set({monitoring:w.monitoring.map((x,j)=>j===i?{...x,description:e.target.value}:x)})}/><label><input type="checkbox" checked={m.reviewed} onChange={e=>set({monitoring:w.monitoring.map((x,j)=>j===i?{...x,reviewed:e.target.checked}:x)})}/> Evento revisado</label></div></article>)}</div>;
}
