"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Plus, Download, Search, ArrowLeft, Save, ClipboardList, Layers, Link2, FlaskConical, Trash2 } from "lucide-react";
import styles from "./operations.module.css";
import Documents from "./documents";
import DataJudSearch from "./datajud-search";
import OperationalCase from "./operational-case";
import type { OperationalWorkflow } from "@/lib/operational-workflow";
import AuditTrail from "./audit-trail";

type Operation = {
  id: string; version: number; title: string; debtor: string; tribunal: string; process: string; owner: string; source: string; stage: string; nominal: number; notes: string;
  tasks: {id:string;title:string;due:string;done:boolean}[];
  checks: {id:string;title:string;done:boolean}[];
  proposals: {id:string;buyer:string;price:number;costs:number;months:number;receipt:number;validUntil:string;conditions:string}[];
  history: {at:string;text:string}[];
  workflow: OperationalWorkflow;
  isDemo: boolean;
};
const stages = ["Entrada","Análise","Diligência","Proposta","Formalização","Acompanhamento","Encerrado"];
const tabs = ["Visão geral", "Consulta e validação", "Documentos", "Jurídico", "Precificação", "Negociação", "Cessão", "Monitoramento", "Cadastro", "Tarefas", "Diligência", "Histórico"];
const money = (n:number) => n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function download(name:string, text:string, type="text/plain") {
  const url=URL.createObjectURL(new Blob([text],{type})); const a=document.createElement("a"); a.href=url;a.download=name;a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function OperationsClient(){
  const [items,setItems]=useState<Operation[]>([]),[draft,setDraft]=useState<Operation|null>(null),[tab,setTab]=useState(tabs[0]),[query,setQuery]=useState(""),[filter,setFilter]=useState(""),[view,setView]=useState("Operações"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/operations",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Não foi possível abrir as operações. Verifique o acesso e tente novamente.");return r.json()}).then(d=>setItems(d.operations)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[dirty]);
  function change(next:Operation){if(busy)return;setDraft(next);setDirty(true);setMessage("")}
  function select(item:Operation){if(busy)return;if(dirty&&!window.confirm("Descartar alterações ainda não salvas?"))return;setDraft(structuredClone(item));setDirty(false);setTab(tabs[0]);setMessage("")}
  async function refresh(preserveSelection=false){
    if(busy||(dirty&&!window.confirm("Recarregar a versão salva e descartar o rascunho atual? Exporte o dossiê antes se quiser preservá-lo.")))return;
    setBusy(true);setError("");
    try{const response=await fetch("/api/operations",{cache:"no-store"});if(!response.ok)throw Error("Não foi possível atualizar as operações.");const data=await response.json();setItems(data.operations);if(preserveSelection&&draft)setDraft(data.operations.find((o:Operation)=>o.id===draft.id)||null);else setDraft(null);setDirty(false);setMessage("Registros atualizados.")}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar.")}finally{setBusy(false)}
  }
  async function demo(method:"POST"|"DELETE"){if(method==="DELETE"&&!window.confirm("Limpar apenas os registros marcados como demonstração desta organização?"))return;setBusy(true);setError("");try{const r=await fetch("/api/demo",{method});const d=await r.json();if(!r.ok)throw Error(d.error||"Não foi possível atualizar a demonstração.");if(method==="POST"){setItems(prev=>[d.operation,...prev.filter(o=>o.id!==d.operation.id)]);setDraft(d.operation);setTab("Visão geral");setMessage("Operação sintética carregada. Nenhum dado possui validade real.")}else{setItems(prev=>prev.filter(o=>!o.isDemo));setDraft(v=>v?.isDemo?null:v);setMessage("Registros demonstrativos removidos. Registros normais foram preservados.")}}catch(e){setError(e instanceof Error?e.message:"Falha na demonstração.")}finally{setBusy(false)}}
  async function save(create=false){
    setBusy(true);setError("");setMessage("");
    try{const payload=create?{title:"Nova operação",debtor:"",tribunal:"",process:"",owner:"",source:"",stage:"Entrada",nominal:0,notes:"",tasks:[],checks:["Confirmar titularidade e representação","Conferir ofício requisitório","Conferir decisões e trânsito em julgado","Revisar cálculo e data-base","Verificar cessões, penhoras e impedimentos","Revisar honorários, tributos e valor disponível"].map(title=>({id:crypto.randomUUID(),title,done:false})),proposals:[]}:draft;
      const r=await fetch("/api/operations",{method:create?"POST":"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||"Não foi possível salvar.");const item=data.operation||data;setItems(prev=>create?[item,...prev]:prev.map(o=>o.id===item.id?item:o));setDraft(item);setDirty(false);setMessage("Operação salva no banco de dados.");
    }catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.")}finally{setBusy(false)}
  }
  const visible=items.filter(o=>(!filter||o.workflow.stage===filter)&&[o.id,o.title,o.workflow.client.name,o.workflow.credit.precatoryNumber,o.process,o.owner,o.tribunal].join(" ").toLowerCase().includes(query.toLowerCase()));
  const tasks=items.flatMap(o=>o.tasks.map(t=>({...t,operation:o})));
  const overdue=tasks.filter(t=>!t.done&&t.due&&t.due<new Date().toISOString().slice(0,10));
  function exportCsv(){const cell=(v:unknown)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';download("cp-operacoes.csv","\uFEFF"+[["Operação","Devedor","Tribunal","Responsável","Etapa","Valor nominal"],...visible.map(o=>[o.title,o.debtor,o.tribunal,o.owner,o.stage,o.nominal])].map(row=>row.map(cell).join(";")).join("\r\n"),"text/csv;charset=utf-8")}
  return <main className={styles.app}><aside className={styles.sidebar}><Link href="/"><ArrowLeft size={16}/> Central Precatórios</Link><div className={styles.brand}>CP<span>CENTRAL OPERACIONAL</span></div><nav>{["Operações","Pipeline","Agenda","Relatórios","Integrações"].map(v=><button key={v} onClick={()=>setView(v)} aria-current={view===v?"page":undefined}>{v}</button>)}</nav><p>Área autenticada e isolada por organização.</p><Link href="/conta">Conta e organização</Link></aside>
  <section className={styles.main}><div className={styles.heading}><div><small>UMA OPORTUNIDADE · UM HISTÓRICO · UM PRÓXIMO PASSO</small><h1>{view}</h1><p>Cada oportunidade com contexto, evidências e ação prioritária.</p></div><div className={styles.headingActions}><button disabled={busy||dirty} onClick={()=>demo("POST")}><FlaskConical size={17}/> Carregar demonstração</button><button disabled={busy||dirty||!items.some(o=>o.isDemo)} onClick={()=>demo("DELETE")}><Trash2 size={17}/> Limpar demo</button><button disabled={busy||dirty} onClick={()=>save(true)}><Plus size={18}/> Nova operação</button></div></div>
    {error&&<div role="alert" className={styles.error}>{error} <button disabled={busy} onClick={()=>void refresh()}>Recarregar registros</button></div>}{message&&<p role="status" className={styles.success}>{message}</p>}
    <div className={styles.metrics}><article><small>Operações cadastradas</small><strong>{items.length}</strong></article><article><small>Valor nominal declarado</small><strong>{money(items.reduce((s,o)=>s+o.nominal,0))}</strong></article><article><small>Tarefas em atraso</small><strong>{overdue.length}</strong></article><article><small>Propostas registradas</small><strong>{items.reduce((s,o)=>s+o.proposals.length,0)}</strong></article></div>
    {view==="Integrações"?<section className={styles.card}><h2>Fontes e serviços</h2><DataJudSearch/><h3>Portais oficiais</h3><p>Consultas oficiais abrem no portal de origem. Registre a fonte e o resultado no cadastro da operação.</p>{[["TJSP · precatórios e credores","https://www.tjsp.jus.br/Precatorios/Precatorios/Credores"],["TRF3 · RPV e precatórios","https://www.trf3.jus.br/carta-servicos/rpv-e-precatorios/"],["CNJ · regras de gestão","https://atos.cnj.jus.br/atos/detalhar/3130"]].map(([label,url])=><p key={url}><a href={url} target="_blank" rel="noopener noreferrer"><Link2 size={16}/> {label}</a></p>)}<h3>Conexões ainda não ativadas</h3><p>KYC/KYB, assinatura eletrônica, pagamentos e protocolos precisam de provedores e credenciais. A mesa permite registrar o acompanhamento; não executa esses serviços.</p></section>:
    view==="Relatórios"?<section className={styles.card}><h2>Distribuição por etapa</h2>{stages.map(s=><p key={s}>{s}: <b>{items.filter(o=>o.stage===s).length}</b> · {money(items.filter(o=>o.stage===s).reduce((sum,o)=>sum+o.nominal,0))}</p>)}<button onClick={exportCsv}><Download size={16}/> Exportar operações CSV</button><h3>Origem das oportunidades</h3>{Array.from(new Set(items.map(o=>o.source||"Não informada"))).map(s=><p key={s}>{s}: {items.filter(o=>(o.source||"Não informada")===s).length}</p>)}</section>:
    <><div className={styles.toolbar}><label><Search size={16}/><input aria-label="Buscar operações" placeholder="Buscar ID, cliente, processo ou precatório" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar etapa" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas as etapas</option>{["NEW","TRIAGE","QUERY","VALIDATION","DOCUMENTS","LEGAL_REVIEW","APPROVED","PROPOSAL","NEGOTIATION","ACCEPTED","CESSION","POST_CESSION","COMPLETED","BLOCKED"].map(s=><option key={s}>{s}</option>)}</select><button onClick={exportCsv}><Download size={16}/> CSV</button></div>
    {view==="Pipeline"&&<div className={styles.board}>{stages.map(stage=><section key={stage}><h3>{stage} <small>{visible.filter(o=>o.stage===stage).length}</small></h3>{visible.filter(o=>o.stage===stage).map(o=><button key={o.id} onClick={()=>select(o)}><b>{o.title}</b><span>{o.debtor||"Devedor pendente"}</span><span>{money(o.nominal)}</span><small>{o.owner||"Sem responsável"}</small></button>)}</section>)}</div>}
    {view==="Agenda"&&<section className={styles.card}><h2>Agenda de acompanhamento</h2>{tasks.length===0?<p>Nenhuma tarefa cadastrada. Abra uma operação e adicione a próxima ação.</p>:tasks.toSorted((a,b)=>a.due.localeCompare(b.due)).map(t=><button className={styles.agenda} key={t.id} onClick={()=>select(t.operation)}><span>{t.done?"Concluída":"Pendente"}</span><b>{t.title}</b><span>{t.due||"Sem prazo"} · {t.operation.title}</span></button>)}</section>}
    <div className={styles.columns}>{view==="Operações"&&<section className={styles.list}>{loading?<p role="status">Carregando oportunidades…</p>:error?null:visible.length===0?<div className={styles.card}><ClipboardList/><h2>{items.length?"Nenhum resultado":"Sua central está pronta."}</h2><p>{items.length?"Ajuste a busca ou limpe os filtros.":"Crie uma operação ou carregue o caso sintético para demonstrar o fluxo."}</p>{items.length>0&&<button onClick={()=>{setQuery("");setFilter("")}}>Limpar filtros</button>}</div>:visible.map(o=><button key={o.id} onClick={()=>select(o)} aria-pressed={draft?.id===o.id}><small>{o.workflow.stage}{o.isDemo?" · DEMO":""}</small><b>{o.title}</b><span>{o.workflow.client.name||o.debtor||"Cliente não informado"}</span><strong>{money(o.nominal)}</strong><span>{o.workflow.nextAction.title||"Defina o próximo passo"}</span></button>)}</section>}
    {draft&&<section className={styles.detail}>{draft.isDemo&&<div className={styles.demoBanner}>DADOS DE DEMONSTRAÇÃO — SEM VALIDADE REAL</div>}<div className={styles.detailHead}><div><small>ID {draft.id.slice(0,8).toUpperCase()} · {draft.workflow.stage} · VERSÃO {draft.version} · {dirty?"ALTERAÇÕES NÃO SALVAS":"REGISTRO SALVO"}</small><h2>{draft.title}</h2><p>{draft.workflow.nextAction.title||"Defina o próximo passo"}</p></div><button disabled={busy||!dirty} onClick={()=>save()}><Save size={16}/>{busy?"Salvando…":"Salvar"}</button></div><nav className={styles.tabs} role="tablist" aria-label="Áreas da oportunidade">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    {["Visão geral","Consulta e validação","Jurídico","Precificação","Negociação","Cessão","Monitoramento"].includes(tab)&&<OperationalCase workflow={draft.workflow} persistedStage={items.find(o=>o.id===draft.id)?.workflow.stage||draft.workflow.stage} mode={tab} onChange={workflow=>change({...draft,workflow})}/>} 
    {tab==="Cadastro"&&<div className={styles.form}><div className={styles.fields}>{([['title','Nome da operação'],['debtor','Ente devedor'],['tribunal','Tribunal'],['process','Processo / precatório'],['owner','Responsável'],['source','Origem / fonte consultada']] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} maxLength={key==="source"?240:key==="tribunal"||key==="process"?100:160} onChange={e=>change({...draft,[key]:e.target.value})}/></label>)}<label>Etapa legada<select value={draft.stage} onChange={e=>change({...draft,stage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Valor nominal (R$)<input type="number" min="0" step="0.01" value={draft.nominal} onChange={e=>change({...draft,nominal:Number(e.target.value),workflow:{...draft.workflow,credit:{...draft.workflow.credit,grossAmount:Number(e.target.value)}}})}/></label></div><label>Notas, fontes, protocolo e próximos passos<textarea rows={6} value={draft.notes} maxLength={12000} onChange={e=>change({...draft,notes:e.target.value})}/></label><p>Etapas são registros de acompanhamento interno. Marcar “Encerrado” não transfere o crédito ou movimenta dinheiro.</p><button onClick={()=>download(`dossie-${draft.id}-v${draft.version}.json`,JSON.stringify({...draft,dossier:{generatedAt:new Date().toISOString(),version:draft.version,warning:"Dossiê operacional. Revisão jurídica humana permanece obrigatória."}},null,2),"application/json")}><Download size={16}/> Gerar dossiê versionado</button></div>}
    {tab==="Tarefas"&&<div className={styles.form}><button onClick={()=>change({...draft,tasks:[...draft.tasks,{id:crypto.randomUUID(),title:"Nova tarefa",due:"",done:false}]})}><Plus size={16}/> Adicionar tarefa</button>{draft.tasks.map((t,i)=><div className={styles.task} key={t.id}><input type="checkbox" aria-label={`Concluir ${t.title}`} checked={t.done} onChange={e=>change({...draft,tasks:draft.tasks.map((v,j)=>j===i?{...v,done:e.target.checked}:v)})}/><input aria-label="Descrição da tarefa" value={t.title} onChange={e=>change({...draft,tasks:draft.tasks.map((v,j)=>j===i?{...v,title:e.target.value}:v)})}/><input aria-label="Prazo da tarefa" type="date" value={t.due} onChange={e=>change({...draft,tasks:draft.tasks.map((v,j)=>j===i?{...v,due:e.target.value}:v)})}/></div>)}</div>}
    {tab==="Diligência"&&<div className={styles.form}><h3>{draft.checks.filter(c=>c.done).length} de {draft.checks.length} verificações concluídas</h3><p>Checklist de trabalho preenchido pela equipe; não valida automaticamente documentos.</p>{draft.checks.map((c,i)=><label className={styles.check} key={c.id}><input type="checkbox" checked={c.done} onChange={e=>change({...draft,checks:draft.checks.map((v,j)=>j===i?{...v,done:e.target.checked}:v)})}/>{c.title}</label>)}</div>}
    {tab==="Documentos"&&<div className={styles.form}><Documents key={draft.id} operation={draft.id}/></div>}
    {tab==="Histórico"&&<div className={styles.form}><AuditTrail operationId={draft.id}/><h3>Histórico legado da operação</h3>{draft.history.toReversed().map((h,i)=><article className={styles.event} key={i}><Layers size={16}/><div><b>{h.text}</b><p>{new Date(h.at).toLocaleString("pt-BR")}</p></div></article>)}</div>}
    </section>}</div></>}
  </section></main>
}
