"use client";
import {useEffect,useState} from "react";
import styles from "./operations.module.css";
type Finding={mechanism:string;robots:string;entityOptions?:number;observedRequest?:string;sampleResult?:string;acquisition:string;limitation:string};
type Snapshot={id:string;sourceId:string;name:string;url:string;status:string;collectedAt:string;httpStatus:number;durationMs:number;contentHash:string;links:{label:string;url:string}[];error:string;changed:boolean;robotsStatus:string;accessStatus:string;finalUrl:string;contentType:string;discoveryStatus:string;acquisitionStatus:string;diagnostics:{mechanism:string;forms:{method:string;action:string;controls:string[];entityOptions:number;captcha:boolean}[];downloads:{url:string;type:string}[];scripts:string[];iframes:string[];fieldNames:string[]}};
type Source={id:string;name:string;url:string;investigation:Finding;latest:Snapshot|null};type Run={id:string;startedAt:string;finishedAt:string;status:string;summary:Record<string,number>};
export default function SourceMonitorPanel(){const[data,setData]=useState<{sources:Source[];snapshots:Snapshot[];runs:Run[];notice:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function refresh(){const r=await fetch("/api/capture/sources",{cache:"no-store"});if(r.ok)setData(await r.json())}useEffect(()=>{let active=true;fetch("/api/capture/sources",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(active&&d)setData(d)}).catch(()=>{});return()=>{active=false}},[]);
 async function run(){setBusy(true);setMessage("");try{const r=await fetch("/api/capture/sources",{method:"POST"}),d=await r.json();if(!r.ok)throw Error(d.error||"A verificação falhou.");setMessage(`${d.run.summary.accessible} páginas acessíveis · ${d.run.summary.robotsUnverified} robots.txt sem confirmação · ${d.run.summary.failed} falhas de acesso · 0 leads criados. ${d.notice}`);await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Falha na verificação.");await refresh()}finally{setBusy(false)}}
 return <section className={styles.acquisitionPanel} aria-label="Central de Captação"><div className={styles.acquisitionHead}><div><span>CP 2.3 · DIAGNÓSTICO DE FONTES</span><h2>Central de Captação</h2><p>A saúde da página, acesso, mecanismo de dados e aquisição têm estados separados. O diagnóstico não cria leads.</p></div><button disabled={busy} onClick={()=>void run()}>{busy?"Diagnosticando fontes…":"Executar diagnóstico"}</button></div>
 <div className={styles.captureNotice}><b>Captação parcial · nenhuma fonte automática de credores foi confirmada</b><span>TJSP/CAC: captura assistida por CAPTCHA. e-SAJ: consulta por entidade em validação; amostras sem registros atuais não provam ausência. Lista Geral e comunicados: histórico, sem uso como saldo atual. Se um canal não fornecer a ficha, use a fonte oficial alternativa e importe para o mesmo registro CP.</span></div>
 <div className={styles.captureNotice}><b>Captura CAC assistida</b><span>Esta fonte exige uma etapa humana para concluir a consulta. Abra o CAC, conclua a etapa solicitada pelo TJSP e gere o relatório. Depois importe CSV, XLS, XLSX, PDF ou ZIP; o CP perfila, normaliza, deduplica, reconcilia, qualifica e audita os registros.</span><div className={styles.captureLinks}><a href="https://www.tjsp.jus.br/cac/scp/webrelpubliclstpagprecatpendentes.aspx" target="_blank" rel="noreferrer">Abrir consulta TJSP/CAC ↗</a><a href="#lead-list-import">Importar resultado CAC ↓</a></div></div>
 {message&&<p role="status" className={styles.captureMessage}>{message}</p>}
 <div className={styles.leadTableWrap}><table className={styles.leadTable}><thead><tr><th>Fonte</th><th>Automação</th><th>Intervenção</th><th>Dados / mecanismo</th><th>Saúde e aquisição</th></tr></thead><tbody>{data?.sources.map(source=>{const x=source.investigation,s=source.latest;return <tr key={source.id}><td><b>{source.name}</b><small><a href={source.url} target="_blank" rel="noreferrer">Abrir fonte oficial ↗</a></small></td><td>{x.acquisition==="CAPTACAO_ASSISTIDA"?"Assistida":x.acquisition==="QUERY_ADAPTER_NOT_IMPLEMENTED"?"Consulta pública · adapter pendente":x.acquisition==="ASSISTED_VALIDATION"?"Validando":"Catálogo / referência"}</td><td>{x.acquisition==="CAPTACAO_ASSISTIDA"?"CAPTCHA":x.robots.startsWith("UNVERIFIED")?"Robots sem confirmação":"Nenhuma identificada"}</td><td>{x.mechanism}{x.entityOptions?` · ${x.entityOptions} entidades`:""}<small>{x.sampleResult}</small></td><td><b>{s?`Página ${s.httpStatus===200?"ACESSÍVEL":"COM FALHA"} · robots ${s.robotsStatus}`:"Ainda não executado"}</b><small>Dados: {s?.discoveryStatus||x.acquisition} · aquisição: {s?.acquisitionStatus||x.acquisition}</small><small>Último diagnóstico: {s?new Date(s.collectedAt).toLocaleString("pt-BR"):"sem execução"}</small></td></tr>})||<tr><td colSpan={5}>Carregando matriz de fontes…</td></tr>}</tbody></table></div>
 <details><summary>Diagnóstico técnico e evidências ({data?.snapshots.length||0} snapshots)</summary>{data?.sources.map(source=>{const s=source.latest,x=source.investigation;return <article className={styles.sourceChange} key={source.id}><b>{source.name} · {x.acquisition}</b><span>{x.limitation}</span><span>Robots: {s?.robotsStatus||x.robots} · Acesso: {s?.accessStatus||"a diagnosticar"} · Destino: {s?.finalUrl||source.url}</span>{x.observedRequest&&<code>{x.observedRequest}</code>}{s&&<><span>HTTP {s.httpStatus} · {s.contentType||"tipo não informado"} · coleta {new Date(s.collectedAt).toLocaleString("pt-BR")}</span><span>Mecanismo: {s.diagnostics.mechanism} · formulários {s.diagnostics.forms.length} · opções de entidade {s.diagnostics.forms.reduce((n,f)=>n+f.entityOptions,0)} · captcha {s.diagnostics.forms.some(f=>f.captcha)?"sim":"não detectado"}</span>{s.diagnostics.forms.map((f,i)=><span key={i}>Formulário {i+1}: {f.method} {f.action} · campos {f.controls.join(", ")||"não expostos no HTML estático"}</span>)}{s.links.slice(0,20).map(link=><a key={link.url} href={link.url} target="_blank" rel="noreferrer">{link.label} ↗</a>)}{s.error&&<span>{s.error}</span>}</>}</article>})}</details>
 <details><summary>O que mudou? · histórico de páginas ({data?.snapshots.filter(x=>x.changed).length||0})</summary>{data?.snapshots.filter(x=>x.changed).length?data.snapshots.filter(x=>x.changed).map(s=><article className={styles.sourceChange} key={s.id}><b>{s.name}</b><span>{s.status} · HTTP {s.httpStatus} · robots {s.robotsStatus} · aquisição {s.acquisitionStatus} · {new Date(s.collectedAt).toLocaleString("pt-BR")}</span><code>SHA-256 {s.contentHash}</code></article>):<p>Nenhuma mudança de catálogo detectada. Isso não comprova estabilidade dos dados de credores.</p>}</details>
 <details><summary>Execuções de diagnóstico ({data?.runs.length||0})</summary>{data?.runs.length?data.runs.map(r=><article className={styles.sourceChange} key={r.id}><b>{r.status} · {new Date(r.startedAt).toLocaleString("pt-BR")}</b><span>{r.summary.sources} fontes · {r.summary.accessible||0} acessíveis · {r.summary.failed} falhas · 0 leads (diagnóstico apenas)</span></article>):<p>Nenhuma execução registrada.</p>}</details><p className={styles.sourceMonitorNote}>{data?.notice} Agendamento recorrente permanece inativo sem worker configurado.</p></section>
}
