import { NextResponse } from "next/server";
import { requireTenantPermission } from "@/lib/tenant";
import { appendAudit } from "@/lib/audit";
import { listSourceRuns, listSourceSnapshots, officialSources, runOfficialCatalogSync } from "@/lib/source-monitor";
export const runtime="nodejs",maxDuration=120;
export async function GET(request:Request){try{const tenant=await requireTenantPermission(request.headers,"operation:read"),[runs,snapshots]=await Promise.all([listSourceRuns(tenant.organizationId),listSourceSnapshots(tenant.organizationId)]);const findings:Record<string,Record<string,unknown>>={
 "tjsp-esaj":{mechanism:"PUBLIC_ENTITY_QUERY",robots:"UNVERIFIED (robots.txt HTTP 404)",entityOptions:870,observedRequest:"GET /portalDevedor/consultarListaPagamentos.do?dadosParaConsulta.pagamento.entidadeDevedora.cdPessoa={id}",sampleResult:"5 entidades consultadas; as cinco responderam HTTP 200, mas mostraram aviso sem lista pendente e sem pagamento em 2026. Amostra limitada: zero não prova ausência de dados em outras entidades/anos.",acquisition:"QUERY_ADAPTER_NOT_IMPLEMENTED",limitation:"Consulta por entidade. O próprio e-SAJ avisa que fundações, autarquias e universidades podem estar vinculadas à entidade responsável pelo pagamento; repetir em entidade correta e anos disponibilizados antes de concluir."},
 "tjsp-cac-pending":{mechanism:"PUBLIC_QUERY_WITH_CAPTCHA",robots:"VERIFIED · robots.txt has no rule for /cac/scp",entityOptions:684,observedRequest:"Geração de relatório na interface pública CAC",sampleResult:"O relatório requer CAPTCHA; não submetido nem contornado.",acquisition:"CAPTACAO_ASSISTIDA",limitation:"Fonte mais promissora para listas pendentes, mas coleta recorrente sem operador não é apropriada enquanto o relatório exigir CAPTCHA."},
 "tjsp-general":{mechanism:"STATIC_CATEGORY_CATALOG",robots:"VERIFIED",sampleResult:"Categorias municipal/estadual levam a Comunicados; itens verificados são arquivos históricos (municipais observados desde 2014; estaduais até 2013).",acquisition:"HISTORICAL_ONLY",limitation:"Não qualificar como saldo atual."},
 "tjsp-pending":{mechanism:"OFFICIAL_SOURCE_INDEX",robots:"VERIFIED",sampleResult:"Página índice encaminha às listas CAC e e-SAJ; não contém registros inline.",acquisition:"NOT_IMPLEMENTED",limitation:"Página de navegação, não dataset."},
 "tjsp-creditors":{mechanism:"OFFICIAL_SOURCE_INDEX",robots:"VERIFIED",sampleResult:"Página organiza links oficiais para fontes distintas.",acquisition:"NOT_IMPLEMENTED",limitation:"Não contém registros inline."},
 "tjsp-notices":{mechanism:"PUBLIC_HTML_CATALOG",robots:"VERIFIED",sampleResult:"Catálogo municipal expõe comunicados e PDFs históricos.",acquisition:"HISTORICAL_ONLY",limitation:"Verificar data do documento antes de qualquer qualificação."},
 "tjsp-debtors":{mechanism:"REFERENCE_CATALOG",robots:"VERIFIED",sampleResult:"Cadastro de entidades devedoras, não lista de credores.",acquisition:"COMPLEMENTARY_ONLY",limitation:"Use para normalizar devedor/município, nunca como lead."},
 "tjsp-depre-notices":{mechanism:"PUBLIC_NOTICES",robots:"UNKNOWN",sampleResult:"Página oficial de comunicados; dataset de credores não confirmado.",acquisition:"NOT_DISCOVERED",limitation:"Diagnosticar destino/estrutura em execução."}
 };return NextResponse.json({sources:officialSources.map(source=>({...source,mode:"PUBLIC_CATALOG_MONITOR",investigation:findings[source.id],latest:snapshots.find(s=>s.sourceId===source.id)||null})),runs,snapshots,notice:"Estados separados: saúde da página, robots.txt, descoberta do mecanismo e aquisição de registros. Páginas acessíveis não significam aquisição funcionando. Nenhuma captura de credores foi concluída nesta investigação."},{headers:{"cache-control":"no-store"}})}catch(e){if(e instanceof Response)return e;return NextResponse.json({error:"Não foi possível carregar a Central de Captação."},{status:500})}}
export async function POST(request:Request){let tenant:Awaited<ReturnType<typeof requireTenantPermission>>|undefined;try{tenant=await requireTenantPermission(request.headers,"operation:write");const result=await runOfficialCatalogSync({organizationId:tenant.organizationId,userId:tenant.userId,onStarted:async(runId,startedAt)=>appendAudit({organizationId:tenant!.organizationId,actorUserId:tenant!.userId,action:"SOURCE_SYNC_STARTED",entityType:"capture_source_run",entityId:runId,previousStateSummary:{},nextStateSummary:{status:"RUNNING",startedAt},metadata:{adapter:"official-public-source-diagnostic",sourceCount:officialSources.length},requestId:request.headers.get("x-request-id")||crypto.randomUUID(),source:"CP_2_3"})});await appendAudit({organizationId:tenant.organizationId,actorUserId:tenant.userId,action:result.status==="FAILED"?"SOURCE_SYNC_FAILED":"SOURCE_SYNC_COMPLETED",entityType:"capture_source_run",entityId:result.id,previousStateSummary:{status:"RUNNING"},nextStateSummary:{status:result.status,...result.summary},metadata:{sources:JSON.stringify(result.sources.map(s=>({id:s.sourceId,status:s.status,robots:s.robotsStatus,access:s.accessStatus,discovery:s.discoveryStatus,acquisition:s.acquisitionStatus})))},requestId:request.headers.get("x-request-id")||crypto.randomUUID(),source:"CP_2_3"});return NextResponse.json({run:result,notice:"Diagnóstico de página e mecanismo de acesso. Não baixa listas, não cria leads e não executa consultas de entidades."},{status:result.status==="FAILED"?502:200})}catch(e){if(e instanceof Response)return e;if(tenant&&e instanceof Error&&e.message!=="Execução já em andamento.")await appendAudit({organizationId:tenant.organizationId,actorUserId:tenant.userId,action:"SOURCE_SYNC_FAILED",entityType:"capture_source_run",entityId:crypto.randomUUID(),previousStateSummary:{},nextStateSummary:{status:"FAILED"},metadata:{reason:e.message.slice(0,300)},requestId:request.headers.get("x-request-id")||crypto.randomUUID(),source:"CP_2_3"}).catch(()=>{});const status=e instanceof Error&&e.message==="Execução já em andamento."?409:500;return NextResponse.json({error:e instanceof Error?e.message:"Falha na verificação das fontes."},{status})}}
