import { requireExplicitDatabaseUrl } from "./database-target.mjs";
import { createClient } from "@libsql/client";
import { buildEvidenceCandidates, resolveEvidenceCandidatesForAcquisition, type SourceAcquisitionResult } from "../src/lib/research-pipeline";
import { listOfficialEvidence } from "../src/lib/autonomous-acquisition";
import { persistResolvedOfficialEvidence } from "../src/lib/evidence-persistence";
import { appendAudit } from "../src/lib/audit";
const c=createClient({url:requireExplicitDatabaseUrl(),authToken:process.env.DATABASE_AUTH_TOKEN});const org="nIGADhUkSbiSBSsPl4z08FQ2qIaH3E0u";
const official=[
 {depre:"0038850-88.2017.8.26.0500",url:"https://portal-api.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/511454721404472145114514.pdf",reference:"PMC.2023.00023499-09",title:"Diário Oficial de Campinas — proposta de acordo deferida",raw:"Registro oficial relaciona o DEPRE a titular/advogado e processo SEI; a publicação contém mais de uma entrada histórica para o mesmo DEPRE."},
 {depre:"0165056-11.2021.8.26.0500",url:"https://portal-adm.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/561915106409510645619126.pdf",reference:"PMC.2023.00075698-85",title:"Diário Oficial de Campinas — ordem cronológica DEPRE",raw:"Registro oficial relaciona o processo DEPRE a Sebastião Gonçalves de Morais, advogado Luiz Carlos Lima e processo SEI."},
];
const targets=["0038850-88.2017.8.26.0500","0165056-11.2021.8.26.0500","0246430-49.2021.8.26.0500","0149031-15.2024.8.26.0500","0078231-59.2024.8.26.0500"];
const rows=await c.execute({sql:"SELECT id,workflow FROM operations WHERE organization_id=? AND json_extract(workflow,'$.credit.numeroProcessoDEPRE') IN (?,?,?,?,?)",args:[org,...targets]});const ids=new Map<string,string>();for(const raw of rows.rows){const r=raw as Record<string,unknown>;const w=JSON.parse(String(r.workflow)) as {credit?:{numeroProcessoDEPRE?:string}};ids.set(String(w.credit?.numeroProcessoDEPRE),String(r.id));}
const out:unknown[]=[];
for(const depre of targets){const found=official.find(x=>x.depre===depre);if(!found){out.push({depre,status:"MANUAL_REQUIRED",evidence:"none",nextAction:"Abrir a publicação oficial municipal/TJSP, pesquisar o DEPRE, capturar URL e referência e anexar para validação."});continue;}const result:SourceAcquisitionResult={provider:"ASSISTED_OFFICIAL_WEB",source:"Diário Oficial de Campinas",sourceId:"campinas-diario-oficial",route:"official-pdf-manual",requestedIdentifier:depre,normalizedIdentifier:depre.replace(/\D/g,""),startedAt:new Date().toISOString(),completedAt:new Date().toISOString(),durationMs:0,status:"SUCCESS",requestAttempted:true,httpStatus:200,sourceUrl:found.url,officialSourceUrl:found.url,errorCode:null,errorMessage:null,rawPayload:{excerpt:found.raw},metadata:{reference:found.reference},documentaryCandidates:[{documentType:"OFFICIAL_RECORD",documentIdentifier:found.reference,reference:found.reference,officialSourceUrl:found.url,title:found.title,status:"COLLECTED",evidenceStrength:"MEDIUM",notes:"Documento oficial localizado por pesquisa assistida; não qualifica automaticamente DOCUMENTAÇÃO 2/2."}]};const existing=await listOfficialEvidence(ids.get(depre)!,org,c);const candidates=buildEvidenceCandidates(result);const resolved=resolveEvidenceCandidatesForAcquisition(result,existing);const persisted=[];for(const item of resolved)persisted.push(await persistResolvedOfficialEvidence(item,{organizationId:org,operationId:ids.get(depre)!,client:c},existing));await appendAudit({organizationId:org,actorUserId:"analyst:assisted-research",action:"OFFICIAL_EVIDENCE_RECORDED",entityType:"operation",entityId:ids.get(depre)!,previousStateSummary:{},nextStateSummary:{sourceStatus:"SUCCESS",documentaryEvidence:"COLLECTED_MEDIUM"},metadata:{depre,source:result.source,route:result.route,officialUrl:found.url,reference:found.reference,qualifiesForDocumentation:false},requestId:`assisted-${depre}-${found.reference}`,source:"ASSISTED_OFFICIAL_RESEARCH"},c);out.push({depre,status:"SUCCESS",source:result.source,route:result.route,url:found.url,reference:found.reference,candidates:candidates.length,resolved:resolved.length,persisted:persisted.map(x=>x.status),documentation:"0/2",nextAction:"Confirmar manualmente titular/processo e buscar segundo documento oficial distinto."});}
console.log(JSON.stringify({targets:targets.length,results:out},null,2));
