import { requireExplicitDatabaseUrl } from "./database-target.mjs";
import { createClient } from "@libsql/client";
import { buildEvidenceCandidates, resolveEvidenceCandidatesForAcquisition, type SourceAcquisitionResult } from "../src/lib/research-pipeline";
import { listOfficialEvidence } from "../src/lib/autonomous-acquisition";
import { persistResolvedOfficialEvidence } from "../src/lib/evidence-persistence";
import { appendAudit } from "../src/lib/audit";
const c=createClient({url:requireExplicitDatabaseUrl(),authToken:process.env.DATABASE_AUTH_TOKEN});const org="nIGADhUkSbiSBSsPl4z08FQ2qIaH3E0u";
const docs=[
 {depre:"0038850-88.2017.8.26.0500",url:"https://portal-api.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/1882658638.pdf",ref:"PMC.2021.00051374-90",date:"2021-09-27",entries:["LÚCIA HELENA SILVEIRA DE FREITAS BLANDY / DANIEL KRAHEMBUHL WANDERLEY / PMC.2021.00051374-90","NELSON BARTHELSON / DANIEL KRAHEMBUHL WANDERLEY / PMC.2021.00051365-07"]},
 {depre:"0038850-88.2017.8.26.0500",url:"https://portal-api.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/511454721404472145114514.pdf",ref:"PMC.2023.00023499-09",date:"2023-04-14",entries:["LUCIA HELENA SILVEIRA DE FREITAS BLANDY / DANIEL KRAHEMBUHL WANDERLEY / PMC.2023.00023499-09"]},
 {depre:"0165056-11.2021.8.26.0500",url:"https://portal-adm.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/511454721404472145114514.pdf",ref:"PMC.2023.00021248-18",date:"2023-04-14",entries:["SEBASTIÃO GONÇALVES DE MORAIS / LUIZ CARLOS LIMA / PMC.2023.00021248-18"]},
 {depre:"0165056-11.2021.8.26.0500",url:"https://portal-adm.campinas.sp.gov.br/sites/default/files/publicacoes-dom/dom/561915106409510645619126.pdf",ref:"PMC.2023.00075698-85",date:"2023-09-26",entries:["LUIZ CARLOS LIMA / LUIZ CARLOS LIMA / PMC.2023.00075698-85"]},
];
const targets=["0038850-88.2017.8.26.0500","0165056-11.2021.8.26.0500"];const rows=await c.execute({sql:"SELECT id,workflow FROM operations WHERE organization_id=? AND json_extract(workflow,'$.credit.numeroProcessoDEPRE') IN (?,?)",args:[org,...targets]});const ids=new Map<string,string>();for(const raw of rows.rows){const r=raw as Record<string,unknown>;const w=JSON.parse(String(r.workflow)) as {credit?:{numeroProcessoDEPRE?:string}};ids.set(String(w.credit?.numeroProcessoDEPRE),String(r.id));}
const persisted=[] as unknown[];for(const item of docs){const operationId=ids.get(item.depre)!;const result:SourceAcquisitionResult={provider:"ASSISTED_OFFICIAL_WEB",source:"Diário Oficial de Campinas",sourceId:"campinas-diario-oficial",route:"official-pdf-manual",requestedIdentifier:item.depre,normalizedIdentifier:item.depre.replace(/\D/g,""),startedAt:new Date().toISOString(),completedAt:new Date().toISOString(),durationMs:0,status:"SUCCESS",requestAttempted:true,httpStatus:200,sourceUrl:item.url,officialSourceUrl:item.url,errorCode:null,errorMessage:null,rawPayload:{publicationDate:item.date,historicalEntries:item.entries},metadata:{publicationDate:item.date,reference:item.ref},documentaryCandidates:[{documentType:"OFFICIAL_RECORD",documentIdentifier:item.ref,reference:item.ref,officialSourceUrl:item.url,title:"Diário Oficial de Campinas — registro DEPRE",publishedAt:item.date,status:"COLLECTED",evidenceStrength:"MEDIUM",notes:"Relação documental preservada; não qualifica automaticamente DOCUMENTAÇÃO 2/2."}]};const existing=await listOfficialEvidence(operationId,org,c);const resolved=resolveEvidenceCandidatesForAcquisition(result,existing);const saved=[];for(const r of resolved)saved.push(await persistResolvedOfficialEvidence(r,{organizationId:org,operationId,client:c},existing));await appendAudit({organizationId:org,actorUserId:"analyst:assisted-research",action:"DOCUMENT_MATCHED",entityType:"operation",entityId:operationId,previousStateSummary:{},nextStateSummary:{depre:item.depre,publication:item.date,reference:item.ref,relationshipCount:item.entries.length},metadata:{source:"campinas-diario-oficial", url:item.url, fieldLevelProvenance:true, documentaryQualification:false},requestId:`campinas-deepening-${item.depre}-${item.ref}`,source:"CAMPINAS_DOCUMENT_DEEPENING"},c);persisted.push({depre:item.depre,url:item.url,publicationDate:item.date,reference:item.ref,entries:item.entries,resolution:saved.map(x=>x.status)});}
console.log(JSON.stringify({documents:persisted,documentation:"0/2",titularStatus:{[targets[0]]:"NÃO CONFIRMADO — múltiplas entradas históricas",[targets[1]]:"NÃO CONFIRMADO — publicações apresentam relações distintas"}},null,2));
