import { createClient } from "@libsql/client";
import { appendAudit } from "../src/lib/audit";
const c=createClient({url:process.env.DATABASE_URL||"file:central-precatorios.db",authToken:process.env.DATABASE_AUTH_TOKEN});
const org="nIGADhUkSbiSBSsPl4z08FQ2qIaH3E0u";
const depes=["0038850-88.2017.8.26.0500","0149031-15.2024.8.26.0500","0246430-49.2021.8.26.0500","0165056-11.2021.8.26.0500","0078231-59.2024.8.26.0500"];
const before=await c.execute("SELECT (SELECT COUNT(*) FROM operations) operations,(SELECT COUNT(*) FROM official_evidence_documents) evidence,(SELECT COUNT(*) FROM crm_records) crm,(SELECT COUNT(*) FROM crm_tasks) tasks,(SELECT COUNT(*) FROM audit_logs) audits");
const rows=await c.execute({sql:"SELECT id,workflow,debtor,version FROM operations WHERE organization_id=? AND is_demo=0 AND json_extract(workflow,'$.credit.numeroProcessoDEPRE') IN (?,?,?,?,?)",args:[org,...depes]});
if(rows.rows.length!==5)throw new Error(`BATCH_REQUIRES_5_GOT_${rows.rows.length}`);
const matrix=[] as unknown[];
for(const raw of rows.rows){const r=raw as Record<string,unknown>;const w=JSON.parse(String(r.workflow)) as {credit?:Record<string,unknown>};const credit=w.credit??{};const depre=String(credit.numeroProcessoDEPRE);const evidence=await c.execute({sql:"SELECT id,status,evidence_strength,document_type,source_url FROM official_evidence_documents WHERE organization_id=? AND operation_id=? AND status='VERIFIED' AND evidence_strength='STRONG'",args:[org,String(r.id)]});const crm=await c.execute({sql:"SELECT id,stage,next_action_at FROM crm_records WHERE organization_id=? AND operation_id=?",args:[org,String(r.id)]});const jobs=await c.execute({sql:"SELECT error_code,error_message FROM automation_jobs WHERE organization_id=? AND target_id=? ORDER BY created_at DESC LIMIT 1",args:[org,String(r.id)]});await appendAudit({organizationId:org,actorUserId:"system:operational-batch",action:"OPPORTUNITY_UPDATED",entityType:"operation",entityId:String(r.id),previousStateSummary:{},nextStateSummary:{researchStatus:"MANUAL_REQUIRED",documentation:"0/2",readyForAnalyst:false},metadata:{batch:"FIRST_5",depre,sourceAction:"NO_RETRY_BLOCKED_SOURCE"},requestId:`first-batch-${depre}`,source:"OPERATIONAL_BATCH"},c);matrix.push({depre,municipality:credit.municipality??"NÃO INFORMADO",titular:credit.titular??"NÃO CONFIRMADO",processo:credit.processoOriginario??"NÃO LOCALIZADO",valor:credit.valor??"NÃO LOCALIZADO",dataBase:credit.dataBase??"NÃO LOCALIZADO",advogado:credit.advogado??"NÃO LOCALIZADO",oab:credit.oab??"NÃO LOCALIZADO",contact:"NO_CONFIRMED_CONTACT",docs:evidence.rows.length>=2?"2/2":evidence.rows.length===1?"1/2":"0/2",evidence:evidence.rows,coverage:"INSUFFICIENT_COVERAGE",opportunity:"REVIEW",readyForAnalyst:false,crm:crm.rows[0]??null,lastJob:jobs.rows[0]??null,nextAction:"MANUAL_REQUIRED: pesquisa oficial assistida; não repetir rota bloqueada"});}
const after=await c.execute("SELECT (SELECT COUNT(*) FROM operations) operations,(SELECT COUNT(*) FROM official_evidence_documents) evidence,(SELECT COUNT(*) FROM crm_records) crm,(SELECT COUNT(*) FROM crm_tasks) tasks,(SELECT COUNT(*) FROM audit_logs) audits");console.log(JSON.stringify({before:before.rows[0],after:after.rows[0],matrix},null,2));
